	.INSERT "PS:<S6>S6FREQ"	; Frequent word table
	.INSERT "PS:<S6>S6DAT"	; Data file
	.INSERT "PS:<S6>S6PUR"
	.INSERT "PS:<S6>MISC"
	.INSERT "PS:<S6>PARSER"
	.INSERT "PS:<S6>SYNTAX"
	.INSERT "PS:<S6>VERBS"
	.INSERT "PS:<S6>GLOBALS"
	.INSERT "PS:<S6>SHIP"
	.INSERT "PS:<S6>STATION"
	.INSERT "PS:<S6>VILLAGE"

	.INSERT "PS:<S6>S6STR"

	.END
