

; STRINGS ARE DEFINED HERE

STRBEG::

	.GSTR STR?1,"Not Here"
	.GSTR STR?2,"Actor"
	.GSTR STR?3,"Preaction"
	.GSTR STR?4,"PRSI"
	.GSTR STR?5,"PRSO"
	.GSTR STR?6,"OOPS"
	.GSTR STR?7,"AGAIN"
	.GSTR STR?8,"begins"
	.GSTR STR?9,"ends"
	.GSTR STR?10,"leave the game"
	.GSTR STR?11,"restart"
	.GSTR STR?12,"Biting"
	.GSTR STR?13,"climb into"
	.GSTR STR?14,"climb onto"
	.GSTR STR?15,"close"
	.GSTR STR?16,"disconnect the timer"
	.GSTR STR?17,"disconnect the explosive"
	.GSTR STR?18,"dress"
	.GSTR STR?19,"open"
	.GSTR STR?20,"get onto"
	.GSTR STR?21,"get into"
	.GSTR STR?22,"look"
	.GSTR STR?23,"Kicking"
	.GSTR STR?24,"Knocking on"
	.GSTR STR?25,"sound"
	.GSTR STR?26,"look inside"
	.GSTR STR?27,"look through"
	.GSTR STR?28,"indecis"
	.GSTR STR?29,"Pulling"
	.GSTR STR?30,"move"
	.GSTR STR?31,"Trying to destroy"
	.GSTR STR?32,"negat"
	.GSTR STR?33,"ff"
	.GSTR STR?34,"n"
	.GSTR STR?35,"pick"
	.GSTR STR?36,"put it in the presser"
	.GSTR STR?37,"Pushing"
	.GSTR STR?38,"Playing in this way with"
	.GSTR STR?39,"read"
	.GSTR STR?40,"roll"
	.GSTR STR?41,"search"
	.GSTR STR?42,"Turning"
	.GSTR STR?43,"Shaking"
	.GSTR STR?44,"."
	.GSTR STR?45,"smell"
	.GSTR STR?46,"spray"
	.GSTR STR?47,"move that much"
	.GSTR STR?48,"taste"
	.GSTR STR?49,"Touching"
	.GSTR STR?50,"Keyboard is only active following authorization"
	.GSTR STR?51,"You have already made your selection"
	.GSTR STR?52,"That bin is unoccupied"
	.GSTR STR?53,"Error"
	.GSTR STR?54,"Fuel levels at zero"
	.GSTR STR?55,"Course set. Launch in approximately 30 millichrons"
	.GSTR STR?56,"Safety precautions forbid the acceptance of course settings unless both the pilot and copilot seats are occupied"
	.GSTR STR?57,"You are already at that level"
	.GSTR STR?58,"Select a level between 1 and 9"
	.GSTR STR?59,"The instant you press the button, the elevator begins plunging down the shaft! It's worse than just free-fall; the elevator is actually in a power dive!!! You punch frantically at the keypad..."
	.GSTR STR?60,"You have not deposited a coin"
	.GSTR STR?61,"This dispenser offers only 9 selections"
	.GSTR STR?62,"Sorry, that items is sold out. Please contact your PX Officer regarding re-stocking of dispenser"
	.GSTR STR?63,"walk"
	.GSTR STR?64,"wear"
	.GSTR STR?65,"posit"
	.GSTR STR?66,"remove"
	.GSTR STR?67," is as worthwhile as cleaning a grotch cage."
	.GSTR STR?68," accomplishes nothing."
	.GSTR STR?69," has no desirable effect."
	.GSTR STR?70,"Fat chance."
	.GSTR STR?71,"A valiant attempt."
	.GSTR STR?72,"You can't be serious."
	.GSTR STR?73,"Not bloody likely."
	.GSTR STR?74,"What a concept."
	.GSTR STR?75,"Nice try."
	.GSTR STR?76,"You are behaving like a demented Denebian slime devil."
	.GSTR STR?77,"Dream on."
	.GSTR STR?78,"It's the looney bin for you!"
	.GSTR STR?79,"You have lost your mind."
	.GSTR STR?80,"A waste of time."
	.GSTR STR?81,"A worthless action -- and much too difficult for a poorly-written program like this one to handle."
	.GSTR STR?82,"Useless. Unhelpful."
	.GSTR STR?83,"There's another turn down the drain."
	.GSTR STR?84,"Why bother?"
	.GSTR STR?85,"with"
	.GSTR STR?86,"Done. You might remain alive long enough to type EXAMINE MY STUMP. Oops, I guess not."
	.GSTR STR?87,"Okay."
	.GSTR STR?88,"Wow! A hole where your torso used to be!"
	.GSTR STR?89,"I was going to ask you the same question!"
	.GSTR STR?90,"Floyd loves games! Let's play!"
	.GSTR STR?91,"Safety precautions forbid the activation of the vehicle unless both the pilot and copilot seats are occupied"
	.GSTR STR?92,"This form has not been validated by the station commander"
	.GSTR STR?93,"Authorization approved. Use keypad to enter the bin number of the desired robot"
	.GSTR STR?94,"Spacecraft activated. Type in the course heading"
	.GSTR STR?95,"slot"
	.GSTR STR?96,"The quiet, dusty corridors stir disturbing memories. You're back on Resida, the deserted, plague-stricken world where you met Floyd. A hot flush creeps over you, indicating that the virulent disease that conquered this planet is beginnning its insidious work on you"
	.GSTR STR?97,"You find yourself on Deck Five of the Duffy, walking nonchalantly along, when suddenly you remember that you were supposed to have Handwriting Legibility Evaluation Forms -- all nine parts, for every member of the crew -- on Captain Fussbottom's desk by 7800. It's 7790, and those forms are stored on the other side of the ship. You begin running down the corridor, but the floor is turning into a thick syrup. You can hear the Captain calling your name, louder and louder, as you struggle to move your legs"
	.GSTR STR?98,"You gulp down the last of your Ramosian Fire Nectar and ask the andro-waiter for another pitcher. This pub makes the finest Nectar on all of Ramos Two, and you and your shipmates are having a pretty rowdy time. Through the windows of the pub you can see a mighty, ancient castle, shining in the light of the three Ramosian moons. The Fire Nectar spreads through your blood and you begin to feel drowsy"
	.GSTR STR?99,"You wake up in a huge stadium, watching an important ceremony. It's a Stellar Patrol promotion ceremony on Tremain! Suddenly you hear your name echoing over the PA system -- and down below you see YOURSELF walking up the steps to the stage! The presiding admiral describes your heroic deeds on Resida, mentioning that you were awarded the key to the planet, and then asks the ceremonial question, ""Do you accept promotion to Lieutenant First Class?"" You try to yell ""No!"" from your seat in the stands, but the words catch in your throat"
	.GSTR STR?100,"You find yourself floating in a spacepod outside the docking bays of a large space station. All the doors are closed. You snap on the radio, and discover that Floyd is in charge within the station. ""Open the pod bay doors, Floyd,"" you tell him, but he replies, ""I'm sorry, I can't do that,"" and begins laughing and your air is beginning to run out"
	.GSTR STR?101,"At last, the Duffy is approaching Space Station Delta Upsilon Upsilon Phi for the ship's first rec leave in almost six months. It's even worth the six solid days of paperwork necessary for a standard half-day leave. Stationfall is only millichrons away, but suddenly you realize that you're all alone on the Duffy! Frantic, you dash to the deserted bridge, but it's too late to keep the out-of-control Duffy from ramming the massive space station! The hull of the station falls toward you"
	.GSTR STR?102,"You dream of being buried alive in an ancient Egyptian pyramid, inside the sarcophagus with some long-dead pharaoh. Phew, does he stink! You gasp and gag as the air in the coffin runs low.
   This dream, incidentally, is not a particularly unusual one among people who go to sleep inside space suits with limited oxygen supplies."
	.GSTR STR?103,"A movement awakens you in the middle of the night! Through unfocused eyes you see a large machine rolling menacingly closer! A bright light leaps from it, straight toward..."
	.GSTR STR?104,"You collapse from extreme thirst and hunger."
	.GSTR STR?105,"A powerful arc of raw energy bridges the gap between two of the monster's welding extensions. Unfortunately, you were pretty much right between the same two extensions at that moment."
	.GSTR STR?106,"It's too dark to see a thing."
	.GSTR STR?107,"You're not holding"
	.GSTR STR?108,"There's nothing "
	.GSTR STR?109,"You can see"
	.GSTR STR?110,"It seems that"
	.GSTR STR?111,"You can't "
	.GSTR STR?112,"You'll have to "
	.GSTR STR?113,"Look around you.
"
	.GSTR STR?114,"You can't do that from here.
"
	.GSTR STR?115,"You're holding it!
"
	.GSTR STR?116,"[There seems to be a noun missing in that sentence.]
"
	.GSTR STR?117,"You see only blackness.
"
	.GSTR STR?118,"You already did that. Senility strikes again!
"
	.GSTR STR?119,".
"
	.GSTR STR?120,"...

"
	.GSTR STR?121,"Nothing happens.
"
	.GSTR STR?122,"Failed.
"
	.GSTR STR?123,"Okay.
"
	.GSTR STR?124,"Huh?
"
	.GSTR STR?125,"You can't go that way.
"
	.GSTR STR?126,"It already is!
"
	.GSTR STR?127,"""Floyd does not one of those have!""
"
	.GSTR STR?128,"Like most fromitz boards, it is a twisted maze of silicon circuits. It is square, approximately seventeen centimeters on each side.
"
	.GSTR STR?129,"You're neither hungry nor thirsty.
"
	.GSTR STR?130,"Floyd is leaning against the wall, his head lolling to the side. Apparently, someone has heartlessly turned him off."
	.GSTR STR?131,"The only part of the complex robot authorization equipment that is visible to you is a slot (for inserting your form) and a keypad (for typing your selection)."
	.GSTR STR?132,"Request for Stellar Patrol Issue Regulation Black Form Binders Request Form Forms"
	.GSTR STR?133,"[Use numerals: for example, TYPE 5 rather than TYPE FIVE.]
"
	.GSTR STR?134,"The thick side wall of the tank has been blasted open"
	.GSTR STR?135,"Next time, say what number to set it to.
"
	.GSTR STR?136,", hopping mad. ""Why you turn Floyd off?"" he asks accusingly."
	.GSTR STR?137,"Spanning the entire garden is a transparent dome, providing a breathtaking view of the heavens in all their splendor."
	.GSTR STR?138,"The control box contains a keypad for typing the number of the level you want to go to."
	.GSTR STR?139," strike the machine's power source, inducing an overload implosion in said power source."
	.GSTR STR?140,"""The Galaxy's Best Zero-Gee Restaurant"""
	.GSTR STR?141,"The eternal flame has been extinguished!"
	.GSTR STR?142,"Lieutenant First Class"
	.GSTR STR?143,"Through the large, dirty window, you can see Dan's used spaceship lot. The spaceships floating in Dan's lot all have their prices whitewashed on their viewports, along with phrases like ""A steal!"" and ""Just reduced!"""
	.GSTR STR?144,"You are in the heart of the administrative level of the ship, the largest level of the S.P.S. Duffy or any other Stellar Patrol ship for that matter. The corridor continues port and starboard, and a room lies aft of here."
	.GSTR STR?145,"An Ensign appears and informs you that access to this section of Deck Five is restricted to those with a validated Assignment Completion Form QX-17-T. Saluting crisply, she retreats to her unseen guard post."
	.GSTR STR?146,"""STELLAR PATROL
Paperwork Task Force
ID Number: 1451-352-716"""
	.GSTR STR?147,"A slightly wrinkled Patrol uniform is lying here."
	.GSTR STR?148,"This is the largest space in the ship, three decks tall and with the floor area of seven Rigellian buzzball fields. The only exit is fore."
	.GSTR STR?149,"The room is filled to the ceiling with row upon row of pallets filled with boxes. Each box has some writing stamped on the side."
	.GSTR STR?150,"The deck five corridor ends here at the entrance to the cargo bay, to starboard. A smaller entrance leads fore."
	.GSTR STR?151,"He's an amusing and friendly little fellow."
	.GSTR STR?152,"That's me!"
	.GSTR STR?153,"Floyd, he"
	.GSTR STR?154,"paces impatiently"
	.GSTR STR?155,"absent-mindedly recites the first six hundred digits of pi"
	.GSTR STR?156,"recalls the time he bruised his knee"
	.GSTR STR?157,"tells you how much it hurts to repair dents"
	.GSTR STR?158,"chants the death scene from ""Carmen"""
	.GSTR STR?159,"cranes his neck to see what you are doing"
	.GSTR STR?160,"rubs his head affectionately against your shoulder"
	.GSTR STR?161,"examines himself for signs of rust"
	.GSTR STR?162,"absent-mindedly oils one of his joints"
	.GSTR STR?163,"wanders restlessly around the room"
	.GSTR STR?164,"notices a mouse scurrying by and tries to hide behind you"
	.GSTR STR?165,"sings an ancient ballad, totally out of key"
	.GSTR STR?166,"frets about the possibility of his batteries failing"
	.GSTR STR?167,"whistles tunelessly"
	.GSTR STR?168,"boasts about the time he helped someone sharpen a pencil"
	.GSTR STR?169,"yawns and looks bored"
	.GSTR STR?170,"complains about a recent assignment in the forms filing department"
	.GSTR STR?171,"produces a crayon from one of his compartments and scrawls his name on the wall"
	.GSTR STR?172,"Floyd tells Plato about a neat shortcut for calculating seventh order differentials"
	.GSTR STR?173,"Plato tells Floyd one of the ancient legends about the early days of the settlement of the galaxy"
	.GSTR STR?174,"Floyd and Plato discuss their favorite battery recharging techniques"
	.GSTR STR?175,"Plato helps polish a hard-to-reach spot on Floyd's back"
	.GSTR STR?176,"""You like Floyd, don't you, Plato?"" asks Floyd. ""Yes,"" replies the taller robot, ""you're the only robot I've ever met who doesn't call me a nerd."" Floyd smiles"
	.GSTR STR?177,"In a very sad voice, Floyd talks of his friend Lazarus, a medical robot on Resida who was tragically disassembled. Plato responds, ""Now, Floyd, don't fill your head with the sad memories of Lazarus' death. Think instead about the joy-filled times when you and your friend were together."" Floyd seems awed by such wisdom"
	.GSTR STR?178,"Floyd gives Plato a friendly hug"
	.GSTR STR?179,"Floyd stubs his toe and begins to whimper. ""There, there,"" says Plato, ""such a reaction will not reduce the level of pain."" He gives Floyd a little tickle, and Floyd begins giggling and forgets the injury"
	.GSTR STR?180,"Bin number two holds a spindly little robot, a specialized model designed for bursting and decollating multi-part forms. A tiny nameplate on her perforating extension reads ""Helen."""
	.GSTR STR?181,"In the first bin is a bulky robot, obviously intended for heavy-lifting. A brass plate on one of his pneumatic arm lifts says ""Rex."""
	.GSTR STR?182,"   Rex trundles after you. Unfortunately, Rex is not too bright on his best days, and today is not one of them. He forgets to stop when you do; sixteen tons of Rex turn you into a human pancake."
	.GSTR STR?183,"open the hatch"
	.GSTR STR?184,"If you're in spacelane 630-461, keep it down to 26000 kilometers per millichron. There's a stakeout there."
	.GSTR STR?185,"Anyone seen any smokeys in the Nebulon sector?"
	.GSTR STR?186,"I'm looking for a traffic report on spacelane 317-455."
	.GSTR STR?187,"At the conclusion of this recording, your emergency message will be sent. In the meantime, stay calm. Nothing can go wrong <skip> go wrong <skip> go wrong <skip> go wrong.."
	.GSTR STR?188," filling the bay with hot ion gasses. Since you slept through most lectures at boot camp, you may not recall that hot ion gasses are pretty deadly."
	.GSTR STR?189,". Once in space, the truck's air gushes out through the open hatch."
	.GSTR STR?190,", leaving an impressive cloud of ion dust. However, you're in no condition to admire it, since you are now smeared all over the rear wall of the truck."
	.GSTR STR?191,"Fuel level at three-quarters"
	.GSTR STR?192,"Fuel level at one-quarter"
	.GSTR STR?193,"Docking bay one is occupied. Defaulting to bay two"
	.GSTR STR?194,"Arrival at terminus of inputted course. Fuel levels now effectively at zero. Oxygen supply for one person: approximately two chrons"
	.GSTR STR?195,"   As the oxygen runs low, Floyd becomes quite chipper. Never before has he been in such a rust-inhibiting atmosphere. You, on the other hand, are dead."
	.GSTR STR?196," Ramosian tree-mold custard"
	.GSTR STR?197," apricot yogurt"
	.GSTR STR?198," blueberry ice cream"
	.GSTR STR?199,"This is a fairly large space where much of the maintenance work for the station takes place. Some repair work for visiting ships is also done here. The room is filled with all sorts of repair and fabrication machinery. A door leads south, and there's an opening to the north."
	.GSTR STR?200,"I'm really not at all mechanically inclined. My sincerest apologies."
	.GSTR STR?201,"It's a kind of a thingamabob for putting in a, you know, a whosiwhatsis."
	.GSTR STR?202,"This is one of the storage areas. Exits lie to the east and south."
	.GSTR STR?203,"twenty tiny sockets"
	.GSTR STR?204,"The central corridor continues around to the southeast and southwest, but another corridor joins from the north. There's a door to the east and a doorway to the northeast."
	.GSTR STR?205,"The corridor widens here as it approaches the skin of the space station at the point where a Scientific Sub-Module would connect. Sure enough, the connecting tube of a Sub-Module begins just to the north! An auto-door lies to the west. Opposite it, a doorway leads east."
	.GSTR STR?206,"This is the shop for station personnel, selling everything from postcards to chewing gum at inflated prices. Exits lead west and southwest."
	.GSTR STR?207,"In the corner of the PX is a Stellar Patrol dispensing machine, consisting of a screen (displaying the dispenser's ""exciting"" offerings), a slot (for coin insertion), a keypad (for typing your selection), and a hole (where the dispensed item hopefully -- but rarely -- arrives)."
	.GSTR STR?208,"coin slot"
	.GSTR STR?209," In case you were napping during Demolitions Training, this means that you're now a fine layer of ash all over the walls of the PX."
	.GSTR STR?210,"It's a kind of a thingamabob for connecting a, you know, a whosiwhatsis."
	.GSTR STR?211,"This infirmary has the finest diagnostic equipment that unlimited Stellar Patrol budgets can buy. To the east, an ID reader indicates a security door. You can leave to the west or southeast."
	.GSTR STR?212,"This is a modest prison, with three cells. The only exit is west."
	.GSTR STR?213,"The corridor continues around to the northwest and southwest, and an adjoining one heads east."
	.GSTR STR?214,"This central corridor turns northeast and northwest of here. A second corridor begins here and leads south. There are doorways to the southwest, southeast, and east."
	.GSTR STR?215,"This is the Deep-Space Communication Center, which keeps the station in touch with the Stellar Patrol Command and the rest of the Third Galactic Union. Although regulations state that the Comm Center must me monitored around the clock, ten chrons per day, there's no one on duty.
   Most of the equipment here is too complicated for anyone without Deep-Space Communications Training to use. However, the red button of the wide-band emergency beacon is well-marked. The only exit is north."
	.GSTR STR?216," The shock seems to have been a bit too much for your heart."
	.GSTR STR?217,"This is the room where octuplet copies of important forms are stored. Since it is only about a hundred square meters, this room cannot hold more than a few days worth of storage before being dumped to nanofilm. Mercifully, there is an exit to the northeast."
	.GSTR STR?218,"reader"
	.GSTR STR?219,"   The log reader explodes!"
	.GSTR STR?220,"These are by far the nicest living quarters on the station, with separate sleeping, changing, and working cubicles, and a private SanFac. The only exit is west."
	.GSTR STR?221,"Sitting on the Commander's desk is an ordinary-looking log tape. There's a notation printed on it."
	.GSTR STR?222,"""Commander's Log -- 11349.12.2 through 11349.12.4"""
	.GSTR STR?223,"A sturdy safe is welded to the deck next to the desk."
	.GSTR STR?224,"The safe has been blown open! The area around the safe is blackened, and a burnt odor hangs in the air."
	.GSTR STR?225,"hole"
	.GSTR STR?226,"This is the Station Commander's conference room. Doors point north and west."
	.GSTR STR?227,"This is secondary weapons storage deck, but the only weapon deck on a station without a Military Sub-Module. Exit: south."
	.GSTR STR?228,"This is a wide but not very tall docking bay. The station entrance lies to the east."
	.GSTR STR?229,"This cramped dormitory, composed of approximately twenty private cubicles, curves around the northern half of this level, with exits to the southeast and southwest."
	.GSTR STR?230,"You enter one of the cubicles but find nothing of interest."
	.GSTR STR?231,"This warren of tiny cubicles fills the southern half of this level, curving toward exits in the northeast and northwest corners."
	.GSTR STR?232,"This is a crowded but otherwise typical sanitary facility, with rows of showers, toilet stalls, and sinks. There are exits both north and south."
	.GSTR STR?233,"A multiple-function exercise machine sits imposingly on one side of the gym. There is a sign above it."
	.GSTR STR?234,"The exercise machine hums encouraging platitudes as it exercises you to death."
	.GSTR STR?235,"In the corner, next to the dryer, is a large empty spot where the washer should be."
	.GSTR STR?236,"lurches forward and slams shut on your arm. Before you pass out from the pain, you hear a rumbling sound from the presser, but you can't decide whether it sounds more like a chuckle or a burp."
	.GSTR STR?237,"This sixty-seat auditorium is used for lectures, certain large briefings, an occasional live entertainment, and a rare live broadcast over deep-space channels. A projection booth dominates the rear of the room. The only entrance is on the north side of the theatre."
	.GSTR STR?238,"Aaarghhh! The soup is poisoned! It's burning up your insides!!"
	.GSTR STR?239,"This is the primary storage room of the station, with large stockpiles of important items. For example, basic organic materials are needed to supplement the food supply due to the tiny inefficiencies of the recycling process. This is nearly the top level of the Command Module, and the ceiling curves in sharply over the supply room, which curves around to doors at the northwestern and southwestern ends."
	.GSTR STR?240,"detonator"
	.GSTR STR?241,"This is a medium-sized conference room with doors to the south and west."
	.GSTR STR?242,"This is a fairly large conference room with north and south exits."
	.GSTR STR?243,"This station's library has some printed material, such as recently transmitted magazines, but primarily it is a location for reading nanofilm spools, via the spool reader, and accessing the main computer's data banks, via the small computer terminal. There's a door to the north and an exit to the west."
	.GSTR STR?244,"Magazines are not to be removed from the library"
	.GSTR STR?245,"""Collater Repair Manual"""
	.GSTR STR?246,"""Food Processing Unit Repair Manual"""
	.GSTR STR?247,"You stroll down one of the pebbled paths. It circles the garden, passing more exotic plants, and returns to the area near the elevator."
	.GSTR STR?248,"""Emergency Elevator Override Controls
       (See Station Commander
          for access key)"""
	.GSTR STR?249,"open the grating"
	.GSTR STR?250,"These cubicles are for use by any visitors or station personnel beyond the normal complement. The entire barracks seem to be unused as well as deserted. The exit lies to the south, and the barracks curve around to the east."
	.GSTR STR?251,"This is the rather ordinary sanitary facility for the barracks to the north."
	.GSTR STR?252,"This is the station's largest docking bay. A huge door to the east leads into the station.
   Resting in the docking bay is a small ship of obviously alien origin. An open hatch seems to beckon you inward."
	.GSTR STR?253,"Must be a connect-the-dots! And a real easy one, too! None of those dumb numbers to confuse you! Where's my crayon?"
	.GSTR STR?254,"Hmmm. Some kind of alien writing, I presume. If I recall, the Mayor is an expert on that subject."
	.GSTR STR?255,"Lying under the dots is a skeleton, the brittle remains of a member of some unfamiliar alien race."
	.GSTR STR?256,"This is the station's smallest docking bay. You can enter the station to the east."
	.GSTR STR?257,"The corridor, which widens off to the west, ends here. There are doorways north and east of you, and doors to the south and southwest. The door to the north must be a security door, because there's an ID reader next to it."
	.GSTR STR?258,"This is a room where new robots are constructed, old robots are repaired, and unused robots are stored. There's a door to the east."
	.GSTR STR?259,"There's a little robot here who is in the final, training phase of its construction. It is ""sleeping"" on a table, connected to wires which are ""feeding"" it information. The young-looking robot has the name ""Oliver"" engraved on its chestplate."
	.GSTR STR?260,"If we be here when Oliver wakes up, Floyd would like to teach Oliver to play paddle-ball. Paddle-ball helped Floyd forget how lonely and scared he was until he found friends...like you."
	.GSTR STR?261,"Ah, a new robot. Poor fellow; new robots are so mercilessly mistreated by the older robots. Such is our lot."
	.GSTR STR?262,"This is the place where a station's exports are prepared before transfer to the docking bays and subsequent shipment throughout the regional sector. The only exit is west."
	.GSTR STR?263,"This is a fairly comfortable two-person living quarters, significantly roomier than the barracks where most of the ship's personnel live. There's a door to the north, and an opening leads southeast."
	.GSTR STR?264,"This is a fairly comfortable two-person living quarters, significantly roomier than the barracks where most of the ship's personnel live. A door leads north and a doorway south."
	.GSTR STR?265,"This is a fairly comfortable two-person living quarters, significantly roomier than the barracks where most of the ship's personnel live. A doorway lies to the southwest, and there's an auto-door to the north."
	.GSTR STR?266,"A moderately luxurious SanFac, with a pair of bathtubs in addition to the regular fixtures. Exits lead north, northeast, and northwest."
	.GSTR STR?267,"Partway down, you discover discover that the ladder passage to Level Eight is sealed off -- apparently from below."
	.GSTR STR?268,"Outdated forms and expired files are reduced to pulp by this machinery. In addition, raw pulp is constantly being ferried into the station from nearby forest worlds. The output from this plant feeds the station's printing plant, which lies to the southeast."
	.GSTR STR?269,"Someone has presumably been attempting to repair some of the machinery in this room, because they left a drill lying around."
	.GSTR STR?270,"drill"
	.GSTR STR?271,"remove the bit that's in the drill"
	.GSTR STR?272,"Oh, no! The elevator isn't at this floor! It's a long plunge..."
	.GSTR STR?273,"Magnetically-stored data has been damaged; see the Security Officer to have data restored"
	.GSTR STR?274,"This shiny cylindrical corridor is the connector between the Command Module, to the south, and the Scientific Sub-Module, to the north."
	.GSTR STR?275,"This laboratory, which fills most of the middle level of the Sub-Module, is for the study of applications of the various space-related research that takes place on the other levels. Gangways lead up and down, and a door leads north. A connecting tube opens to the south."
	.GSTR STR?276,"This is a small office associated with the lab to the south."
	.GSTR STR?277,"This is the notebook of a certain Professor Schmidt, who was studying a strange pyramid discovered aboard a derelict alien ship and brought here.
   Schmidt traced back the path of the alien ship; the path points out of the galaxy without nearing any star system. Further, extending the path leads straight to one of our smaller neighboring galaxies. Schmidt concludes that the ship and the pyramid are probably well over one billion years old!
   Next, Schmidt studied the wall markings in the alien ship. A series of identical dots, they defied every computerized model of linguistic decipherment! Then, in an inspiration, Schmidt studied the dots for nonvisual properties. His diary vaguely refers to a breakthrough, saying, ""I guess my pal, the mayor, will get to show off his linguistic training.""
   Finally, Schmidt began concentrating his studies on the pyramid itself. He was able to discover very little, blaming this primarily on the unexplained failures of several crucial pieces of lab machinery."
	.GSTR STR?278,"This laboratory conducts research into various space-related physical sciences. Gangways lead up and down, a there's a door to the north."
	.GSTR STR?279,"Various biological sciences, as they related to the environment of space, are studied in this laboratory. There is a gangway leading up, another leading down, and a door leading north."
	.GSTR STR?280,"Lying on one of the desks is a scribbled note."
	.GSTR STR?281,"""Schmidt -- Why didn't I see it until now! Just think of this station as a cell and the pyramid as a mechanized bacterioph"" The note ends at that point; there seem to be some reddish-brown stains on it."
	.GSTR STR?282,"This cramped living area has cubicles for the dozen or so scientists and engineers working in this Sub-Module. The only exit is a gangway leading down."
	.GSTR STR?283,"I don't have a very specific function in the station's robotic organizational scheme, but I do keep the library organized."
	.GSTR STR?284,"Floyd's best friend! Oh, except you, of course!"
	.GSTR STR?285,"Some early poems by Ignatius Tomato. He's my current favorite."
	.GSTR STR?286,"burst into tears and dashes out of the room. A beam leaps from the gun..."
	.GSTR STR?287," the station's reactor turns into a good old-fashioned H-bomb."
	.GSTR STR?288,"You are at the top of an air shaft. There is no gravity here. Handholds lead downward, and a partially open air grate leads out of the shaft."
	.GSTR STR?289,"You are in a large, vertical air duct. Handholds lead up and down."
	.GSTR STR?290,"You have reached the bottom of the air vent. Ducts too small for you to enter lead off laterally. Handholds lead upward, and the entire floor of the duct is another large grating."
	.GSTR STR?291,"The sides ducts are too small to enter!"
	.GSTR STR?292,"This tiny control station allows access to the massive memory banks of the station's computer. Ever since the formation of the Third Galactic Union ended the great interstellar dark age, every Stellar Patrol spaceship, every Patrol space station, has been equipped with a computer bulging with the entire accumulated knowledge of mankind. Never again will humanity be permitted to slip back into the ignorance and savagery of the dark age.
   A ladder leads up to Level Eight, and there's a call button next to the elevator shaft to the north."
	.GSTR STR?293,"The exercise machine reaches you, and performs various repetitions all over your body, proving that exercise isn't always good for you."
	.GSTR STR?294,"You are standing on the bottom of the elevator shaft. The elevator is not in sight. The only place to go is back to the computer room to the south."
	.GSTR STR?295,"There's no way to climb the shaft."
	.GSTR STR?296,"Floyd fires his stun ray nonchalantly in your direction, laughing, as though taunting you. You feel your leg go numb"
	.GSTR STR?297,"Smoke is trickling from the tails of the tiny rockets, as though the duplicate pyramids were preparing for activation and launch"
	.GSTR STR?298,"A blinking light on the reactor goes from yellow to red"
	.GSTR STR?299,"the pyramid, Floyd"
	.GSTR STR?300,"This is an east-west tube, widening as it gets farther from the Command Module."
	.GSTR STR?301,"This is a wide, cheaply constructed space tube, narrowing to the west. There are openings off this ""street"" in virtually every direction, including one leading downward."
	.GSTR STR?302,"Well, there are openings in ALMOST every direction."
	.GSTR STR?303,"This is a tiny living bubble beneath Broadway. The inhabitant, who is nowhere in sight, seems to be in the profession of reading the future for superstitious spacemen."
	.GSTR STR?304,"You have entered a ramshackle, deserted house of worship for one of the many nondescript space-based religions. The decor was obviously intended, but fails, to make the church look larger and less shoddy than it really is. The only exit is south."
	.GSTR STR?305,"This moderately large store sells all kinds of games and other recreational materials. There is also an in-house rec area, featuring a group of simulation booths. The ""street"" lies to the southwest."
	.GSTR STR?306,"groof hunting on Septurion Seven"
	.GSTR STR?307,"a little-known incident during the signing of the Treaty of Gishen IV"
	.GSTR STR?308,"a torrid romance on the tropical planet of San Cupidor"
	.GSTR STR?309,"searching for treasure in a magical underground kingdom"
	.GSTR STR?310,"bullfighting, skydiving, and dental hygiene"
	.GSTR STR?311,"A fine example of trans-molecular platinum foil. The most perfectly reflective material know to man, I am told, and not just on the visual wavelengths! There was a recent rumor that the Rec Shop was to be redecorated using such foil."
	.GSTR STR?312,"Floyd loves anything reflective! Give Floyd a mirror and he'll be happy for days!"
	.GSTR STR?313,"The huge galactic mining conglomerates often open field offices in these space villages, and this is one of those. Miners will haul some promising hunk of space rock into the vicinity, and then come here to sell the rights to it. You can leave to the west."
	.GSTR STR?314,"Some miner has left a headlamp here."
	.GSTR STR?315,"You have entered a surprisingly old-fashioned looking tonsorial parlor. A space village seems to be the last place in the civilized galaxy where someone can go to have their hair or fur trimmed by an actual human being. The barber isn't here, though. Doors lead northwest and west."
	.GSTR STR?316,"This is a small convenience store, the main source of food and living supplies for this village, as well as a supplement supply for personnel from the space station proper. The shelves are pretty bare, and there is no one in sight. Exits lead north, east, southeast and south."
	.GSTR STR?317,"A small, translucent plastic bag is sitting on one of the shelves."
	.GSTR STR?318,", delectable, moist boysenberry-flavored taffy"
	.GSTR STR?319,"This shop, with exits to the northeast and southeast, sells a variety of animals. Many a lonely spacer has discovered the joys a pet can bring, and this shop features animals of both terrestrial and alien origin. A large sign advertises this month's special."
	.GSTR STR?320,"You can see the faint outline of a panel in the ceiling."
	.GSTR STR?321,"This sprawling old cargo ship, its engines long ago cannibalized for spare parts, has been converted into a store for supplies and curios. There's an eye-catching sign on the wall. Passageways lead in many directions, and there's an opening in the floor."
	.GSTR STR?322,"""FREZONE (tm) Liquid Gorzium Explosive
Instructions for use:
1. Insert explosive in hole of appropriate diameter.
2. Attach detonator to explosive and timer.
3. Set timer.
4. Vamoose.
NOTE: Do not expose explosive to temperatures above 150 degrees Kelvin for period of more than 100 millichrons."""
	.GSTR STR?323,"Carbon dioxide! Don't use it myself. The only form I've ever seen it in is dry ice."
	.GSTR STR?324,"open the bottle"
	.GSTR STR?325,"This living bubble has been set up as an artist's loft. Most of the space is taken up by a large scrap sculpture floating in the center of the bubble. It is, of course, pretty impossible to tell how close the sculpture is to completion. The way out is to the east."
	.GSTR STR?326,"The most recognizable item in the sculpture is a twenty-prong fromitz board."
	.GSTR STR?327,"From your experience with tawdry, space village bars, they are crowded every millichron of the day and night. So it's quite unusual that this saloon is totally deserted. Despite the current solitude, you can almost hear the tinny music, the loud voices, the fistfights. Openings lead west and northwest, and to the east is a partially disguised exit."
	.GSTR STR?328,"This is a tiny room, smelling strongly of various synthesized opium variants. There's a sign on the wall a door to the south."
	.GSTR STR?329,"You've always wondered what a back-room zero-gee space village bordello was like. Well, now you know. Next to the nearest bed is a locker. The exit leads down."
	.GSTR STR?330,"Your lungs rupture, not to mention all sorts of even nastier stuff that you're lucky if you can't imagine."
	.GSTR STR?331,"This filthy north-south tube is quite a change from the gleaming, well-scrubbed metal of the space station."
	.GSTR STR?332,"This large spacetube is the main thoroughfare of a space village which has sprung up here on the outskirts of the space station, which lies to the north. Rather than the bustling thoroughfare you might expect, however, there isn't a soul in sight. Openings lead up, northeast, south and west. To the southeast, the ""street"" narrows and ramps downward."
	.GSTR STR?333," fire nectar - thick and warming"
	.GSTR STR?334,"This permanently-docked one-man ship serves as the office for Hizzoner the Mayor, the unofficial leader of the village. Main Street is below."
	.GSTR STR?335,"You spot a copy of a book entitled ""Deciphering Alien Speech."""
	.GSTR STR?336,"""(bitter/salty/bitter)  softness/weakness
(sweet/very-sour)       Hunji (noun form)
(bland/salty/sour)      Zeenak (adj form)
(bland/bitter)          air/atmosphere
(very-salty)            however
(sweet/very-sweet)      legal destruction (sabotage?)
(very-sweet/bland/sour) I have shined light upon
(sour/bland/sour/sweet) turn back
(bland)                 (definite article?)
(slightly-sour)         solitary
(very-sweet/very-salty) element/substance
(sweet/slightly-bitter) brethren (adj form)
(sour/bland/bland/sour) died/failed
(bland/sour/very-sour)  is souring/turning bad
(spicy-hot/bland/bland) (a number) (78? 7/8?)
(bitter/sour/very-sour) weapon (poss form)
(very-sweet)            (emphasis mark?)
(very-salty/salty/sour) bad/evil/deadly radiation (plur form)"""
	.GSTR STR?337,"The Stellar Patrol has opened a recruitment office off Main Street, thus giving tacit approval to this technically nonregulation space village. Posters showing a rose-colored view of Patrol life are plastered all over the walls. A door leads east."
	.GSTR STR?338,"This is a branch office of the First Galactic Bank of Nebulon. There are doors to the north, west and southwest."
	.GSTR STR?339,"This small space bubble, with openings to the east and south, is decorated with posters of exotic locales, but it's hard to imagine that anyone in this rundown spacetown would be able to afford an interstellar pleasure jaunt."
	.GSTR STR?340,"Since there's no one here to milk you for some worthless life insurance or spaceship insurance, you might as well use the exits to the north or northeast."
	.GSTR STR?341,"There's no doubt that ""alley"" is the best word to describe this winding, garbage-strewn connector. Dark passages branch off in almost every direction, and the alley slopes upward to the northwest."
	.GSTR STR?342,"This is the home of some kook, a proselytizer of the fringe religion which believes that humankind has angered God by venturing out into space, and the universe will end sometime next week. Next week never seems to come, but there are enough kooks in the galaxy to keep the belief going. You can exit to the south."
	.GSTR STR?343,", taking you along for the ride.

Lost in Space
   You spend several chrons tumbling into the starry depths, the station dwindling to a dot of light behind you. Eventually, your air runs out."
	.GSTR STR?344,"As you swivel the headlamp around, you discover a tiny cylinder with an even tinier label."
	.GSTR STR?345,"""FREZONE (tm) Liquid Gorzium Explosive. For use only by licensed demolitionist. Instruction sheet available from vendor; read thoroughly before use!"""
	.GSTR STR?346,"The three balls hanging by the (northeastern) entrance to this space hut indicate that a villager down on his or her luck could come here to hock some valuable possession."
	.GSTR STR?347,"Some destitute spacer was so hard up that he or she actually pawned a spray can. It's sitting here in the shop, and has some lettering on it."
	.GSTR STR?348,"Some seedy loan shark has moored his dilapidated vessel here, on the south side of the alley."
	.GSTR STR?349,"""ONE GALAKMID
Third Galactic Union"""
	.GSTR STR?350,"This physician's bubble is owned by the village quack, known to his friends as ""Doc"" Schuster, but known to the vast majority of the villagers as Schuster the Shyster. There's a small hole in the wall, probably the opening for a disposal chute. The Doc is out, and in this case, out is northwest."
	.GSTR STR?351,"There is a large pile of intoxicated ostrich here."
	.GSTR STR?352,"[This is pretty gross, but you asked for it!] As the drill penetrates the unconscious ostrich, geysers of blood spout out, inundating you and the drill, causing a short circuit and electrocuting you. You collapse into a fried heap among a spreading puddle of blood."
	.GSTR STR?353,"""Doc -- that ostrich nip you've been waiting for finally came in. Drop by and pick it up. If I'm not in, you'll find it in my ceiling panel."""
	.GSTR STR?354,"In the corner of the office is a rather plain-looking machine with a keypad. It looks a bit jerry-rigged."
	.GSTR STR?355,"opening"
	.GSTR STR?356,"A scrambled card cannot be altered"
	.GSTR STR?357,"Ensign, Sixth Class or lower"
	.GSTR STR?358,"Ensign, Fifth through Second Class"
	.GSTR STR?359,"Ensign First Class"
	.GSTR STR?360,"Midshipman"
	.GSTR STR?361,"Lieutenant Second Class"
	.GSTR STR?362,"Lieutentant Commander"
	.GSTR STR?363,"Commander or Captain"
	.GSTR STR?364,"Admiral"
	.GSTR STR?365,"Fleet Admiral"
	.GSTR STR?366,"This outdated drydock is now a messy junk yard. A huge pile of floating junk fills the center of the bubble. Passages lead upwards and west."
	.GSTR STR?367,"Of all the items floating in the scrap heap, the pair of magnetic spaceboots looks to be in the best shape."

	.ENDI
