

; STRINGS ARE DEFINED HERE

STRBEG::

	.GSTR STR?1,"Not Here"
	.GSTR STR?2,"Actor"
	.GSTR STR?3,"Preaction"
	.GSTR STR?4,"PRSI"
	.GSTR STR?5,"PRSO"
	.GSTR STR?6,"OOPS"
	.GSTR STR?7,"AGAIN"
	.GSTR STR?8,"A powerful arc of raw energy bridges the gap between two of the monster's welding extensions. Unfortunately, you were pretty much right between the same two extensions at that moment."
	.GSTR STR?9,"."
	.GSTR STR?10,"   The log reader explodes!"
	.GSTR STR?11,"begins"
	.GSTR STR?12,"ends"
	.GSTR STR?13,"leave the game"
	.GSTR STR?14,"restart"
	.GSTR STR?15,"Biting"
	.GSTR STR?16,"climb into"
	.GSTR STR?17,"climb onto"
	.GSTR STR?18,"close"
	.GSTR STR?19,"disconnect the timer"
	.GSTR STR?20,"disconnect the explosive"
	.GSTR STR?21,"crumple"
	.GSTR STR?22,"dress"
	.GSTR STR?23,"open"
	.GSTR STR?24,"get onto"
	.GSTR STR?25,"get into"
	.GSTR STR?26,"look"
	.GSTR STR?27,"Kicking"
	.GSTR STR?28,"Knocking on"
	.GSTR STR?29,"jump"
	.GSTR STR?30,"You plummet down the shaft..."
	.GSTR STR?31,"sound"
	.GSTR STR?32,"look inside"
	.GSTR STR?33,"look through"
	.GSTR STR?34,"indecis"
	.GSTR STR?35,"Pulling"
	.GSTR STR?36,"move"
	.GSTR STR?37,"Trying to destroy"
	.GSTR STR?38,"negat"
	.GSTR STR?39,"ff"
	.GSTR STR?40,"n"
	.GSTR STR?41,"pick"
	.GSTR STR?42,"Pushing"
	.GSTR STR?43,"Playing in this way with"
	.GSTR STR?44,"read"
	.GSTR STR?45,"roll"
	.GSTR STR?46,"search"
	.GSTR STR?47,"Turning"
	.GSTR STR?48,"Shaking"
	.GSTR STR?49,"smell"
	.GSTR STR?50,"spray"
	.GSTR STR?51,"move that much"
	.GSTR STR?52,"taste"
	.GSTR STR?53,"Touching"
	.GSTR STR?54,"Keyboard is active only following authorization"
	.GSTR STR?55,"You have already made your selection"
	.GSTR STR?56,"That bin is unoccupied"
	.GSTR STR?57,"Error"
	.GSTR STR?58,"Fuel level at zero"
	.GSTR STR?59,"Course set. Launch in approximately 30 millichrons"
	.GSTR STR?60,"Safety precautions forbid the acceptance of course settings unless both the pilot and copilot seats are occupied"
	.GSTR STR?61,"Select a level between 1 and 9"
	.GSTR STR?62,"The instant you press the button, the elevator begins plunging down the shaft in a power dive! You punch frantically at the keypad..."
	.GSTR STR?63,"You are already at that level"
	.GSTR STR?64,"You have not deposited a coin"
	.GSTR STR?65,"This dispenser offers only 9 selections"
	.GSTR STR?66,"Sorry, that item is sold out. Inform your PX Officer for restocking"
	.GSTR STR?67,"walk"
	.GSTR STR?68,"wear"
	.GSTR STR?69,"posit"
	.GSTR STR?70,"remove"
	.GSTR STR?71," is as worthwhile as cleaning a grotch cage."
	.GSTR STR?72," accomplishes nothing."
	.GSTR STR?73," has no desirable effect."
	.GSTR STR?74,"Fat chance."
	.GSTR STR?75,"A valiant attempt."
	.GSTR STR?76,"You can't be serious."
	.GSTR STR?77,"Not bloody likely."
	.GSTR STR?78,"What a concept."
	.GSTR STR?79,"Nice try."
	.GSTR STR?80,"You are behaving like a demented Denebian slime devil."
	.GSTR STR?81,"Dream on."
	.GSTR STR?82,"You're wacko."
	.GSTR STR?83,"You have lost your mind."
	.GSTR STR?84,"A waste of time."
	.GSTR STR?85,"A worthless action -- and much too complex for a crufty program like this one to handle."
	.GSTR STR?86,"Useless. Unhelpful."
	.GSTR STR?87,"There's another turn down the drain."
	.GSTR STR?88,"Why bother?"
	.GSTR STR?89,"with"
	.GSTR STR?90,"Done. You might remain alive long enough to type EXAMINE MY STUMP. Oops, I guess not."
	.GSTR STR?91,"If you insist."
	.GSTR STR?92,"Wow! A hole where your torso used to be!"
	.GSTR STR?93,"I was going to ask you the same question!"
	.GSTR STR?94,"Floyd loves games! Let's play!"
	.GSTR STR?95,"Safety precautions forbid the activation of the vehicle unless both the pilot and copilot seats are occupied"
	.GSTR STR?96,"Spacecraft activated. Type in the course heading"
	.GSTR STR?97,"Authorization approved. Type the bin number of the desired robot"
	.GSTR STR?98,"This form has not been validated by a commanding officer"
	.GSTR STR?99,"Improper form for this location"
	.GSTR STR?100,"slot"
	.GSTR STR?101,"The quiet, dusty corridors stir disturbing memories. You're back on Resida, the deserted, plague-stricken world where you met Floyd. A hot flush creeps over you, indicating that the virulent disease that conquered this planet is beginnning its insidious work on you"
	.GSTR STR?102,"You are strolling across Deck Four of the Duffy, when suddenly you remember that you were supposed to have Handwriting Legibility Evaluation Forms -- all nine parts, for every member of the crew -- on Captain Fussbottom's desk by 7800. It's 7790, and those forms are stored on the other side of the ship. You try to run, but the floor is covered with glue. You can hear the Captain calling your name, louder and louder, as you struggle to move your legs"
	.GSTR STR?103,"You gulp down the last of your Ramosian Fire Nectar and ask the andro-waiter for another pitcher. This pub makes the finest Nectar on all of Ramos Two, and you and your shipmates are having a pretty rowdy time. Through the windows of the pub you can see a mighty, ancient castle, shining in the light of the three Ramosian moons. The Fire Nectar spreads through your blood and you begin to feel drowsy"
	.GSTR STR?104,"You wake up in a huge stadium, watching an important ceremony. It's a Stellar Patrol promotion ceremony on Tremain! Suddenly your own name echoes over the P.A. system -- and down below you see YOURSELF walking up the steps to the stage! The presiding admiral describes your heroism on Resida, mentioning that you were awarded the key to the planet, and then asks the ceremonial question, ""Do you accept promotion to Lieutenant First Class?"" You try to yell ""No!"" from the stands, but the words are lost in the vastness of the stadium"
	.GSTR STR?105,"You find yourself in a spacepod outside the docking bays of a large space station. All the doors are closed. You snap on the radio, and discover that Floyd is in charge within the station. ""Open the pod bay doors, Floyd,"" you tell him but he replies, ""I'm sorry, I can't do that,"" and begins laughing and your air is beginning to run out"
	.GSTR STR?106,"At last, the Duffy is approaching station Delta Upsilon Upsilon Phi -- your first rec leave in almost six months. It's even worth the six solid days of paperwork necessary for a standard half-day leave. Stationfall is millichrons away, but suddenly you realize that you're all alone on the Duffy! Frantic, you dash to the deserted bridge, but it's too late to stop the out-of-control Duffy from ramming the massive space station! The hull of the station rushes toward you"
	.GSTR STR?107,"You dream of being buried alive in an ancient Egyptian pyramid, inside the sarcophagus with some long-dead pharaoh. Phew, does he stink! You gasp and gag as the air in the coffin runs low.
   This dream, incidentally, is not a particularly unusual one among people who go to sleep inside space suits with limited oxygen supplies."
	.GSTR STR?108,"A movement awakens you in the middle of the night! Through unfocused eyes you see a large machine rolling menacingly closer! A bright light leaps from it, straight toward..."
	.GSTR STR?109,"Snore...snore...KABOOM!"
	.GSTR STR?110,"You collapse from extreme thirst and hunger."
	.GSTR STR?111,"It's too dark to see a thing."
	.GSTR STR?112,"You're not holding"
	.GSTR STR?113,"There's nothing "
	.GSTR STR?114,"You can see"
	.GSTR STR?115,"It seems that"
	.GSTR STR?116,"You can't "
	.GSTR STR?117,"You'll have to "
	.GSTR STR?118,"Look around you.
"
	.GSTR STR?119,"You're holding it!
"
	.GSTR STR?120,"[There seems to be a noun missing in that sentence.]
"
	.GSTR STR?121,"You see only blackness.
"
	.GSTR STR?122,"You already did that. Senility strikes again!
"
	.GSTR STR?123,".
"
	.GSTR STR?124,"...

"
	.GSTR STR?125,"Nothing happens.
"
	.GSTR STR?126,"Failed.
"
	.GSTR STR?127,"Okay.
"
	.GSTR STR?128,"Huh?
"
	.GSTR STR?129,"You can't go that way.
"
	.GSTR STR?130,"It already is!
"
	.GSTR STR?131,"""Floyd does not one of those have!""
"
	.GSTR STR?132,"Like most fromitz boards, it is a twisted maze of silicon circuits. It is square, approximately seventeen centimeters on each side.
"
	.GSTR STR?133,"You're neither hungry nor thirsty.
"
	.GSTR STR?134,"Floyd is leaning against the wall, his head lolling to the side. Apparently, someone has heartlessly turned him off."
	.GSTR STR?135,"The only part of the complex robot authorization equipment that is visible to you is a slot (for inserting your form) and a keypad (for typing your selection)."
	.GSTR STR?136,"Request for Stellar Patrol Issue Regulation Black Form Binders Request Form Forms"
	.GSTR STR?137,"The thick side wall of the tank has been blasted open"
	.GSTR STR?138,"Next time, say what number to set it to.
"
	.GSTR STR?139,", hopping mad. ""Why you turn Floyd off?"" he asks accusingly."
	.GSTR STR?140,"Spanning the entire garden is a transparent dome, providing a breathtaking view of the heavens in all their splendor."
	.GSTR STR?141," strike the machine's power source, inducing an overload implosion in said power source."
	.GSTR STR?142,"""The Galaxy's Best Zero-Gee Restaurant"""
	.GSTR STR?143,"The eternal flame has been extinguished!"
	.GSTR STR?144,"Lieutenant First Class"
	.GSTR STR?145,"Through the large, dirty window, you can see Dan's used spaceship lot. The spaceships floating in Dan's lot all have their prices whitewashed on their viewports, along with phrases like ""A steal!"" and ""Just reduced!"""
	.GSTR STR?146,"You are already in that mode.
"
	.GSTR STR?147,"That might get you into serious trouble as a violation of the Comprehensive Forms Destruction and Mutilation Act of 11309 GY.
"
	.GSTR STR?148,"ou hear the welder move off in another direction.
"
	.GSTR STR?149,", of course, no longer attached to the detonator.)"
	.GSTR STR?150,"The form is swallowed up, followed by a long pause for triple-redundancy processing. "
	.GSTR STR?151,"The form is rejected. "
	.GSTR STR?152,"suddenly sublimes into a puff of FREZONE (tm) gas."
	.GSTR STR?153,"For those unfamiliar with PLANETFALL, "
	.GSTR STR?154,"
   You have entered a cluttered space bubble "
	.GSTR STR?155," in the center... Oops. At second glance, you realize that the "
	.GSTR STR?156," between the arms of the frozen exercise machine, smoke pouring from its engine vents like steam from the nostrils of an angry bull."
	.GSTR STR?157,"You detach the detonator from "
	.GSTR STR?158,"   The ostrich gives a pathetic squawk of terror "
	.GSTR STR?159,"ou can just make out a letter ""M.""
"
	.GSTR STR?160," and lands on the floor."
	.GSTR STR?161,", and a ladder leads both upward and downward."
	.GSTR STR?162,"That's too long to wait.
"
	.GSTR STR?163,". 2. A callous disregard for scientific accuracy on the part of the author"
	.GSTR STR?164,"[Please refer to them as FIRST BIN, SECOND BIN, and THIRD BIN.]
"
	.GSTR STR?165,"   ""Boy, that looks like fun!"" says Floyd, peering up at you. ""Can Floyd try it? Huh? Please?""
"
	.GSTR STR?166," is a tangle of tubes and space bubbles and derelict rockets."
	.GSTR STR?167,"It won't budge.
"
	.GSTR STR?168,"Floyd sniffs, ""Please leave Floyd alone for a while.""
"
	.GSTR STR?169,"You are in the heart of the administrative level of the ship, the largest level of the S.P.S. Duffy or any other Stellar Patrol ship for that matter. The corridor continues starboard and a room lies aft. Beyond the door to port lies the bulk of the Duffy. Next to the door is a slot."
	.GSTR STR?170,"You must insert a validated Assignment Completion Form in the slot"
	.GSTR STR?171,"""STELLAR PATROL
Paperwork Task Force
ID Number: 1451-352-716"""
	.GSTR STR?172,"This is the largest space in the ship, three decks tall and with the floor area of seven Rigellian buzzball fields. The only exit is fore."
	.GSTR STR?173,"The room is filled to the ceiling with row upon row of pallets filled with boxes. Each box has some writing stamped on the side."
	.GSTR STR?174,"The deck twelve corridor ends here at the entrance to the cargo bay, to starboard. A smaller entrance leads fore."
	.GSTR STR?175,"He's an amusing and friendly little fellow."
	.GSTR STR?176,"That's me!"
	.GSTR STR?177,"Floyd, he"
	.GSTR STR?178,"rubs his head affectionately against your shoulder"
	.GSTR STR?179,"notices a mouse scurrying by and tries to hide behind you"
	.GSTR STR?180,"reminisces about the excitement of your adventure on Resida"
	.GSTR STR?181,"hums the theme song from a popular Saturday morning hyperwave cartoon"
	.GSTR STR?182,"plays a quick game of paddleball, almost breaking his record of four hits"
	.GSTR STR?183,"paces impatiently"
	.GSTR STR?184,"absent-mindedly recites the first six hundred digits of pi"
	.GSTR STR?185,"recalls the time he bruised his knee"
	.GSTR STR?186,"tells you how much it hurts to repair dents"
	.GSTR STR?187,"cranes his neck to see what you are doing"
	.GSTR STR?188,"examines himself for signs of rust"
	.GSTR STR?189,"absent-mindedly oils one of his joints"
	.GSTR STR?190,"wanders restlessly around the room"
	.GSTR STR?191,"sneaks up clumsily behind you and shouts ""Boo!"" in your ear"
	.GSTR STR?192,"frets about the possibility of his batteries failing"
	.GSTR STR?193,"whistles tunelessly"
	.GSTR STR?194,"boasts about the time he helped someone find a lost paper clip"
	.GSTR STR?195,"yawns and looks bored"
	.GSTR STR?196,"complains about a recent assignment in the forms filing department"
	.GSTR STR?197,"produces a crayon from one of his compartments and scrawls his name on the wall"
	.GSTR STR?198,"stomps on your foot, for no apparent reason"
	.GSTR STR?199,"accidentally bumps into you, and reacts by cursing your ancestors"
	.GSTR STR?200,"produces a loud burp and fails to apologize"
	.GSTR STR?201,"mumbles about a mysterious future in which humans will have to take orders from robots"
	.GSTR STR?202,"tells an off-color joke about the bizarre mating habits of flesh and blood creatures"
	.GSTR STR?203,"Floyd tells Plato about a neat shortcut for calculating seventh order differentials"
	.GSTR STR?204,"Plato tells Floyd one of the ancient legends about the early days of the settlement of the galaxy"
	.GSTR STR?205,"Floyd confides to Plato that his life's dream is to get locked up overnight in a toy factory"
	.GSTR STR?206,"Floyd and Plato discuss their favorite battery recharging techniques"
	.GSTR STR?207,"Plato helps polish a hard-to-reach spot on Floyd's back"
	.GSTR STR?208,"""You like Floyd, don't you, Plato?"" asks Floyd. ""Yes,"" replies the taller robot, ""you're the only robot I've ever met who doesn't call me a nerd."" Floyd smiles"
	.GSTR STR?209,"In a very sad voice, Floyd talks of his friend Lazarus, a medical robot on Resida who was tragically disassembled. Plato responds, ""Now, Floyd, don't fill your head with the sad memories of Lazarus' death. Think instead about the joy-filled times when you and your friend were together."" Floyd seems awed by such wisdom"
	.GSTR STR?210,"Floyd gives Plato a friendly hug"
	.GSTR STR?211,"Floyd stubs his toe and begins to whimper. ""There, there,"" says Plato, ""such a reaction will not reduce the level of pain."" He gives Floyd a little tickle, and Floyd begins giggling and forgets the injury"
	.GSTR STR?212,"Bin number two holds a spindly little robot, a specialized model designed for bursting and decollating multi-part forms. A tiny nameplate on her perforating extension reads ""Helen."""
	.GSTR STR?213,"In the first bin is a bulky robot, obviously intended for heavy lifting. A brass plate on one of his pneumatic arm lifts says ""Rex."""
	.GSTR STR?214,"   Rex trundles after you. Unfortunately, Rex is not too bright on his best days, and today is not one of them. He forgets to stop when you do; sixteen tons of Rex turn you into a human pancake."
	.GSTR STR?215,"open the hatch"
	.GSTR STR?216,"If you're in spacelane 630-461, keep it down to 26000 kilometers per millichron. There's a stakeout there."
	.GSTR STR?217,"Anyone seen any smokeys in the Nebulon sector?"
	.GSTR STR?218,"I'm looking for a traffic report on spacelane 317-455."
	.GSTR STR?219,"At the conclusion of this recording, your emergency message will be sent. In the meantime, stay calm. Nothing can go wrong <skip> go wrong <skip> go wrong <skip> go wrong.."
	.GSTR STR?220," filling the bay with hot ion gasses. Since you slept through most lectures at boot camp, you may not recall that hot ion gasses are pretty deadly."
	.GSTR STR?221,". Once in space, the truck's air gushes out through the open hatch."
	.GSTR STR?222,", leaving an impressive cloud of ion dust. However, you're in no condition to admire it, since you are now smeared all over the rear wall of the truck."
	.GSTR STR?223,"Fuel level at three-quarters"
	.GSTR STR?224,"Fuel level at one-quarter"
	.GSTR STR?225,"Docking bay one is occupied. Defaulting to bay two"
	.GSTR STR?226,"Arrival at terminus of inputted course. Fuel level now effectively at zero. Oxygen supply for one person: approximately two chrons"
	.GSTR STR?227,"   As the oxygen runs low, Floyd becomes quite chipper. Never before has he been in such a rust-inhibiting atmosphere. You, on the other hand, are dead."
	.GSTR STR?228," blueberry walnut soup"
	.GSTR STR?229,"soup"
	.GSTR STR?230," Ramosian tree-mold custard"
	.GSTR STR?231," apricot yogurt"
	.GSTR STR?232,"This is a fairly large space where much of the maintenance work for the station takes place. Some repair work for visiting ships is also done here. The room is filled with all sorts of repair and fabrication machinery. A door leads south, and there's an opening to the north."
	.GSTR STR?233,"I'm really not at all mechanically inclined. My sincerest apologies."
	.GSTR STR?234,"It's a kind of a thingamabob for putting in a, you know, a whosiwhatsis."
	.GSTR STR?235,"This is one of the storage areas. Exits lie to the east and south."
	.GSTR STR?236,"twenty tiny sockets"
	.GSTR STR?237,"The central corridor continues around to the southeast and southwest, but another corridor joins from the north. There's a door to the east and a doorway to the northeast."
	.GSTR STR?238,"The corridor widens here as it approaches the skin of the space station at the point where a Scientific Sub-Module would connect. Sure enough, the connecting tube of a Sub-Module begins just to the north! An auto-door lies to the west. Opposite it, a doorway leads east. A junction is visible to the south."
	.GSTR STR?239,"This is the shop for station personnel, selling everything from postcards to chewing gum at inflated prices. Exits lead west and southwest."
	.GSTR STR?240,"In the corner of the PX is a Stellar Patrol dispensing machine, consisting of a screen (displaying the dispenser's ""exciting"" offerings), a slot (for coin insertion), a keypad (for typing your selection), and a hole (where the dispensed item hopefully -- but rarely -- arrives)."
	.GSTR STR?241,"coin slot"
	.GSTR STR?242," In case you were napping during Demolitions Training, this means that you're now a fine layer of ash all over the walls of the PX."
	.GSTR STR?243,"It's a kind of a thingamabob for connecting a, you know, a whosiwhatsis."
	.GSTR STR?244,"Surrounding the beds of this infirmary is the finest diagnostic equipment that unlimited Stellar Patrol budgets can buy. To the east, an ID reader indicates a security door. You can leave to the west or southeast."
	.GSTR STR?245,"This is a modest prison, with three cells. The only exit is west."
	.GSTR STR?246,"lock"
	.GSTR STR?247,"The corridor continues around to the northwest and southwest, and an adjoining one heads east."
	.GSTR STR?248,"This central corridor turns northeast and northwest of here. A second corridor begins here and leads south. There are doorways to the southwest, southeast, and east."
	.GSTR STR?249," The shock seems to have been a bit too much for your heart."
	.GSTR STR?250,"This is the room where octuplet copies of forms are stored. Since it's only a hundred square meters, this room cannot hold more than a few days' worth of storage before being dumped to nanofilm. Mercifully, there is an exit to the northeast."
	.GSTR STR?251,"reader"
	.GSTR STR?252,"These are by far the nicest living quarters on the station, with separate sleeping, changing, and working cubicles, and a private SanFac. The only exit is west."
	.GSTR STR?253,"Sitting on the Commander's desk is an ordinary-looking log tape. There's a notation printed on it."
	.GSTR STR?254,"""Commander's Log -- 11349.12.2 through 11349.12.4"""
	.GSTR STR?255,"A sturdy safe is welded to the deck next to the desk."
	.GSTR STR?256,"The safe has been blown open! The area around the safe is blackened, and a burnt odor hangs in the air."
	.GSTR STR?257,"hole"
	.GSTR STR?258,"This is the Station Commander's conference room. Doors point north and west."
	.GSTR STR?259,"This is a secondary weapons storage deck, but the only weapon deck on a station with no Military Sub-Module. Exit: south."
	.GSTR STR?260,"This is a wide but not very tall docking bay. The station entrance lies to the east."
	.GSTR STR?261,"""Spacetruck Refueling Instructions"""
	.GSTR STR?262,"This cramped dormitory, composed of approximately twenty private cubicles, curves around the northern half of this level, with exits to the southeast and southwest."
	.GSTR STR?263,"You enter one of the cubicles but find nothing of interest."
	.GSTR STR?264,"This warren of tiny cubicles fills the southern half of this level, curving toward exits in the northeast and northwest corners."
	.GSTR STR?265,"This is a crowded but otherwise typical sanitary facility, with rows of showers, toilet stalls, and sinks. There are exits both north and south."
	.GSTR STR?266,"A multiple-function exercise machine sits imposingly on one side of the gym. There is a sign above it."
	.GSTR STR?267," hums encouraging platitudes as it exercises you to death."
	.GSTR STR?268,"In the corner, next to the dryer, is a large empty spot where the washer should be."
	.GSTR STR?269,"lurches forward and slams shut on your arm. Before you pass out from the pain, you hear a rumbling sound from the presser, but you can't decide whether it sounds more like a chuckle or a burp."
	.GSTR STR?270,"""Chapel Maintenance Procedures"""
	.GSTR STR?271,"This sixty-seat auditorium is used for lectures, certain large briefings, an occasional live entertainment, and a rare live broadcast over deep-space channels. A projection booth dominates the rear of the room. The theatre's only exit is to the north."
	.GSTR STR?272,"coffee"
	.GSTR STR?273,"Aaarghhh! The coffee is poisoned! It's eating away at your insides!!"
	.GSTR STR?274,"This is the primary storage room of the station, with large stockpiles of important items. For example, basic organic materials are needed to supplement the food supply due to the tiny inefficiencies of the recycling process. This is nearly the top level of the Command Module, and the ceiling curves in sharply over the supply room, which curves around to doors at the northwestern and southwestern ends."
	.GSTR STR?275,"detonator"
	.GSTR STR?276,"This is a medium-sized conference room with doors to the south and west."
	.GSTR STR?277,"This is a fairly large conference room with north and south exits."
	.GSTR STR?278,"This station's library has some printed material, such as recently transmitted magazines, but primarily it is a location for reading nanofilm spools, using the spool reader here, and for accessing the main computer's data banks via a computer terminal. Strangely, the computer terminal has been removed. There's a door to the north and an exit to the west."
	.GSTR STR?279,"Magazines are not to be removed from the library"
	.GSTR STR?280,"You stroll down one of the pebbled paths. It circles the garden, passing more exotic plants, and returns to the area near the elevator."
	.GSTR STR?281,"""Shrubbery Maintenance Supplies"""
	.GSTR STR?282,"open the grating"
	.GSTR STR?283,"These cubicles are for use by any visitors or station personnel beyond the normal complement. The entire barracks seem to be unused as well as deserted. The exit lies to the south, and the barracks curve around to the east."
	.GSTR STR?284,"This is the rather ordinary sanitary facility for the barracks to the north."
	.GSTR STR?285,"This is the station's largest docking bay. A huge door to the east leads into the station.
   Resting in the docking bay is a small ship of obviously alien origin. An open hatch seems to beckon you inward."
	.GSTR STR?286,"Must be a connect-the-dots! And a real easy one, too! None of those dumb numbers to confuse you! Where's my crayon?"
	.GSTR STR?287,"Hmmm. Some kind of alien writing, I presume. If I recall, the Mayor is an expert on that subject."
	.GSTR STR?288,"Lying under the dots is a skeleton, the brittle remains of a member of some unfamiliar alien race."
	.GSTR STR?289,"This is the station's smallest docking bay. You can enter the station to the east."
	.GSTR STR?290,"The corridor, which widens off to the west, ends here. Doors lie to the east, north, south, and southwest. The door to the north must be a security door, because there's an ID reader next to it."
	.GSTR STR?291,"This is a room where new robots are constructed, old robots are repaired, and unused robots are stored. There's a door to the east."
	.GSTR STR?292,"opening of the chamber"
	.GSTR STR?293,"There's a young-looking robot lying here, apparently having completed the final ""training"" phase of its construction. The wires for feeding it information have been removed, but it has not yet ""woken up."" A dim memory from your old robotics text drifts through your mind: ""The incubation period between the training and 'birth' of a robot is two to twenty days, depending on the complexity of the model."" This particular model has the name ""Oliver"" engraved on its chestplate."
	.GSTR STR?294,"A little ""sleeping"" robot named ""Oliver"" is lying here."
	.GSTR STR?295,"If we be here when Oliver wakes up, Floyd would like to teach Oliver to play paddleball. Paddleball helped Floyd forget how lonely and scared he was until he found friends...like you."
	.GSTR STR?296,"Ah, a new robot. Poor fellow; new robots are so mercilessly mistreated by the older robots. Such is our lot."
	.GSTR STR?297,"In an event staggering in its improbability, a huge meteor crashes through the hull of the space station as you take aim, and turns you into cosmic dust. Can't say you didn't deserve it, you baby-robot-killer you."
	.GSTR STR?298,"This is the place where a station's exports are prepared before transfer to the docking bays and subsequent shipment throughout the regional sector. Hanging above a large vacant section of the room is an eye-catching sign. The only exit is west."
	.GSTR STR?299,"This is a fairly comfortable two-person living quarters, significantly roomier than the barracks where most of the ship's personnel live. There's a door to the north, and an opening leads southeast."
	.GSTR STR?300,"This is a fairly comfortable two-person living quarters, significantly roomier than the barracks where most of the ship's personnel live. A door leads north and a doorway south."
	.GSTR STR?301,"This is a fairly comfortable two-person living quarters, significantly roomier than the barracks where most of the ship's personnel live. A doorway lies to the southwest, and there's an auto-door to the north."
	.GSTR STR?302,"A moderately luxurious SanFac, with a pair of bathtubs in addition to the regular fixtures. Exits lead north, northeast, and northwest."
	.GSTR STR?303,"A few rungs down, you discover that the ladder passage to Level Eight is sealed off -- apparently from below."
	.GSTR STR?304,"""Collater Repair Manual"""
	.GSTR STR?305,"Outdated forms and expired files are reduced to pulp by this machinery. In addition, raw pulp is constantly being ferried into the station from nearby forest worlds. The output from this plant feeds the station's printing plant, which lies to the southeast."
	.GSTR STR?306,"Someone has presumably been attempting to repair some of the machinery in this room, because they left a drill lying around."
	.GSTR STR?307,"drill"
	.GSTR STR?308,"remove the bit that's in the drill"
	.GSTR STR?309,"Oh, no! The elevator isn't at this floor! It's a long plunge..."
	.GSTR STR?310,"Magnetically-stored data has been damaged; see the Security Officer to have data restored"
	.GSTR STR?311,"This shiny cylindrical corridor is the connector between the Command Module, to the south, and the Scientific Sub-Module, to the north."
	.GSTR STR?312,"This laboratory, which fills most of the middle level of the Sub-Module, is for the study of applications of the various space-related research that takes place on the other levels. Gangways lead up and down, and a door leads north. A connecting tube opens to the south."
	.GSTR STR?313,"This is a small office associated with the lab to the south."
	.GSTR STR?314,"This is the notebook of a certain Professor Schmidt, who was studying a strange pyramid discovered aboard a derelict alien ship and brought here.
   Schmidt traced back the path of the alien ship; the path points out of the galaxy without nearing any star system. Further, extending the path leads straight to one of our smaller neighboring galaxies. Schmidt concludes that the ship and the pyramid are probably well over one billion years old!
   Next, Schmidt studied the wall markings in the alien ship. A series of identical dots, they defied every computerized model of linguistic decipherment! Then, in an inspiration, Schmidt studied the dots for nonvisual properties. His diary vaguely refers to a breakthrough, saying, ""I guess my pal, the mayor, will get to show off his linguistic training.""
   Finally, Schmidt began concentrating his studies on the pyramid itself. He was able to discover very little, blaming this primarily on the unexplained failures of several crucial pieces of lab machinery."
	.GSTR STR?315,"This laboratory conducts research into various space-related physical sciences. Gangways lead up and down, and there's a door to the north."
	.GSTR STR?316,"Various biological sciences, as they relate to the environment of space, are studied in this laboratory. There is a gangway leading up, another leading down, and a door leading north."
	.GSTR STR?317,"Lying on one of the desks is a scribbled note."
	.GSTR STR?318,"""Schmidt -- Why didn't I see it until now! Just think of this station as a cell and the pyramid as a mechanized bacterioph"" The note ends at that point; there seem to be some reddish-brown stains on it."
	.GSTR STR?319,"This cramped living area has cubicles for the dozen or so scientists and engineers working in this Sub-Module. The only exit is a gangway leading down."
	.GSTR STR?320,"I don't have a very specific function in the station's robotic organizational scheme, but I do keep the library organized."
	.GSTR STR?321,"Floyd's best friend! Oh, except you, of course!"
	.GSTR STR?322,"Some early poems by Ignatius Tomato. He's my current favorite."
	.GSTR STR?323,"burst into tears and dashes out of the room. A beam leaps from the gun..."
	.GSTR STR?324," the station's reactor turns into a good old-fashioned H-bomb."
	.GSTR STR?325,"You are at the top of an air shaft. Handholds lead downward, and a partially open air grate leads out of the shaft."
	.GSTR STR?326,"You are in a large, vertical air duct. Handholds lead up and down."
	.GSTR STR?327,"You have reached the bottom of the air vent. Ducts too small for you to enter lead off laterally. Handholds lead upward, and the entire floor of the duct is another large grating."
	.GSTR STR?328,"The sides ducts are too small to enter!"
	.GSTR STR?329,"This tiny control station allows access to the massive memory banks of the station's computer. Ever since the formation of the Third Galactic Union ended the great interstellar dark age, every Stellar Patrol spaceship, every Patrol space station, has been equipped with a computer bulging with the entire accumulated knowledge of mankind. Never again will humanity be permitted to slip back into the ignorance and savagery of the dark age.
   A ladder leads up to Level Eight, and there's a call button next to the elevator shaft to the north."
	.GSTR STR?330," reaches you, and performs various repetitions all over your body, proving that exercise isn't always good for you."
	.GSTR STR?331,"slips into gear and zooms forward, goring you on its fork."
	.GSTR STR?332,"There is gravity here at the bottom of the elevator shaft. The elevator's not in sight; the only exit is back to the computer room to the south."
	.GSTR STR?333,"There's no way to climb the shaft."
	.GSTR STR?334,"Floyd fires his stun ray nonchalantly in your direction, laughing, as though taunting you. You feel part of your leg go numb"
	.GSTR STR?335,"Smoke is trickling from the tails of the tiny rockets, as though the duplicate pyramids were preparing for activation and launch"
	.GSTR STR?336,"One of the blinking lights on the reactor goes from yellow to red"
	.GSTR STR?337,"the pyramid, Floyd"
	.GSTR STR?338,"This is an east-west tube, widening as it gets farther from the Command Module."
	.GSTR STR?339,"This is a wide, cheaply constructed space tube, narrowing to the west. There are openings off this ""street"" in virtually every direction, including one leading downward."
	.GSTR STR?340,"Well, there are openings in ALMOST every direction."
	.GSTR STR?341,"This is a tiny living bubble beneath Broadway. The inhabitant, who is nowhere in sight, seems to be in the profession of reading the future for superstitious spacers."
	.GSTR STR?342,"The Stellar Patrol has opened a recruitment office off Broadway, thus giving tacit approval to this technically nonregulation space village. Posters showing a rose-colored view of Patrol life are plastered all over the walls. A door leads south."
	.GSTR STR?343,"This moderately large store sells all kinds of games and other recreational materials. There is also an in-house rec area, featuring a group of simulation booths. The ""street"" lies to the southwest."
	.GSTR STR?344,"groof hunting on Septurion Seven"
	.GSTR STR?345,"a little-known incident during the signing of the Treaty of Gishen IV"
	.GSTR STR?346,"a torrid romance on the tropical planet of San Cupidor"
	.GSTR STR?347,"searching for treasure in a magical underground empire"
	.GSTR STR?348,"bullfighting, skydiving, and dental hygiene"
	.GSTR STR?349,"The huge galactic mining conglomerates often open field offices in these space villages, and this is one of those. Miners will haul some promising hunk of space rock into the vicinity, and then come here to sell the rights to it. You can leave to the west."
	.GSTR STR?350,"Some miner has left a headlamp here."
	.GSTR STR?351,"A piece of reflective foil is hanging on the wall where the mirror once was."
	.GSTR STR?352,"Trans-molecular platinum foil! I am told that it is the most perfectly reflective material known, and not just on the visual wavelengths!"
	.GSTR STR?353,"Floyd loves anything reflective! Give Floyd a mirror and he'll be happy for days!"
	.GSTR STR?354,"This is a small convenience store, the main source of food and living supplies for this village, as well as a supplement supply for personnel from the space station proper. The shelves are pretty bare, and there is no one in sight. Exits lead north, east, southeast and south."
	.GSTR STR?355,"A small, translucent plastic bag is sitting on one of the shelves."
	.GSTR STR?356,", delectable, moist boysenberry-flavored taffy"
	.GSTR STR?357,"This shop, with exits to the northeast and southeast, sells a variety of animals. Many a lonely spacer has discovered the joys a pet can bring, and this shop features animals of both terrestrial and alien origin. A large sign advertises this month's special."
	.GSTR STR?358,"You can see the faint outline of a panel in the ceiling."
	.GSTR STR?359,"This sprawling old cargo ship, its engines long ago cannibalized for spare parts, has been converted into a store for supplies and curios. There's an eye-catching sign on the wall. Passageways lead in many directions, and there's an opening in the floor."
	.GSTR STR?360,"""FREZONE (tm) Liquid Gorzium Explosive
Instructions for use:
1. Insert explosive in hole of appropriate diameter.
2. Attach detonator to explosive and timer.
3. Set timer.
4. Vamoose.
NOTE: Do not expose explosive to temperatures above 150 degrees Kelvin for periods of more than 100 millichrons."""
	.GSTR STR?361,"This living bubble has been set up as an artist's loft. Most of the space is taken up by a large scrap sculpture floating in the center of the bubble. It is, of course, pretty impossible to tell how close the sculpture is to completion. The way out is to the east."
	.GSTR STR?362,"The most recognizable item in the sculpture is a J-series hyperdiode."
	.GSTR STR?363,"From your experience with tawdry, space village bars, they are crowded every millichron of the day and night. So it's quite unusual that this saloon is totally deserted. Despite the current solitude, you can almost hear the tinny music, the loud voices, the fistfights. Openings lead west and northwest, and to the east is a partially disguised exit."
	.GSTR STR?364,"This is a tiny room, smelling strongly of various synthesized opium variants. There's a sign on the wall and a door to the south."
	.GSTR STR?365,"Your lungs rupture, not to mention all sorts of even nastier stuff that you're lucky if you can't imagine."
	.GSTR STR?366,"This filthy north-south tube is quite a change from the gleaming, well-scrubbed metal of the space station."
	.GSTR STR?367,"This large spacetube is the main thoroughfare of a space village which has sprung up here on the outskirts of the space station, which lies to the north. Rather than the bustling thoroughfare you might expect, however, there isn't a soul in sight. Openings lead up, northeast, south and west. To the southeast, the ""street"" narrows and ramps downward."
	.GSTR STR?368," fire nectar -- thick and warming"
	.GSTR STR?369,"nectar"
	.GSTR STR?370,"This permanently-docked one-man ship serves as the office for Hizzoner the Mayor, the unofficial leader of the village. Main Street is below."
	.GSTR STR?371,"You spot a copy of a book entitled ""Deciphering Alien Speech."""
	.GSTR STR?372,"""bttr/salty/bttr     softness/weakness
sweet/v.sour         Hunji (noun form)
blnd/salty/sour      Zeenak (adj form)
blnd/bttr            air/atmosphere
sour/blnd/blnd/sour  died/failed
sweet/v.sweet        legal destruction
                         (sabotage?)
v.salty              however
sour/blnd/sour/sweet turn back
blnd                 (def. article?)
v.sweet/blnd/sour    I have shined
                         light upon
slightly-sour        solitary
v.sweet/v.salty      element/substance
sweet/slightly-bttr  brethren (adj)
blnd/sour/v.sour     is souring
v.salty/salty/sour   bad/evil/deadly
                         radiations
spicy-hot/blnd/blnd  78 (?) 7/8 (?)
bttr/sour/v.sour     weapon (possesv.)
v.sweet              (emphasis mark?)"""
	.GSTR STR?373,"This is a branch office of the First Galactic Bank of Nebulon. There are doors to the north and northwest."
	.GSTR STR?374,"This small space bubble, with openings to the east and southeast, is decorated with posters of exotic locales, but it's hard to imagine that anyone in this rundown spacetown would be able to afford an interstellar pleasure jaunt."
	.GSTR STR?375,"There's no doubt that ""alley"" is the best word to describe this winding, garbage-strewn connector. Dark passages branch off in almost every direction, and the alley slopes upward to the northwest."
	.GSTR STR?376,"This is the home of some kook, a proselytizer of the fringe religion which believes that humankind has angered God by venturing out into space, and the universe will end sometime next week. Next week never seems to come, but there are enough kooks in the galaxy to keep the belief going. You can exit to the south."
	.GSTR STR?377,"

Lost in Space
   You spend several chrons tumbling into the starry depths, the station dwindling to a dot of light behind you. Eventually, your air runs out."
	.GSTR STR?378,"As you swivel the headlamp around, you discover a tiny cylinder with an even tinier label."
	.GSTR STR?379,"""FREZONE (tm) Liquid Gorzium Explosive. For use only by licensed demolitionist. Instruction sheet available from vendor; read thoroughly before use!"""
	.GSTR STR?380,"The three balls hanging by the (northeastern) entrance to this space hut indicate that a villager down on his or her luck could come here to hock some valuable possession."
	.GSTR STR?381,"Some destitute spacer was so hard up that he or she actually pawned a spray can. It's sitting here in the shop, and has some lettering on it."
	.GSTR STR?382,"This is a dilapidated vessel that some seedy loan shark has moored on the south side of the alley."
	.GSTR STR?383,"A fairly sturdy strong box is fastened to the floor. Or maybe the ceiling. One can never be sure without gravity."
	.GSTR STR?384,"""ONE GALAKMID
Third Galactic Union"""
	.GSTR STR?385,"This physician's bubble is owned by the village quack, known to his friends as ""Doc"" Schuster, but known to the vast majority of the villagers as Schuster the Shyster. There's a small hole in the wall, probably the opening for a disposal chute. The Doc is out, and in this case, out is northwest."
	.GSTR STR?386,"There is a large pile of intoxicated ostrich here."
	.GSTR STR?387,"""Doc -- that ostrich nip you've been waiting for finally came in. Drop by and pick it up. If I'm not in, you'll find it in my ceiling panel."""
	.GSTR STR?388,"In the corner of the office is a rather plain-looking machine with a keypad. It looks a bit jerry-built."
	.GSTR STR?389,"opening"
	.GSTR STR?390,"A scrambled card cannot be altered"
	.GSTR STR?391,"Ensign, lower classes"
	.GSTR STR?392,"Ensign First Class"
	.GSTR STR?393,"Upshipman"
	.GSTR STR?394,"Lieutenant Last Class"
	.GSTR STR?395,"Lieutenant Second Class"
	.GSTR STR?396,"Commander or Captain"
	.GSTR STR?397,"Admiral"
	.GSTR STR?398,"HyperAdmiral"
	.GSTR STR?399,"Grand Fleet HyperAdmiral"
	.GSTR STR?400,"This outdated drydock is now a messy junk yard. A huge pile of floating junk fills the center of the bubble. Passages lead upwards and west."
	.GSTR STR?401,"Of all the items floating in the scrap heap, the pair of magnetic spaceboots looks to be in the best shape."

	.ENDI
