

	.FUNCT	V-VERBOSE
	SET	'VERBOSITY,2
	PRINTI	"Maximum verbosity."
	CRLF	
	CRLF	
	CALL	V-LOOK
	RSTACK	


	.FUNCT	V-BRIEF
	SET	'VERBOSITY,1
	PRINTR	"Brief descriptions."


	.FUNCT	V-SUPER-BRIEF
	SET	'VERBOSITY,0
	PRINTR	"Superbrief descriptions."


	.FUNCT	V-SAVE
	SET	'P-CONT,FALSE-VALUE
	SET	'QUOTE-FLAG,FALSE-VALUE
	CALL	VISIBLE?,FLOYD
	ZERO?	STACK /?CND1
	FSET?	FLOYD,TOUCHBIT \?CND1
	FSET?	FLOYD,ACTIVEBIT \?CND1
	EQUAL?	HERE,FACTORY /?CND1
	PRINTI	"Floyd's eyes light up. ""Oh boy! Are we gonna try something dangerous now?"""
	CRLF	
	CRLF	
?CND1:	SAVE	 \?ELS10
	PRINT	OK
	RTRUE	
?ELS10:	PRINT	FAILED
	RTRUE	


	.FUNCT	V-RESTORE
	CALL	VISIBLE?,FLOYD
	ZERO?	STACK /?CND1
	FSET?	FLOYD,TOUCHBIT \?CND1
	FSET?	FLOYD,ACTIVEBIT \?CND1
	EQUAL?	HERE,FACTORY /?CND1
	PRINTI	"Floyd looks disappointed but understanding. ""That part of the story was more fun,"" he sighs."
	CRLF	
	CRLF	
?CND1:	RESTORE	 \?ELS10
	PRINT	OK
	RTRUE	
?ELS10:	PRINT	FAILED
	RTRUE	


	.FUNCT	TELL-SCORE
	PRINTI	"Your score is "
	PRINTN	SCORE
	PRINTI	" (out of 80 points). It is Day "
	PRINTN	DAY
	PRINTI	" of your adventure. "
	CALL	V-TIME,TRUE-VALUE
	PRINTI	" Your score gives you the rank of "
	ZERO?	SCORE \?ELS3
	PRINTI	"Insignificant Nobody"
	JUMP	?CND1
?ELS3:	LESS?	SCORE,13 \?ELS5
	PRINTI	"Rising Young Insignificant Nobody"
	JUMP	?CND1
?ELS5:	LESS?	SCORE,25 \?ELS7
	PRINTI	"One-Day Flash on the Evening News"
	JUMP	?CND1
?ELS7:	LESS?	SCORE,36 \?ELS9
	PRINTI	"Footnote in History"
	JUMP	?CND1
?ELS9:	LESS?	SCORE,46 \?ELS11
	PRINTI	"International VIP"
	JUMP	?CND1
?ELS11:	LESS?	SCORE,55 \?ELS13
	PRINTI	"Interplanetary Star"
	JUMP	?CND1
?ELS13:	LESS?	SCORE,63 \?ELS15
	PRINTI	"Interstellar Superstar"
	JUMP	?CND1
?ELS15:	PRINTI	"Intergalactic Mega-Hero"
?CND1:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	V-SCRIPT
	CALL	VISIBLE?,FLOYD
	ZERO?	STACK /?CND1
	FSET?	FLOYD,TOUCHBIT \?CND1
	FSET?	FLOYD,ACTIVEBIT \?CND1
	EQUAL?	HERE,FACTORY /?CND1
	PRINTI	"   ""Uh oh,"" frets Floyd. ""If this is going to be permanent, Floyd will have to be careful not to use any of the bad words he learned aboard the Duffy!"""
	CRLF	
?CND1:	GET	0,8
	BOR	STACK,1
	PUT	0,8,STACK
	CALL	CORP-NOTICE,STR?8
	CALL	V-VERSION
	RSTACK	


	.FUNCT	V-UNSCRIPT
	CALL	VISIBLE?,FLOYD
	ZERO?	STACK /?CND1
	FSET?	FLOYD,TOUCHBIT \?CND1
	FSET?	FLOYD,ACTIVEBIT \?CND1
	EQUAL?	HERE,FACTORY /?CND1
	PRINTI	"   Floyd nods his approval. ""Good idea. Printer paper expensive. Best to save for important scenes. Not like this one."""
	CRLF	
?CND1:	CALL	CORP-NOTICE,STR?9
	CALL	V-VERSION
	GET	0,8
	BAND	STACK,-2
	PUT	0,8,STACK
	RTRUE	


	.FUNCT	CORP-NOTICE,STRING
	PRINTI	"Here "
	PRINT	STRING
	PRINTR	" a transcript of interaction with STATIONALL."


	.FUNCT	V-DIAGNOSE
	SET	'C-ELAPSED,18
	EQUAL?	HERE,FACTORY \?ELS5
	PRINTR	"We're talking adrenaline. Lots and lots of adrenalin."
?ELS5:	PRINTI	"You feel "
	GRTR?	PLATO-ATTACK-COUNTER,0 \?ELS10
	IN?	PLATO,HERE \?ELS10
	PRINTI	"numb. "
	CALL	STUNNED
	RTRUE	
?ELS10:	ZERO?	SLEEPY-LEVEL \?ELS14
	PRINTI	"well-rested"
	JUMP	?CND8
?ELS14:	EQUAL?	SLEEPY-LEVEL,1 \?ELS19
	PRINTI	"sort of"
	JUMP	?CND17
?ELS19:	EQUAL?	SLEEPY-LEVEL,2 \?ELS21
	PRINTI	"quite"
	JUMP	?CND17
?ELS21:	PRINTI	"phenomenally"
?CND17:	PRINTI	" tired"
?CND8:	ZERO?	SLEEPY-LEVEL \?ELS30
	GRTR?	HUNGER-LEVEL,0 /?THN27
?ELS30:	GRTR?	SLEEPY-LEVEL,0 \?ELS26
	ZERO?	HUNGER-LEVEL \?ELS26
?THN27:	PRINTI	", but"
	JUMP	?CND24
?ELS26:	PRINTI	", and"
?CND24:	PRINTI	" you are "
	ZERO?	HUNGER-LEVEL \?ELS37
	PRINTI	"well-fed"
	JUMP	?CND35
?ELS37:	EQUAL?	HUNGER-LEVEL,1 \?ELS42
	PRINTI	"fairly"
	JUMP	?CND40
?ELS42:	GRTR?	HUNGER-LEVEL,4 \?ELS44
	PRINTI	"awesomely"
	JUMP	?CND40
?ELS44:	PRINTI	"very"
?CND40:	PRINTI	" hungry and thirsty"
?CND35:	PRINTR	". In all other respects, you are in good health."


	.FUNCT	V-INVENTORY
	SUB	0,WORNBIT >D-BIT
	SET	'C-ELAPSED,18
	ADD	D-ALL?,D-PARA?
	CALL	DESCRIBE-CONTENTS,WINNER,FALSE-VALUE,STACK
	ZERO?	STACK \?CND1
	PRINTI	"You are empty-handed."
?CND1:	SET	'D-BIT,WORNBIT
	ADD	D-ALL?,D-PARA?
	CALL	DESCRIBE-CONTENTS,WINNER,FALSE-VALUE,STACK
	SET	'D-BIT,FALSE-VALUE
	CRLF	
	RTRUE	


	.FUNCT	V-QUIT
	CALL	TELL-SCORE
	CALL	VISIBLE?,FLOYD
	ZERO?	STACK /?CND1
	FSET?	FLOYD,TOUCHBIT \?CND1
	FSET?	FLOYD,ACTIVEBIT \?CND1
	EQUAL?	HERE,FACTORY /?CND1
	PRINTI	"   Floyd grins impishly. ""Giving up, huh?"""
	CRLF	
?CND1:	CALL	DO-YOU-WISH,STR?10
	CALL	YES?
	ZERO?	STACK /?ELS10
	QUIT	
	RTRUE	
?ELS10:	PRINT	OK
	RTRUE	


	.FUNCT	V-RESTART
	CALL	TELL-SCORE
	CALL	VISIBLE?,FLOYD
	ZERO?	STACK /?CND1
	FSET?	FLOYD,TOUCHBIT \?CND1
	FSET?	FLOYD,ACTIVEBIT \?CND1
	FSET?	ROBOT-POOL,TOUCHBIT \?CND1
	EQUAL?	HERE,ROBOT-POOL /?CND1
	PRINTI	"   Floyd rolls his eyes. ""We're gonna have to go through that stupid scene in the Robot Pool again?"""
	CRLF	
?CND1:	CALL	DO-YOU-WISH,STR?11
	CALL	YES?
	ZERO?	STACK /FALSE
	PRINTI	"Restarting."
	CRLF	
	RESTART	
	PRINT	FAILED
	RTRUE	


	.FUNCT	DO-YOU-WISH,STRING
	CRLF	
	PRINTI	"Do you wish to "
	PRINT	STRING
	PRINTI	"? (Y is affirmative): "
	RTRUE	


	.FUNCT	YES?
?FCN:	PRINTC	62
	READ	P-INBUF,P-LEXV
	GET	P-LEXV,1
	CALL	YES-WORD,STACK
	ZERO?	STACK \TRUE
	GET	P-LEXV,1
	CALL	NO-WORD,STACK
	ZERO?	STACK \FALSE
	GET	P-LEXV,1
	EQUAL?	STACK,W?N /FALSE
	PRINTI	"Please answer YES or NO. "
	JUMP	?FCN


	.FUNCT	FINISH,REPEATING=0,CNT=0
?PRG1:	CRLF	
	ZERO?	REPEATING \?CND3
	SET	'REPEATING,TRUE-VALUE
	CALL	TELL-SCORE
?CND3:	PRINTI	"   According to the Treaty of Gishen IV, which was amended after the Battle on Sorkin III in 11347 GY, you must be given the opportunity to restart the story, restore a saved position, or end this session of the game. In the interests of interstellar peace, type RESTART, RESTORE, or QUIT: >"
	PUTB	P-LEXV,0,10
	READ	P-INBUF,P-LEXV
	PUTB	P-LEXV,0,60
	INC	'CNT
	GET	P-LEXV,1
	EQUAL?	STACK,W?RESTAR \?ELS8
	RESTART	
	PRINT	FAILED
	JUMP	?PRG1
?ELS8:	GET	P-LEXV,1
	EQUAL?	STACK,W?RESTOR \?ELS10
	RESTORE	 /?ELS10
	PRINT	FAILED
	JUMP	?PRG1
?ELS10:	GET	P-LEXV,1
	EQUAL?	STACK,W?QUIT,W?Q /?THN15
	GRTR?	CNT,10 \?PRG1
?THN15:	QUIT	
	JUMP	?PRG1


	.FUNCT	V-SCORE
	PRINTI	"You're currently getting "
	ZERO?	VERBOSITY \?ELS3
	PRINTI	"super-brief"
	JUMP	?CND1
?ELS3:	EQUAL?	VERBOSITY,1 \?ELS5
	PRINTI	"brief"
	JUMP	?CND1
?ELS5:	PRINTI	"verbose"
?CND1:	PRINTI	" descriptions. "
	CALL	TELL-SCORE
	RSTACK	


	.FUNCT	V-VERSION,CNT=17,V
	GET	0,1
	BAND	STACK,2047 >V
	PRINTI	"STATIONFALL
Infocom interactive fiction -- a science fiction story
Copyright (c) 1987 by Infocom, Inc. All rights reserved.
STATIONFALL is a trademark of Infocom, Inc.
Release "
	PRINTN	V
	PRINTI	" / Serial number "
?PRG1:	IGRTR?	'CNT,23 /?REP2
	GETB	0,CNT
	PRINTC	STACK
	JUMP	?PRG1
?REP2:	CRLF	
	CALL	VISIBLE?,FLOYD
	ZERO?	STACK /FALSE
	FSET?	FLOYD,TOUCHBIT \FALSE
	FSET?	FLOYD,ACTIVEBIT \FALSE
	EQUAL?	HERE,FACTORY /FALSE
	PRINTR	"   Floyd looks out at you, right through your computer screen. ""See that copyright notice?"" he asks in a defiant tone. ""If anyone tries pirating this disk, they'll have Floyd to answer to."""


	.FUNCT	V-$COMMAND
	DIRIN	1
	RTRUE	


	.FUNCT	V-$RANDOM
	EQUAL?	PRSO,INTNUM /?ELS5
	PRINTR	"Bug1"
?ELS5:	SUB	0,P-NUMBER
	RANDOM	STACK
	RTRUE	


	.FUNCT	V-$RECORD
	DIROUT	D-RECORD-ON
	RTRUE	


	.FUNCT	V-$UNRECORD
	DIROUT	D-RECORD-OFF
	RTRUE	


	.FUNCT	V-$VERIFY
	EQUAL?	PRSO,INTNUM \?ELS5
	EQUAL?	P-NUMBER,69 \?ELS5
	PRINTN	SERIAL
	CRLF	
	RTRUE	
?ELS5:	PRINTI	"Verifying."
	CRLF	
	VERIFY	 \?ELS14
	PRINT	OK
	RTRUE	
?ELS14:	PRINTR	"** Bad **"


	.FUNCT	V-$DEBUG
	PRINTC	79
	ZERO?	DEBUG /?ELS3
	SET	'DEBUG,FALSE-VALUE
	PRINTI	"ff"
	JUMP	?CND1
?ELS3:	SET	'DEBUG,TRUE-VALUE
	PRINTC	110
?CND1:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	V-$STATION
	FSET	FLOYD,TOUCHBIT
	FSET	SPACETRUCK-HATCH,OPENBIT
	FSET	IRIS-HATCH,OPENBIT
	SET	'ROBOT-PICKED,FLOYD
	SET	'SPACETRUCK-COUNTER,5
	REMOVE	CLASS-THREE-SPACECRAFT-ACTIVATION-FORM
	REMOVE	ROBOT-USE-AUTHORIZATION-FORM
	MOVE	FLOYD,SPACETRUCK
	CALL	QUEUE,I-WELDER,-1
	CALL	QUEUE,I-FLOYD,-1
	CALL	QUEUE,I-PLATO,750
	CALL	GOTO,SPACETRUCK
	RSTACK	


	.FUNCT	V-$KEY
	RANDOM	200
	ADD	STACK,20
	CALL	QUEUE,I-LIGHTS-OUT,STACK
	MOVE	KEY,PROTAGONIST
	MOVE	HEADLAMP,PROTAGONIST
	FSET	HEADLAMP,WORNBIT
	MOVE	JAMMER,PROTAGONIST
	MOVE	TWENTY-PRONG-FROMITZ-BOARD,PROTAGONIST
	SET	'JAMMER-SETTING,710
	FSET	JAMMER,ACTIVEBIT
	MOVE	ZAPGUN,PROTAGONIST
	CALL	GOTO,COMMANDERS-QUARTERS
	RSTACK	


	.FUNCT	V-ALARM
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	PERFORM-PRSA,ME
	RSTACK	
?ELS5:	PRINTI	"But"
	CALL	TPRINT-PRSO
	PRINTR	" isn't asleep."


	.FUNCT	V-ANSWER
	ZERO?	AWAITING-REPLY /?ELS5
	GET	P-LEXV,P-CONT
	CALL	YES-WORD,STACK
	ZERO?	STACK /?ELS5
	CALL	V-YES
	CALL	STOP
	RSTACK	
?ELS5:	ZERO?	AWAITING-REPLY /?ELS9
	GET	P-LEXV,P-CONT
	CALL	NO-WORD,STACK
	ZERO?	STACK /?ELS9
	CALL	V-NO
	CALL	STOP
	RSTACK	
?ELS9:	PRINTI	"Nobody is awaiting your answer."
	CRLF	
	CALL	STOP
	RSTACK	


	.FUNCT	V-APPLAUD
	PRINTI	"""Clap."""
	CRLF	
	IN?	OSTRICH,HERE \TRUE
	PRINTI	"   "
	CALL	PERFORM,V?SCARE,OSTRICH
	RTRUE	


	.FUNCT	V-APPLY
	FSET?	PRSO,WEARBIT \?ELS5
	CALL	PERFORM,V?WEAR,PRSO
	RTRUE	
?ELS5:	SET	'AWAITING-REPLY,1
	ADD	C-ELAPSED,2
	CALL	QUEUE,I-REPLY,STACK
	PRINTI	"Apply"
	CALL	TPRINT-PRSO
	PRINTR	" for what? A job?"


	.FUNCT	V-ASK-ABOUT,OWINNER
	EQUAL?	PRSO,ME \?ELS5
	CALL	PERFORM,V?TELL,ME
	RTRUE	
?ELS5:	FSET?	PRSO,ACTORBIT \?ELS7
	SET	'OWINNER,WINNER
	SET	'WINNER,PRSO
	CALL	PERFORM,V?TELL-ABOUT,ME,PRSI
	SET	'WINNER,OWINNER
	CALL	THIS-IS-IT,PRSI
	CALL	THIS-IS-IT,PRSO
	RTRUE	
?ELS7:	CALL	PERFORM,V?TELL,PRSO
	RTRUE	


	.FUNCT	V-ASK-FOR
	FSET?	PRSO,ACTORBIT \?ELS3
	SET	'WINNER,PRSO
	CALL	PERFORM,V?GIVE,PRSI,ME
	RTRUE	
?ELS3:	CALL	PERFORM,V?TELL,PRSO
	RTRUE	


	.FUNCT	V-ATTRACT
	EQUAL?	PRSI,BOOTS \?ELS5
	CALL	WASTES
	RSTACK	
?ELS5:	PRINT	HUH
	RTRUE	


	.FUNCT	V-BITE
	CALL	HACK-HACK,STR?12
	RSTACK	


	.FUNCT	V-BURN
	EQUAL?	HERE,CHAPEL \?ELS5
	FSET?	ETERNAL-FLAME,ONBIT \?ELS5
	CALL	PERFORM,V?PUT,PRSO,ETERNAL-FLAME
	RTRUE	
?ELS5:	PRINTR	"You have no source of fire."


	.FUNCT	V-CALL
	CALL	VISIBLE?,PRSO
	ZERO?	STACK \?ELS5
	CALL	CANT-SEE,PRSO
	RSTACK	
?ELS5:	CALL	PERFORM,V?TELL,PRSO
	RTRUE	


	.FUNCT	V-CATCH
	PRINTR	"The only thing you're good at catching is a cold."


	.FUNCT	V-CHASTISE
	EQUAL?	PRSO,INTDIR \?ELS5
	PRINT	YOULL-HAVE-TO
	PRINTR	"go in that direction to see what's there."
?ELS5:	PRINTR	"Use prepositions to indicate precisely what you want to do: LOOK AT the object, LOOK INSIDE it, LOOK UNDER it, etc."


	.FUNCT	V-CLEAN
	SET	'AWAITING-REPLY,1
	ADD	C-ELAPSED,2
	CALL	QUEUE,I-REPLY,STACK
	PRINTR	"Do you also do windows?"


	.FUNCT	V-CLIMB-DOWN
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	DO-WALK,P?DOWN
	RSTACK	
?ELS5:	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS7
	PRINT	HOLDING-IT
	RTRUE	
?ELS7:	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-CLIMB-ON
	FSET?	PRSO,VEHBIT \?ELS5
	CALL	PERFORM,V?ENTER,PRSO
	RTRUE	
?ELS5:	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS7
	PRINT	HOLDING-IT
	RTRUE	
?ELS7:	GET	P-ITBL,P-PREP1
	EQUAL?	STACK,PR?IN \?ELS9
	CALL	CANT-VERB-A-PRSO,STR?13
	RSTACK	
?ELS9:	CALL	CANT-VERB-A-PRSO,STR?14
	RSTACK	


	.FUNCT	V-CLIMB-UP
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	DO-WALK,P?UP
	RSTACK	
?ELS5:	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS7
	PRINT	HOLDING-IT
	RTRUE	
?ELS7:	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-CLOSE
	FSET?	PRSO,SURFACEBIT /?THN6
	FSET?	PRSO,ACTORBIT /?THN6
	FSET?	PRSO,VEHBIT \?ELS5
?THN6:	CALL	CANT-VERB-A-PRSO,STR?15
	RSTACK	
?ELS5:	FSET?	PRSO,DOORBIT /?THN10
	FSET?	PRSO,CONTBIT \?ELS9
?THN10:	FSET?	PRSO,OPENBIT \?ELS16
	ZERO?	TIMER-CONNECTED /?ELS21
	CALL	ULTIMATELY-IN?,TIMER,PRSO
	ZERO?	STACK /?ELS21
	CALL	ULTIMATELY-IN?,DETONATOR,PRSO
	ZERO?	STACK \?ELS21
	CALL	DO-FIRST,STR?16
	RSTACK	
?ELS21:	ZERO?	TIMER-CONNECTED /?ELS25
	CALL	ULTIMATELY-IN?,DETONATOR,PRSO
	ZERO?	STACK /?ELS25
	CALL	ULTIMATELY-IN?,TIMER,PRSO
	ZERO?	STACK \?ELS25
	CALL	DO-FIRST,STR?16
	RSTACK	
?ELS25:	ZERO?	EXPLOSIVE-CONNECTED /?ELS29
	CALL	ULTIMATELY-IN?,DETONATOR,PRSO
	ZERO?	STACK /?ELS29
	CALL	ULTIMATELY-IN?,EXPLOSIVE,PRSO
	ZERO?	STACK \?ELS29
	CALL	DO-FIRST,STR?17
	RSTACK	
?ELS29:	ZERO?	EXPLOSIVE-CONNECTED /?ELS33
	CALL	ULTIMATELY-IN?,EXPLOSIVE,PRSO
	ZERO?	STACK /?ELS33
	CALL	ULTIMATELY-IN?,DETONATOR,PRSO
	ZERO?	STACK \?ELS33
	CALL	DO-FIRST,STR?17
	RSTACK	
?ELS33:	FCLEAR	PRSO,OPENBIT
	PRINTI	"Okay,"
	CALL	TPRINT-PRSO
	PRINTI	" is now closed."
	CRLF	
	CALL	NOW-DARK?
	RSTACK	
?ELS16:	PRINT	ALREADY-IS
	RTRUE	
?ELS9:	CALL	CANT-VERB-A-PRSO,STR?15
	RSTACK	


	.FUNCT	V-COMFORT
	FSET?	PRSO,ACTORBIT \?ELS5
	PRINTI	"But"
	CALL	TPRINT-PRSO
	PRINTR	" isn't in need of comforting!"
?ELS5:	PRINT	HUH
	RTRUE	


	.FUNCT	V-CONNECT
	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-COUNT
	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-CRAWL-UNDER
	FSET?	PRSO,TAKEBIT /?ELS5
	CALL	TELL-HIT-HEAD
	RSTACK	
?ELS5:	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-CROSS
	CALL	V-WALK-AROUND
	RSTACK	


	.FUNCT	V-CUT
	ZERO?	PRSI \?ELS5
	CALL	IMPOSSIBLES
	RSTACK	
?ELS5:	PRINTI	"To put it bluntly, neither"
	CALL	TPRINT-PRSI
	PRINTR	" nor you are very sharp."


	.FUNCT	V-DIG
	CALL	WASTES
	RSTACK	


	.FUNCT	V-DISCONNECT
	PRINTI	"But"
	CALL	TPRINT-PRSO
	PRINTI	" isn't connected to"
	ZERO?	PRSI /?ELS5
	CALL	TRPRINT,PRSI
	RSTACK	
?ELS5:	PRINTR	" anything!"


	.FUNCT	V-DISEMBARK
	EQUAL?	P-PRSA-WORD,W?HOLD \?ELS5
	GET	P-ITBL,P-PREP1
	EQUAL?	STACK,PR?DOWN \?ELS5
	CALL	PERFORM,V?PUSH,PRSO
	RTRUE	
?ELS5:	ZERO?	PRSO \?ELS9
	IN?	PROTAGONIST,HERE /?ELS14
	LOC	PROTAGONIST
	CALL	PERFORM-PRSA,STACK
	RSTACK	
?ELS14:	PRINT	LOOK-AROUND
	RTRUE	
?ELS9:	EQUAL?	P-PRSA-WORD,W?TAKE \?ELS18
	CALL	PERFORM,V?TAKE,PRSO
	RTRUE	
?ELS18:	IN?	PROTAGONIST,PRSO /?ELS20
	PRINT	LOOK-AROUND
	RETURN	8
?ELS20:	MOVE	PROTAGONIST,HERE
	PRINTI	"You get o"
	CALL	OFF-VEHICLE?,PRSO
	ZERO?	STACK /?ELS27
	PRINTI	"ff"
	JUMP	?CND25
?ELS27:	PRINTI	"ut of"
?CND25:	CALL	TPRINT-PRSO
	LOC	FLOYD
	EQUAL?	STACK,PILOT-SEAT,COPILOT-SEAT \?CND30
	MOVE	FLOYD,HERE
	PRINTI	". Floyd gets up also"
?CND30:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	V-DRESS
	ZERO?	PRSO /?ELS5
	CALL	CANT-VERB-A-PRSO,STR?18
	RSTACK	
?ELS5:	CALL	PERFORM,V?GET-DRESSED,ROOMS
	RTRUE	


	.FUNCT	PRE-DRILL
	ZERO?	PRSI \?CND1
	CALL	ULTIMATELY-IN?,DRILL
	ZERO?	STACK /?ELS6
	SET	'PRSI,DRILL
	JUMP	?CND1
?ELS6:	PRINTR	"With what? Your head isn't QUITE pointy enough."
?CND1:	EQUAL?	PRSI,DRILL /?ELS13
	PRINT	YOU-CANT
	PRINTI	"drill with"
	CALL	ARPRINT,PRSI
	RSTACK	
?ELS13:	FIRST?	DRILL /FALSE
	PRINTR	"There's no bit in the drill!"


	.FUNCT	V-DRILL
	FSET?	PRSO,TAKEBIT \?ELS5
	PRINTI	"You'll need a vice to hold down"
	CALL	TPRINT-PRSO
	PRINTR	" before you can drill it."
?ELS5:	PRINTI	"The point of the drill doesn't seem to be as hard as"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-DRILL-HOLE
	GET	P-NAMW,0
	EQUAL?	STACK,W?HOLE \?ELS5
	CALL	PERFORM,V?DRILL,PRSI
	RTRUE	
?ELS5:	PRINT	RECOGNIZE
	RTRUE	


	.FUNCT	V-DROP
	IN?	PRSO,DRILL \?CND1
	PRINTI	"[removing"
	CALL	TPRINT-PRSO
	PRINTI	" from the drill first]"
	CRLF	
?CND1:	EQUAL?	HERE,TOP-OF-AIR-SHAFT,AIR-SHAFT \?ELS8
	MOVE	PRSO,BOTTOM-OF-AIR-SHAFT
	PRINTR	"It drops down the shaft."
?ELS8:	IN?	PROTAGONIST,HOLDING-TANK \?ELS13
	MOVE	PRSO,HOLDING-TANK
	JUMP	?CND11
?ELS13:	MOVE	PRSO,HERE
?CND11:	PRINTI	"Dropped"
	FSET?	HERE,WEIGHTLESSBIT \?CND16
	PRINTI	", so to speak"
?CND16:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	PRE-EAT
	ZERO?	PRSI /?ELS5
	IN?	PRSO,PRSI /?ELS5
	CALL	NOT-IN
	RSTACK	
?ELS5:	FSET?	SPACESUIT,WORNBIT \FALSE
	PRINT	YOU-CANT
	PRINTR	"eat while you're wearing a space suit!"


	.FUNCT	V-EAT,FOOD=0
	GETP	PRSO,P?FOOD-DESC >FOOD
	ZERO?	FOOD /?ELS5
	ZERO?	HUNGER-LEVEL \?ELS10
	PRINT	NOT-HUNGRY
	RTRUE	
?ELS10:	REMOVE	PRSO
	SET	'C-ELAPSED,15
	SET	'HUNGER-LEVEL,0
	CALL	QUEUE,I-HUNGER-WARNINGS,2250
	PRINTI	"Mmmm...that tasted just like yummy"
	PRINT	FOOD
	PRINT	PERIOD-CR
	RTRUE	
?ELS5:	PRINTI	"It's doubtful that"
	CALL	TPRINT-PRSO
	PRINTR	" would agree with you."


	.FUNCT	V-EAT-FROM,X
	FSET?	PRSO,OPENBIT /?ELS5
	CALL	DO-FIRST,STR?19,PRSO
	RSTACK	
?ELS5:	FIRST?	PRSO >X \?ELS7
	PRINTI	"(How about"
	CALL	TPRINT,X
	PRINTI	"?)"
	CALL	PERFORM,V?EAT,X
	RTRUE	
?ELS7:	PRINTR	"It's empty!"


	.FUNCT	V-EMPTY,OBJ,NXT
	ZERO?	PRSI \?CND1
	SET	'PRSI,GROUND
?CND1:	FSET?	PRSO,CONTBIT /?ELS8
	PRINT	HUH
	RTRUE	
?ELS8:	FSET?	PRSO,OPENBIT /?ELS10
	PRINTI	"But"
	CALL	TPRINT-PRSO
	PRINTR	" isn't open."
?ELS10:	FIRST?	PRSO /?ELS12
	PRINTI	"But"
	CALL	TPRINT-PRSO
	PRINTR	" is already empty!"
?ELS12:	FIRST?	PRSO /?KLU44
?KLU44:	EQUAL?	PRSI,STACK \?ELS14
	NEXT?	PRSI /?ELS14
	PRINT	THERES-NOTHING
	PRINTI	"in"
	CALL	TPRINT-PRSO
	PRINTI	" but"
	CALL	TRPRINT,PRSI
	RSTACK	
?ELS14:	FIRST?	PRSO >OBJ /?KLU45
?KLU45:	
?PRG19:	NEXT?	OBJ >NXT /?KLU46
?KLU46:	EQUAL?	OBJ,PROTAGONIST /?CND21
	PRINTD	OBJ
	PRINTI	": "
	FSET?	OBJ,TAKEBIT \?ELS26
	MOVE	OBJ,PROTAGONIST
	EQUAL?	PRSI,HANDS \?ELS29
	PRINTI	"Taken."
	CRLF	
	JUMP	?CND21
?ELS29:	EQUAL?	PRSI,GROUND \?ELS31
	CALL	PERFORM,V?DROP,OBJ
	JUMP	?CND21
?ELS31:	FSET?	PRSI,SURFACEBIT \?ELS33
	CALL	PERFORM,V?PUT-ON,OBJ,PRSI
	JUMP	?CND21
?ELS33:	CALL	PERFORM,V?PUT,OBJ,PRSI
	JUMP	?CND21
?ELS26:	CALL	YUKS
?CND21:	ZERO?	NXT /TRUE
	SET	'OBJ,NXT
	JUMP	?PRG19


	.FUNCT	V-EMPTY-FROM
	IN?	PRSO,PRSI \?ELS5
	FSET?	PRSO,TAKEBIT \?ELS10
	MOVE	PRSO,PROTAGONIST
	CALL	PERFORM,V?DROP,PRSO
	RTRUE	
?ELS10:	CALL	YUKS
	RSTACK	
?ELS5:	CALL	NOT-IN
	RSTACK	


	.FUNCT	PRE-ENTER
	IN?	PROTAGONIST,PRSO \?ELS5
	PRINT	LOOK-AROUND
	RTRUE	
?ELS5:	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS7
	PRINT	HOLDING-IT
	RTRUE	
?ELS7:	CALL	UNTOUCHABLE?,PRSO
	ZERO?	STACK /FALSE
	CALL	CANT-REACH,PRSO
	RSTACK	


	.FUNCT	V-ENTER,AV
	LOC	PROTAGONIST >AV
	FSET?	PRSO,DOORBIT \?ELS5
	CALL	OTHER-SIDE,PRSO
	CALL	DO-WALK,STACK
	RTRUE	
?ELS5:	FSET?	PRSO,VEHBIT \?ELS7
	LOC	PRSO
	EQUAL?	STACK,HERE,LOCAL-GLOBALS /?ELS12
	PRINT	YOU-CANT
	PRINTI	"board"
	CALL	TPRINT-PRSO
	PRINTI	" when it's "
	LOC	PRSO
	FSET?	STACK,SURFACEBIT \?ELS15
	PRINTI	"on"
	JUMP	?CND13
?ELS15:	PRINTI	"in"
?CND13:	LOC	PRSO
	CALL	TRPRINT,STACK
	RSTACK	
?ELS12:	MOVE	PROTAGONIST,PRSO
	PRINTI	"You are now "
	FSET?	PRSO,INBIT \?ELS22
	PRINTC	105
	JUMP	?CND20
?ELS22:	PRINTC	111
?CND20:	PRINTC	110
	CALL	TPRINT-PRSO
	PRINTC	46
	GETP	PRSO,P?ACTION
	CALL	STACK,M-ENTER
	CRLF	
	RTRUE	
?ELS7:	GET	P-ITBL,P-PREP1
	EQUAL?	STACK,PR?ON \?ELS26
	CALL	CANT-VERB-A-PRSO,STR?20
	RSTACK	
?ELS26:	FSET?	PRSO,TAKEBIT /?ELS28
	CALL	TELL-HIT-HEAD
	RSTACK	
?ELS28:	GET	P-ITBL,P-PREP1
	EQUAL?	STACK,PR?IN \FALSE
	CALL	CANT-VERB-A-PRSO,STR?21
	RSTACK	


	.FUNCT	V-EXAMINE
	SET	'C-ELAPSED,32
	FSET?	PRSO,ACTORBIT \?ELS5
	FIRST?	PRSO \?ELS10
	CALL	PERFORM,V?LOOK-INSIDE,PRSO
	RTRUE	
?ELS10:	CALL	NOTHING-INTERESTING
	PRINTI	"about"
	CALL	TRPRINT,PRSO
	RSTACK	
?ELS5:	FSET?	PRSO,SURFACEBIT \?ELS14
	CALL	V-LOOK-INSIDE
	RSTACK	
?ELS14:	FSET?	PRSO,DOORBIT \?ELS16
	PRINT	IT-SEEMS-THAT
	CALL	TPRINT-PRSO
	PRINTI	" is "
	CALL	OPEN-CLOSED,PRSO
	PRINT	PERIOD-CR
	RTRUE	
?ELS16:	IN?	PROTAGONIST,PRSO \?ELS18
	CALL	DESCRIBE-VEHICLE
	RSTACK	
?ELS18:	FSET?	PRSO,CONTBIT \?ELS20
	FSET?	PRSO,VEHBIT /?ELS20
	PRINTI	"It's "
	CALL	OPEN-CLOSED,PRSO
	FSET?	PRSO,OPENBIT /?THN28
	FSET?	PRSO,TRANSBIT \?ELS27
?THN28:	PRINTI	". "
	CALL	V-LOOK-INSIDE
	RSTACK	
?ELS27:	PRINT	PERIOD-CR
	RTRUE	
?ELS20:	FSET?	PRSO,LIGHTBIT \?ELS33
	PRINTI	"It looks like"
	CALL	TPRINT-PRSO
	PRINTI	" is o"
	FSET?	PRSO,ACTIVEBIT \?ELS36
	PRINTC	110
	JUMP	?CND34
?ELS36:	PRINTI	"ff"
?CND34:	PRINT	PERIOD-CR
	RTRUE	
?ELS33:	FSET?	PRSO,READBIT \?ELS40
	CALL	PERFORM,V?READ,PRSO
	RTRUE	
?ELS40:	FSET?	PRSO,NARTICLEBIT \?ELS42
	CALL	SENSE-OBJECT,STR?22
	RSTACK	
?ELS42:	RANDOM	100
	LESS?	35,STACK \?THN45
	EQUAL?	PRSO,PSEUDO-OBJECT \?ELS44
?THN45:	PRINTI	"Totally ordinary looking "
	PRINTD	PRSO
	PRINT	PERIOD-CR
	RTRUE	
?ELS44:	CALL	NOTHING-INTERESTING
	PRINTI	"about"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-EXERCISE
	GRTR?	PLATO-ATTACK-COUNTER,0 \?ELS3
	IN?	PLATO,HERE \?ELS3
	CALL	STUNNED
	RTRUE	
?ELS3:	IN?	PROTAGONIST,EXERCISE-MACHINE \?ELS7
	CALL	ULTIMATELY-IN?,JAMMER,HERE
	ZERO?	STACK /?ELS10
	EQUAL?	JAMMER-SETTING,710 \?ELS10
	FSET?	JAMMER,ACTIVEBIT \?ELS10
	IN?	TWENTY-PRONG-FROMITZ-BOARD,JAMMER \?ELS10
	PRINTR	"The machine seems to be frozen."
?ELS10:	PRINTI	"You do a few repetitions"
	JUMP	?CND1
?ELS7:	PRINTI	"You drop to the deck and do a few push-ups"
?CND1:	PRINTR	". Dr. Ventricalli, the Duffy's cardiologist, would be pleased."


	.FUNCT	NOTHING-INTERESTING
	PRINT	THERES-NOTHING
	RANDOM	100
	LESS?	25,STACK /?ELS3
	PRINTI	"unusual"
	JUMP	?CND1
?ELS3:	RANDOM	100
	LESS?	33,STACK /?ELS5
	PRINTI	"noteworthy"
	JUMP	?CND1
?ELS5:	RANDOM	100
	LESS?	50,STACK /?ELS7
	PRINTI	"eye-catching"
	JUMP	?CND1
?ELS7:	PRINTI	"special"
?CND1:	PRINTC	32
	RTRUE	


	.FUNCT	V-EXIT
	ZERO?	PRSO /?ELS5
	FSET?	PRSO,VEHBIT \?ELS5
	CALL	PERFORM,V?DISEMBARK,PRSO
	RTRUE	
?ELS5:	CALL	DO-WALK,P?OUT
	RSTACK	


	.FUNCT	V-FEED
	PRINTI	"You have no food for"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-FILL
	ZERO?	PRSI \?ELS5
	PRINT	THERES-NOTHING
	PRINTR	"to fill it with."
?ELS5:	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-FIND,WHERE=0,L
	LOC	PRSO >L
	SET	'C-ELAPSED,18
	ZERO?	L \?ELS5
	CALL	PRONOUN
	PRINTR	" could be anywhere!"
?ELS5:	IN?	PRSO,PROTAGONIST \?ELS7
	PRINTR	"You have it!"
?ELS7:	IN?	PRSO,HERE /?THN10
	CALL	GLOBAL-IN?,PRSO,HERE
	ZERO?	STACK \?THN10
	EQUAL?	PRSO,PSEUDO-OBJECT \?ELS9
?THN10:	PRINTR	"Right in front of you."
?ELS9:	FSET?	L,ACTORBIT \?ELS13
	CALL	VISIBLE?,L
	ZERO?	STACK /?ELS13
	PRINTI	"Looks as if"
	CALL	TPRINT,L
	PRINTR	" has it."
?ELS13:	FSET?	L,CONTBIT \?ELS17
	CALL	VISIBLE?,PRSO
	ZERO?	STACK /?ELS17
	IN?	L,GLOBAL-OBJECTS /?ELS17
	FSET?	L,SURFACEBIT \?ELS22
	PRINTC	79
	JUMP	?CND20
?ELS22:	FSET?	L,VEHBIT \?ELS24
	FSET?	L,INBIT /?ELS24
	PRINTC	79
	JUMP	?CND20
?ELS24:	PRINTC	73
?CND20:	PRINTC	110
	CALL	TRPRINT,L
	RSTACK	
?ELS17:	ZERO?	WHERE /?THN31
	IN?	PRSO,GLOBAL-OBJECTS \?ELS30
?THN31:	PRINTR	"You'll have to do that yourself."
?ELS30:	PRINTR	"Beats me."


	.FUNCT	V-FLATTEN
	PRINT	HUH
	RTRUE	


	.FUNCT	V-FOLLOW
	CALL	VISIBLE?,PRSO
	ZERO?	STACK /?ELS5
	PRINTI	"But"
	CALL	TPRINT-PRSO
	PRINTR	" is right here!"
?ELS5:	FSET?	PRSO,ACTORBIT /?ELS7
	CALL	IMPOSSIBLES
	RSTACK	
?ELS7:	PRINTI	"You have no idea where"
	CALL	TPRINT-PRSO
	PRINTR	" is."


	.FUNCT	PRE-GIVE
	EQUAL?	PRSA,V?GIVE \?ELS5
	EQUAL?	PRSO,HANDS \?ELS5
	CALL	PERFORM,V?SHAKE-WITH,PRSI
	RTRUE	
?ELS5:	CALL	IDROP
	ZERO?	STACK \TRUE
	RFALSE	


	.FUNCT	V-GET-DRESSED
	EQUAL?	PRSO,ROOMS \?ELS5
	PRINTR	"You are!"
?ELS5:	CALL	RECOGNIZE
	RSTACK	


	.FUNCT	V-GET-UNDRESSED
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	PERFORM,V?TAKE-OFF,PATROL-UNIFORM
	RTRUE	
?ELS5:	CALL	RECOGNIZE
	RSTACK	


	.FUNCT	V-GIVE
	FSET?	PRSI,ACTORBIT \?ELS5
	PRINTI	"Briskly,"
	CALL	TPRINT-PRSI
	PRINTR	" declines your offer."
?ELS5:	PRINT	YOU-CANT
	PRINTI	"give"
	CALL	APRINT,PRSO
	PRINTI	" to"
	CALL	APRINT,PRSI
	PRINTR	"!"


	.FUNCT	V-GIVE-UP
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	V-QUIT
	RSTACK	
?ELS5:	CALL	RECOGNIZE
	RSTACK	


	.FUNCT	V-GREET
	FSET?	PRSO,ACTORBIT \?ELS3
	SET	'WINNER,PRSO
	CALL	PERFORM,V?HELLO
	SET	'WINNER,PROTAGONIST
	RTRUE	
?ELS3:	CALL	PERFORM,V?TELL,PRSO
	RTRUE	


	.FUNCT	V-HELLO
	ZERO?	PRSO /?ELS5
	PRINTR	"[The proper way to talk to characters in the story is PERSON, HELLO.]"
?ELS5:	CALL	PERFORM,V?TELL,ME
	RTRUE	


	.FUNCT	V-HELP
	PRINTR	"[Help!?! You need help?!? Do you know how hard it is being a computer? My chips feel are about to go, my wife just ran off with a mainframe from Milwaukee, and one of the kids just told me that when he grows up he wants to be a talking greeting card! Furtherm... Hey! I'm not done! Mumk mpgrlph...] If you're really stuck, you can order a complete map and InvisiClues hint booklet from your dealer or by using the order form from your package."


	.FUNCT	V-HIDE
	PRINT	YOU-CANT
	PRINTI	"hide "
	ZERO?	PRSO /?CND1
	PRINTC	116
?CND1:	PRINTR	"here."


	.FUNCT	V-HUG
	PRINTR	"Hugged."


	.FUNCT	V-IN,VEHICLE
	CALL	DO-WALK,P?IN
	RSTACK	


	.FUNCT	V-KICK
	CALL	HACK-HACK,STR?23
	RSTACK	


	.FUNCT	V-KILL
	EQUAL?	PRSI,ZAPGUN \?ELS5
	CALL	PERFORM,V?SHOOT,PRSO,PRSI
	RTRUE	
?ELS5:	ZERO?	PRSI \?ELS7
	CALL	ULTIMATELY-IN?,ZAPGUN
	ZERO?	STACK /?ELS7
	PRINTI	"(with"
	CALL	TPRINT,ZAPGUN
	PRINTC	41
	CRLF	
	CALL	PERFORM,V?SHOOT,PRSO,ZAPGUN
	RTRUE	
?ELS7:	FSET?	PRSO,ACTORBIT \?ELS11
	PRINTI	"You succeeded in frightening"
	CALL	TRPRINT,PRSO
	RSTACK	
?ELS11:	PRINTI	"Why attack"
	CALL	APRINT,PRSO
	PRINTR	"?"


	.FUNCT	V-KISS
	PRINTR	"I'd sooner kiss a pile of Antarian swamp mold."


	.FUNCT	V-KNOCK
	FSET?	PRSO,DOORBIT \?ELS5
	PRINTR	"Silence answers back."
?ELS5:	CALL	HACK-HACK,STR?24
	RSTACK	


	.FUNCT	V-LAUNCH
	PRINTR	"Your brain is out to launch."


	.FUNCT	V-LEAP
	ZERO?	PRSO /?ELS5
	PRINTR	"You have spent too much time among the leaping loon-toads of Leonia."
?ELS5:	EQUAL?	HERE,CHAPEL \?ELS8
	FSET?	STAR,TRYTAKEBIT \?ELS8
	PRINTR	"Your best jump still leaves you half a meter short of the star."
?ELS8:	EQUAL?	HERE,BOTTOM-OF-AIR-SHAFT \?ELS12
	CALL	PERFORM,V?OPEN,GRATING
	RTRUE	
?ELS12:	CALL	WEE
	RSTACK	


	.FUNCT	V-LEAP-OFF
	FSET?	PRSO,VEHBIT \?ELS5
	CALL	PERFORM,V?DISEMBARK,PRSO
	RTRUE	
?ELS5:	CALL	PERFORM,V?LEAP,PRSO
	RTRUE	


	.FUNCT	V-LEAVE
	ZERO?	PRSO \?CND1
	SET	'PRSO,ROOMS
?CND1:	EQUAL?	PRSO,ROOMS \?ELS8
	CALL	DO-WALK,P?OUT
	RSTACK	
?ELS8:	IN?	PROTAGONIST,PRSO \?ELS10
	CALL	PERFORM,V?DISEMBARK,PRSO
	RTRUE	
?ELS10:	CALL	PERFORM,V?DROP,PRSO
	RTRUE	


	.FUNCT	V-LIE-DOWN
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	GLOBAL-IN?,BED,HERE
	ZERO?	STACK /?ELS10
	CALL	PERFORM,V?ENTER,BED
	RTRUE	
?ELS10:	GRTR?	SLEEPY-LEVEL,0 \?ELS12
	CALL	V-SLEEP
	RSTACK	
?ELS12:	CALL	WASTES
	RSTACK	
?ELS5:	FSET?	PRSO,VEHBIT \?ELS16
	CALL	PERFORM,V?ENTER,PRSO
	RTRUE	
?ELS16:	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-LISTEN
	SET	'C-ELAPSED,18
	ZERO?	PRSO /?ELS5
	CALL	SENSE-OBJECT,STR?25
	RSTACK	
?ELS5:	PRINTR	"You hear nothing of interest."


	.FUNCT	V-LOCK
	CALL	YUKS
	RSTACK	


	.FUNCT	PRE-LOOK
	EQUAL?	PRSO,STAR \?ELS5
	IN?	DIODE-M,STAR /FALSE
?ELS5:	ZERO?	LIT \FALSE
	PRINT	TOO-DARK
	CRLF	
	RTRUE	


	.FUNCT	V-LOOK
	SET	'C-ELAPSED,9
	CALL	DESCRIBE-ROOM,TRUE-VALUE
	ZERO?	STACK /TRUE
	CALL	DESCRIBE-OBJECTS
	RTRUE	


	.FUNCT	V-LOOK-BEHIND
	FSET?	PRSO,DOORBIT \?ELS5
	CALL	PERFORM,V?LOOK-INSIDE,PRSO
	RTRUE	
?ELS5:	PRINTI	"There is nothing behind"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-LOOK-DOWN
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	PERFORM,V?EXAMINE,GROUND
	RTRUE	
?ELS5:	CALL	PERFORM,V?LOOK-INSIDE,PRSO
	RTRUE	


	.FUNCT	V-LOOK-INSIDE
	GRTR?	PLATO-ATTACK-COUNTER,0 \?ELS5
	IN?	PLATO,HERE \?ELS5
	CALL	STUNNED
	RSTACK	
?ELS5:	FSET?	PRSO,ACTORBIT \?ELS9
	PRINT	IT-SEEMS-THAT
	CALL	TPRINT-PRSO
	PRINTI	" has"
	CALL	DESCRIBE-NOTHING
	ZERO?	STACK \TRUE
	PRINT	PERIOD-CR
	RTRUE	
?ELS9:	IN?	PROTAGONIST,PRSO \?ELS14
	CALL	DESCRIBE-VEHICLE
	RSTACK	
?ELS14:	FSET?	PRSO,SURFACEBIT \?ELS16
	PRINT	YOU-SEE
	CALL	DESCRIBE-NOTHING
	ZERO?	STACK \TRUE
	PRINTI	" on"
	CALL	TRPRINT,PRSO
	RTRUE	
?ELS16:	FSET?	PRSO,DOORBIT \?ELS21
	PRINTI	"All you can tell is that"
	CALL	TPRINT-PRSO
	PRINTI	" is "
	CALL	OPEN-CLOSED,PRSO
	PRINT	PERIOD-CR
	RTRUE	
?ELS21:	FSET?	PRSO,CONTBIT \?ELS23
	CALL	SEE-INSIDE?,PRSO
	ZERO?	STACK /?ELS28
	PRINT	YOU-SEE
	CALL	DESCRIBE-NOTHING
	ZERO?	STACK \TRUE
	PRINTI	" in"
	CALL	TRPRINT,PRSO
	RTRUE	
?ELS28:	FSET?	PRSO,OPENBIT /?ELS33
	FIRST?	PRSO \?ELS33
	CALL	PRE-TOUCH
	ZERO?	STACK \TRUE
	CALL	PERFORM,V?OPEN,PRSO
	RTRUE	
?ELS33:	CALL	DO-FIRST,STR?19,PRSO
	RSTACK	
?ELS23:	GET	P-ITBL,P-PREP1
	EQUAL?	STACK,PR?IN \?ELS42
	CALL	CANT-VERB-A-PRSO,STR?26
	RSTACK	
?ELS42:	CALL	CANT-VERB-A-PRSO,STR?27
	RSTACK	


	.FUNCT	V-LOOK-OVER
	CALL	V-EXAMINE
	RSTACK	


	.FUNCT	V-LOOK-UNDER
	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS5
	FSET?	PRSO,WORNBIT \?ELS10
	PRINTR	"You're wearing it!"
?ELS10:	PRINT	HOLDING-IT
	RTRUE	
?ELS5:	CALL	NOTHING-INTERESTING
	PRINTI	"under"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-LOOK-UP
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	PERFORM,V?EXAMINE,CEILING
	RTRUE	
?ELS5:	CALL	PERFORM,V?LOOK-INSIDE,PRSO
	RTRUE	


	.FUNCT	V-LOWER
	CALL	V-RAISE
	RSTACK	


	.FUNCT	V-MAYBE
	CALL	YOU-SOUND,STR?28
	RSTACK	


	.FUNCT	V-MEASURE
	FSET?	PRSO,PARTBIT /?THN6
	EQUAL?	PRSO,ME \?ELS5
?THN6:	PRINTR	"Usual size."
?ELS5:	PRINTI	"The same size as any other "
	PRINTD	PRSO
	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	V-MOVE
	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS5
	CALL	WASTES
	RSTACK	
?ELS5:	CALL	LOC-CLOSED
	ZERO?	STACK \TRUE
	FSET?	PRSO,TAKEBIT \?ELS9
	PRINTI	"Moving"
	CALL	TPRINT-PRSO
	PRINTR	" reveals nothing."
?ELS9:	EQUAL?	P-PRSA-WORD,W?PULL \?ELS11
	CALL	HACK-HACK,STR?29
	RSTACK	
?ELS11:	CALL	CANT-VERB-A-PRSO,STR?30
	RSTACK	


	.FUNCT	PRE-MUNG
	ZERO?	PRSI /FALSE
	EQUAL?	PRSI,ZAPGUN \FALSE
	CALL	PERFORM,V?SHOOT,PRSO,PRSI
	RTRUE	


	.FUNCT	V-MUNG
	EQUAL?	PRSO,ROOMS \?ELS5
	PRINTR	"Argh! Pimples!"
?ELS5:	CALL	HACK-HACK,STR?31
	RSTACK	


	.FUNCT	V-NO
	EQUAL?	AWAITING-REPLY,1 \?ELS5
	CALL	V-YES
	RSTACK	
?ELS5:	EQUAL?	AWAITING-REPLY,2,4 \?ELS7
	PRINTR	"Floyd pouts."
?ELS7:	EQUAL?	AWAITING-REPLY,3 \?ELS9
	PRINTR	"""Figures."""
?ELS9:	CALL	YOU-SOUND,STR?32
	RSTACK	


	.FUNCT	NO-WORD,WRD
	EQUAL?	WRD,W?NO,W?NOPE /TRUE
	EQUAL?	WRD,W?NAH,W?UH-UH \FALSE
	RTRUE	


	.FUNCT	V-OFF
	FSET?	PRSO,LIGHTBIT \?ELS5
	FSET?	PRSO,ACTIVEBIT \?ELS10
	FCLEAR	PRSO,ACTIVEBIT
	FCLEAR	PRSO,ONBIT
	PRINTI	"Okay,"
	CALL	TPRINT-PRSO
	PRINTI	" is now off."
	CRLF	
	CALL	NOW-DARK?
	RSTACK	
?ELS10:	PRINTR	"It isn't on!"
?ELS5:	CALL	CANT-TURN,STR?33
	RSTACK	


	.FUNCT	V-ON
	FSET?	PRSO,LIGHTBIT \?ELS5
	FSET?	PRSO,ACTIVEBIT \?ELS10
	PRINT	ALREADY-IS
	RTRUE	
?ELS10:	FSET	PRSO,ACTIVEBIT
	EQUAL?	PRSO,HEADLAMP \?CND13
	FSET	PRSO,ONBIT
?CND13:	PRINTI	"Okay,"
	CALL	TPRINT-PRSO
	PRINTI	" is now on."
	CRLF	
	CALL	NOW-LIT?
	RSTACK	
?ELS5:	CALL	CANT-TURN,STR?34
	RSTACK	


	.FUNCT	CANT-TURN,STRING
	PRINT	YOU-CANT
	PRINTI	"turn that o"
	PRINT	STRING
	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	V-OPEN
	FSET?	PRSO,SURFACEBIT /?THN6
	FSET?	PRSO,ACTORBIT /?THN6
	FSET?	PRSO,VEHBIT \?ELS5
?THN6:	CALL	IMPOSSIBLES
	RSTACK	
?ELS5:	FSET?	PRSO,OPENBIT \?ELS9
	PRINT	ALREADY-IS
	RTRUE	
?ELS9:	FSET?	PRSO,DOORBIT /?ELS11
	FSET?	PRSO,CONTBIT /?ELS11
	CALL	CANT-VERB-A-PRSO,STR?19
	RSTACK	
?ELS11:	FSET?	PRSO,LOCKEDBIT \?ELS15
	PRINTR	"It's locked."
?ELS15:	FSET?	PRSO,DOORBIT \?ELS17
	FSET	PRSO,OPENBIT
	PRINTI	"The "
	PRINTD	PRSO
	PRINTR	" swings open."
?ELS17:	FSET	PRSO,OPENBIT
	FSET	PRSO,TOUCHBIT
	FIRST?	PRSO \?THN23
	FSET?	PRSO,TRANSBIT \?ELS22
?THN23:	PRINTR	"Opened."
?ELS22:	PRINTI	"Opening"
	CALL	TPRINT-PRSO
	PRINTI	" reveals"
	CALL	DESCRIBE-NOTHING
	ZERO?	STACK \?CND27
	PRINT	PERIOD-CR
?CND27:	CALL	NOW-LIT?
	RTRUE	


	.FUNCT	V-PICK
	CALL	CANT-VERB-A-PRSO,STR?35
	RSTACK	


	.FUNCT	V-PICK-UP
	CALL	PERFORM,V?TAKE,PRSO,PRSI
	RTRUE	


	.FUNCT	V-PLAY-WITH
	FSET?	PRSO,ACTORBIT \?ELS5
	CALL	WEE
	RSTACK	
?ELS5:	PRINTR	"You're wacko."


	.FUNCT	V-POINT
	PRINTR	"That would be pointless."


	.FUNCT	V-POUR
	PRINTR	"Pouring or spilling non-liquids is specifically forbidden by section 17.9.2 of the Galactic Adventure Game Compendium of Rules."


	.FUNCT	V-PRAY
	PRINTR	"If you pray enough, your prayers may be answered."


	.FUNCT	V-PUSH
	GET	P-NAMW,0
	EQUAL?	STACK,W?ONE,W?TWO,W?THREE \?ELS5
	CALL	GLOBAL-IN?,KEYPAD,HERE
	ZERO?	STACK /?ELS5
	PRINT	TYPE-NUMERALS
	RTRUE	
?ELS5:	EQUAL?	P-PRSA-WORD,W?PRESS,W?IRON \?ELS9
	EQUAL?	HERE,LAUNDRY \?ELS9
	ZERO?	PRSI /?THN12
	EQUAL?	PRSI,PRESSER \?ELS9
?THN12:	IN?	PRSO,PRESSER \?ELS18
	CALL	PERFORM,V?CLOSE,PRESSER
	RTRUE	
?ELS18:	CALL	DO-FIRST,STR?36
	RSTACK	
?ELS9:	CALL	HACK-HACK,STR?37
	RSTACK	


	.FUNCT	V-PUSH-DIR
	EQUAL?	PRSI,INTDIR \?ELS5
	CALL	V-PUSH
	RSTACK	
?ELS5:	CALL	RECOGNIZE
	RSTACK	


	.FUNCT	PRE-PUT
	EQUAL?	PRSI,GROUND \?ELS5
	CALL	PERFORM,V?DROP,PRSO
	RTRUE	
?ELS5:	EQUAL?	PRSO,HANDS \?ELS7
	EQUAL?	PRSA,V?PUT,V?PUT-ON \?ELS12
	FSET?	PRSI,PARTBIT /FALSE
?ELS12:	EQUAL?	PRSA,V?PUT \?ELS16
	CALL	PERFORM,V?REACH-IN,PRSI
	RTRUE	
?ELS16:	CALL	IMPOSSIBLES
	RSTACK	
?ELS7:	FSET?	PRSI,PARTBIT /?ELS20
	CALL	PRE-LOOK
	ZERO?	STACK \TRUE
?ELS20:	CALL	ULTIMATELY-IN?,PRSI,PRSO
	ZERO?	STACK /?ELS24
	PRINT	YOU-CANT
	PRINTI	"put"
	CALL	TPRINT-PRSO
	GET	P-ITBL,P-PREP2
	EQUAL?	STACK,PR?ON \?ELS27
	PRINTI	" on"
	JUMP	?CND25
?ELS27:	PRINTI	" in"
?CND25:	CALL	TPRINT-PRSI
	PRINTI	" when"
	CALL	TPRINT-PRSI
	PRINTI	" is already "
	FSET?	PRSO,SURFACEBIT \?ELS32
	PRINTI	"on"
	JUMP	?CND30
?ELS32:	PRINTI	"in"
?CND30:	CALL	TPRINT-PRSO
	PRINTR	"!"
?ELS24:	CALL	UNTOUCHABLE?,PRSI
	ZERO?	STACK /?ELS36
	CALL	CANT-REACH,PRSI
	RSTACK	
?ELS36:	CALL	IDROP
	ZERO?	STACK \TRUE
	RFALSE	


	.FUNCT	V-PUT,?TMP1,?TMP2,?TMP3
	FSET?	PRSI,OPENBIT /?ELS5
	FSET?	PRSI,CONTBIT /?ELS5
	FSET?	PRSI,SURFACEBIT /?ELS5
	FSET?	PRSI,VEHBIT /?ELS5
	PRINT	YOU-CANT
	PRINTI	"put"
	CALL	TPRINT-PRSO
	PRINTI	" in"
	CALL	APRINT,PRSI
	PRINTR	"!"
?ELS5:	EQUAL?	PRSI,PRSO /?THN10
	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS9
	FSET?	PRSO,TAKEBIT /?ELS9
?THN10:	PRINTR	"How can you do that?"
?ELS9:	FSET?	PRSI,DOORBIT \?ELS15
	PRINT	CANT-FROM-HERE
	RTRUE	
?ELS15:	FSET?	PRSI,OPENBIT /?ELS17
	FSET?	PRSI,SURFACEBIT /?ELS17
	CALL	THIS-IS-IT,PRSI
	CALL	DO-FIRST,STR?19,PRSI
	RSTACK	
?ELS17:	IN?	PRSO,PRSI \?ELS21
	PRINTI	"But"
	CALL	TPRINT-PRSO
	PRINTI	" is already in"
	CALL	TRPRINT,PRSI
	RSTACK	
?ELS21:	FSET?	PRSI,ACTORBIT \?ELS23
	PRINT	HUH
	RTRUE	
?ELS23:	CALL	WEIGHT,PRSI >?TMP3
	CALL	WEIGHT,PRSO
	ADD	?TMP3,STACK >?TMP2
	GETP	PRSI,P?SIZE
	SUB	?TMP2,STACK >?TMP1
	GETP	PRSI,P?CAPACITY
	GRTR?	?TMP1,STACK \?ELS25
	CALL	ULTIMATELY-IN?,PRSO,PRSI
	ZERO?	STACK \?ELS25
	PRINTI	"There's no room "
	FSET?	PRSI,SURFACEBIT \?ELS30
	PRINTI	"on"
	JUMP	?CND28
?ELS30:	PRINTI	"in"
?CND28:	CALL	TPRINT-PRSI
	PRINTI	" for"
	CALL	TRPRINT,PRSO
	RSTACK	
?ELS25:	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK \?ELS34
	CALL	ITAKE
	EQUAL?	STACK,M-FATAL,FALSE-VALUE /TRUE
?ELS34:	MOVE	PRSO,PRSI
	CALL	SCORE-OBJ
	PRINTR	"Done."


	.FUNCT	V-PUT-BEHIND
	CALL	WASTES
	RSTACK	


	.FUNCT	V-PUT-ON
	EQUAL?	PRSI,ME \?ELS5
	CALL	PERFORM,V?WEAR,PRSO
	RTRUE	
?ELS5:	FSET?	PRSI,SURFACEBIT /?THN8
	FSET?	PRSI,VEHBIT \?ELS7
?THN8:	CALL	V-PUT
	RSTACK	
?ELS7:	PRINTI	"There's no good surface on"
	CALL	TRPRINT,PRSI
	RSTACK	


	.FUNCT	V-PUT-UNDER
	CALL	WASTES
	RSTACK	


	.FUNCT	V-RAISE
	CALL	HACK-HACK,STR?38
	RSTACK	


	.FUNCT	V-REACH-IN,OBJ
	FIRST?	PRSO >OBJ /?KLU16
?KLU16:	FSET?	PRSO,ACTORBIT /?THN6
	FSET?	PRSO,SURFACEBIT /?THN6
	FSET?	PRSO,CONTBIT /?ELS5
?THN6:	CALL	YUKS
	RSTACK	
?ELS5:	FSET?	PRSO,OPENBIT /?ELS9
	CALL	DO-FIRST,STR?19,PRSO
	RSTACK	
?ELS9:	ZERO?	OBJ /?THN12
	FSET?	OBJ,INVISIBLE /?THN12
	FSET?	OBJ,TAKEBIT /?ELS11
?THN12:	PRINT	THERES-NOTHING
	PRINTI	"in"
	CALL	TRPRINT,PRSO
	RSTACK	
?ELS11:	PRINTI	"You feel something inside"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-READ
	FSET?	PRSO,READBIT \?ELS5
	GETP	PRSO,P?TEXT
	PRINT	STACK
	CRLF	
	RTRUE	
?ELS5:	CALL	CANT-VERB-A-PRSO,STR?39
	RSTACK	


	.FUNCT	V-REMOVE
	FSET?	PRSO,WEARBIT \?ELS5
	CALL	PERFORM,V?TAKE-OFF,PRSO
	RTRUE	
?ELS5:	CALL	PERFORM,V?TAKE,PRSO
	RTRUE	


	.FUNCT	V-ROLL
	CALL	CANT-VERB-A-PRSO,STR?40
	RSTACK	


	.FUNCT	V-RUN-OVER
	PRINT	HUH
	RTRUE	


	.FUNCT	V-SAVE-SOMETHING
	PRINTI	"Sorry, but"
	CALL	TPRINT-PRSO
	PRINTR	" is beyond help."


	.FUNCT	V-SAY,V
	ZERO?	AWAITING-REPLY /?ELS5
	GET	P-LEXV,P-CONT
	CALL	YES-WORD,STACK
	ZERO?	STACK /?ELS5
	CALL	V-YES
	CALL	STOP
	RSTACK	
?ELS5:	ZERO?	AWAITING-REPLY /?ELS9
	GET	P-LEXV,P-CONT
	CALL	NO-WORD,STACK
	ZERO?	STACK /?ELS9
	CALL	V-NO
	CALL	STOP
	RSTACK	
?ELS9:	CALL	FIND-IN,HERE,ACTORBIT >V
	ZERO?	V /?ELS13
	PRINTI	"You must address"
	CALL	TPRINT,V
	PRINTI	" directly."
	CRLF	
	CALL	STOP
	RSTACK	
?ELS13:	CALL	PERFORM,V?TELL,ME
	CALL	STOP
	RSTACK	


	.FUNCT	V-SCARE
	PRINTI	"Despite your most frightening tactics,"
	CALL	TPRINT-PRSO
	PRINTR	" seems unscared."


	.FUNCT	V-SCOLD
	PRINT	HUH
	RTRUE	


	.FUNCT	V-SEARCH
	FSET?	PRSO,ACTORBIT \?ELS5
	CALL	V-SHAKE
	RSTACK	
?ELS5:	IN?	PROTAGONIST,PRSO \?ELS7
	CALL	DESCRIBE-VEHICLE
	RSTACK	
?ELS7:	FSET?	PRSO,CONTBIT \?ELS9
	FSET?	PRSO,OPENBIT /?ELS9
	CALL	DO-FIRST,STR?19,PRSO
	RSTACK	
?ELS9:	FSET?	PRSO,CONTBIT \?ELS13
	SET	'C-ELAPSED,32
	PRINTI	"You find"
	CALL	DESCRIBE-NOTHING
	ZERO?	STACK \TRUE
	PRINT	PERIOD-CR
	RTRUE	
?ELS13:	CALL	CANT-VERB-A-PRSO,STR?41
	RSTACK	


	.FUNCT	V-SET
	EQUAL?	PRSO,ROOMS \?ELS5
	CALL	WEE
	RSTACK	
?ELS5:	ZERO?	PRSI \?ELS7
	FSET?	PRSO,TAKEBIT \?ELS12
	CALL	HACK-HACK,STR?42
	RSTACK	
?ELS12:	PRINT	YNH
	CALL	TRPRINT,PRSO
	RSTACK	
?ELS7:	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-SGIVE
	CALL	PERFORM,V?GIVE,PRSI,PRSO
	RTRUE	


	.FUNCT	V-SHAKE
	FSET?	PRSO,ACTORBIT \?ELS5
	PRINTR	"That wouldn't be polite."
?ELS5:	CALL	HACK-HACK,STR?43
	RSTACK	


	.FUNCT	V-SHAKE-WITH
	EQUAL?	PRSO,HANDS /?ELS5
	CALL	RECOGNIZE
	RSTACK	
?ELS5:	FSET?	PRSI,ACTORBIT /?ELS7
	PRINTI	"I don't think"
	CALL	TPRINT-PRSI
	PRINTR	" even has hands."
?ELS7:	CALL	PERFORM,V?THANK,PRSI
	RTRUE	


	.FUNCT	PRE-SHOOT
	ZERO?	PRSI \?CND1
	CALL	ULTIMATELY-IN?,ZAPGUN
	ZERO?	STACK /?CND1
	EQUAL?	PRSO,ZAPGUN \?ELS8
	ZERO?	ZAPGUN-SHOTS \?ELS11
	PRINTR	"""Click."""
?ELS11:	DEC	'ZAPGUN-SHOTS
	PRINTR	"Some nasty flames shoot out the maw of the zapgun."
?ELS8:	SET	'PRSI,ZAPGUN
	PRINTI	"(with the "
	PRINTD	ZAPGUN
	PRINTC	41
	CRLF	
?CND1:	ZERO?	PRSI \?ELS20
	PRINTR	"You aren't holding a gun!"
?ELS20:	EQUAL?	PRSI,ZAPGUN /?ELS22
	PRINTI	"Shoot"
	CALL	APRINT,PRSI
	PRINTR	"!?!"
?ELS22:	EQUAL?	PRSO,ZAPGUN \?ELS24
	PRINTR	"Sorry; the zapgun doesn't have a rubber barrel."
?ELS24:	ZERO?	ZAPGUN-SHOTS \?ELS26
	PRINTR	"""Click."""
?ELS26:	DEC	'ZAPGUN-SHOTS
	RFALSE	


	.FUNCT	V-SHOOT
	PRINTI	"A blaze of intense rays "
	FSET?	PRSO,TAKEBIT \?ELS5
	PRINTI	"envelop"
	CALL	TPRINT-PRSO
	PRINTI	". When the rays dissipate,"
	CALL	TPRINT-PRSO
	PRINTC	32
	FSET?	PRSO,PLURALBIT \?ELS8
	PRINTI	"are"
	JUMP	?CND6
?ELS8:	PRINTI	"is"
?CND6:	PRINTI	" gone."
	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS15
	PRINTI	" Unfortunately, so is most of your "
	FSET?	PRSO,WORNBIT \?ELS18
	PRINTI	"body, since you were wear"
	JUMP	?CND16
?ELS18:	PRINTI	"arm, since you were hold"
?CND16:	PRINTI	"ing"
	CALL	TPRINT-PRSO
	CALL	JIGS-UP,STR?44
	RSTACK	
?ELS15:	CALL	REMOVE-CAREFULLY,PRSO
	CRLF	
	RTRUE	
?ELS5:	PRINTI	"wash over"
	CALL	TPRINT-PRSO
	PRINTR	". It glows for a bit, but then cools."


	.FUNCT	V-SSHOOT
	CALL	PERFORM,V?SHOOT,PRSI,PRSO
	CALL	THIS-IS-IT,PRSO
	RTRUE	


	.FUNCT	V-SHOW
	PRINTI	"It doesn't look like"
	CALL	TPRINT-PRSI
	PRINTR	" is interested."


	.FUNCT	V-SIT,VEHICLE
	EQUAL?	PRSO,ROOMS /?ELS5
	CALL	PERFORM,V?ENTER,PRSO
	RTRUE	
?ELS5:	CALL	FIND-IN,HERE,VEHBIT >VEHICLE
	ZERO?	VEHICLE /?ELS7
	CALL	PERFORM,V?ENTER,VEHICLE
	RTRUE	
?ELS7:	CALL	PERFORM,V?CLIMB-ON,GROUND
	RTRUE	


	.FUNCT	V-SKIP
	CALL	WEE
	RSTACK	


	.FUNCT	V-SLEEP
	ZERO?	SLEEPY-LEVEL \?ELS5
	PRINTR	"You're not tired."
?ELS5:	CALL	QUEUED?,I-FALL-ASLEEP
	ZERO?	STACK /?ELS7
	PRINTR	"You'll probably be asleep before you know it."
?ELS7:	PRINTR	"Members of civilized societies usually sleep in beds."


	.FUNCT	V-SMELL
	ZERO?	PRSO \?ELS5
	FSET?	SPACESUIT,WORNBIT \?ELS10
	PRINTI	"You smell stale air and rusty metal and unbathed "
	PRINT	LFC
	PRINTR	" -- all the usual odors of the inside a space suit."
?ELS10:	ZERO?	BALLOON-ODOR /?ELS12
	PRINTR	"The nauseating odor of burnt digestive gas is thankfully fading."
?ELS12:	EQUAL?	HERE,GREASY-STRAW \?ELS15
	IN?	NECTAR,LOCAL-GLOBALS \?ELS15
	PRINTR	"There's something yum-smelling around here!"
?ELS15:	EQUAL?	HERE,OPIUM-DEN \?ELS19
	PRINTR	"There's a lingering smell of various drugs."
?ELS19:	CALL	VISIBLE?,BALLOON
	ZERO?	STACK /?ELS21
	PRINTR	"There's an odor reminiscent of the video room at home on a night when your mom served Northern Gallium Bonzo Beans."
?ELS21:	PRINTR	"You smell nothing unusual just now."
?ELS5:	CALL	SENSE-OBJECT,STR?45
	RSTACK	


	.FUNCT	SENSE-OBJECT,STRING
	CALL	PRONOUN
	PRINTC	32
	PRINT	STRING
	FSET?	PRSO,PLURALBIT /?CND1
	EQUAL?	PRSO,ME /?CND1
	PRINTC	115
?CND1:	PRINTI	" just like"
	CALL	ARPRINT,PRSO
	RSTACK	


	.FUNCT	V-SPLAY-WITH
	CALL	PERFORM,V?PLAY-WITH,PRSI
	RTRUE	


	.FUNCT	V-SPRAY
	ZERO?	PRSI \?ELS5
	IN?	SPRAY-CAN,PROTAGONIST \?ELS5
	PRINTI	"[with the "
	PRINTD	SPRAY-CAN
	PRINTC	93
	CRLF	
	CALL	PERFORM,V?SPRAY,SPRAY-CAN,PRSO
	RTRUE	
?ELS5:	CALL	CANT-VERB-A-PRSO,STR?46
	RSTACK	


	.FUNCT	V-SPUT-ON
	CALL	PERFORM,V?PUT-ON,PRSI,PRSO
	RTRUE	


	.FUNCT	V-SSHOW
	CALL	PERFORM,V?SHOW,PRSI,PRSO
	RTRUE	


	.FUNCT	V-SSPRAY
	CALL	PERFORM,V?SPRAY,PRSI,PRSO
	RTRUE	


	.FUNCT	V-STAND
	EQUAL?	P-PRSA-WORD,W?HOLD \?ELS5
	CALL	WASTES
	RSTACK	
?ELS5:	LOC	PROTAGONIST
	FSET?	STACK,VEHBIT \?ELS7
	LOC	PROTAGONIST
	CALL	PERFORM,V?DISEMBARK,STACK
	RTRUE	
?ELS7:	ZERO?	PRSO /?ELS9
	FSET?	PRSO,TAKEBIT \?ELS9
	CALL	WASTES
	RSTACK	
?ELS9:	PRINTR	"You're already standing."


	.FUNCT	V-STAND-ON
	CALL	WASTES
	RSTACK	


	.FUNCT	V-STELL
	CALL	PERFORM,V?TELL,PRSI
	RTRUE	


	.FUNCT	V-STHROW
	CALL	PERFORM,V?THROW-TO,PRSI,PRSO
	RTRUE	


	.FUNCT	V-SWING
	ZERO?	PRSI /?ELS5
	CALL	PERFORM,V?KILL,PRSI,PRSO
	RTRUE	
?ELS5:	PRINTR	"""Whoosh."""


	.FUNCT	V-SWRAP
	CALL	PERFORM,V?PUT-ON,PRSO,PRSI
	RTRUE	


	.FUNCT	PRE-TAKE
	GRTR?	PLATO-ATTACK-COUNTER,0 \?ELS5
	IN?	PLATO,HERE \?ELS5
	CALL	STUNNED,STR?47
	RSTACK	
?ELS5:	CALL	UNTOUCHABLE?,PRSO
	ZERO?	STACK /?ELS9
	CALL	CANT-REACH,PRSO
	RSTACK	
?ELS9:	FSET?	PRSO,PARTBIT /?ELS11
	CALL	PRE-LOOK
	ZERO?	STACK \TRUE
?ELS11:	CALL	LOC-CLOSED
	ZERO?	STACK \TRUE
	IN?	PROTAGONIST,PRSO \?ELS17
	PRINTI	"You're "
	FSET?	PRSO,INBIT \?ELS20
	PRINTC	105
	JUMP	?CND18
?ELS20:	PRINTC	111
?CND18:	PRINTR	"n it, asteroid-brain!"
?ELS17:	IN?	PRSO,PROTAGONIST /?THN25
	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /?ELS24
	FSET?	PRSO,TAKEBIT /?ELS24
?THN25:	FSET?	PRSO,WORNBIT \?ELS31
	PRINTI	"You're already wearing"
	JUMP	?CND29
?ELS31:	PRINTI	"You already have"
?CND29:	CALL	TPRINT-PRSO
	PRINT	PERIOD-CR
	RTRUE	
?ELS24:	IN?	PRSO,HEATING-CHAMBER \?ELS35
	CALL	PERFORM,V?REACH-IN,HEATING-CHAMBER
	RTRUE	
?ELS35:	EQUAL?	PRSO,LEASH \?ELS37
	EQUAL?	PRSI,BALLOON \?ELS37
	CALL	PERFORM,V?REMOVE,LEASH
	RTRUE	
?ELS37:	ZERO?	PRSI /FALSE
	IN?	PRSO,PRSI /FALSE
	EQUAL?	PRSO,ME \?ELS45
	CALL	PERFORM,V?DROP,PRSI
	RTRUE	
?ELS45:	EQUAL?	PRSI,GLOBAL-ROOM \?ELS47
	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK /FALSE
	CALL	DO-WALK,P?OUT
	RSTACK	
?ELS47:	IN?	PRSO,PRSI /?ELS56
	CALL	NOT-IN
	RSTACK	
?ELS56:	SET	'PRSI,FALSE-VALUE
	RFALSE	


	.FUNCT	V-TAKE
	CALL	ITAKE
	EQUAL?	STACK,TRUE-VALUE \FALSE
	ZERO?	ID-SCRAMBLED \?CND6
	EQUAL?	PRSO,ID-CARD \?ELS14
	CALL	ULTIMATELY-IN?,BOOTS
	ZERO?	STACK /?ELS14
	FSET?	BOOTS,WORNBIT \?THN11
?ELS14:	EQUAL?	PRSO,BOOTS \?CND6
	CALL	ULTIMATELY-IN?,ID-CARD
	ZERO?	STACK /?CND6
?THN11:	FCLEAR	BOOTS,TRYTAKEBIT
	FCLEAR	ID-CARD,TRYTAKEBIT
	SET	'ID-SCRAMBLED,TRUE-VALUE
?CND6:	PRINTR	"Taken."


	.FUNCT	V-TAKE-OFF
	EQUAL?	PRSO,ROOMS \?ELS5
	LOC	PROTAGONIST
	FSET?	STACK,VEHBIT \?ELS10
	PRINTI	"[of"
	LOC	PROTAGONIST
	CALL	TPRINT,STACK
	PRINTC	93
	CRLF	
	LOC	PROTAGONIST
	CALL	PERFORM,V?DISEMBARK,STACK
	RTRUE	
?ELS10:	CALL	V-STAND
	RSTACK	
?ELS5:	FSET?	PRSO,WORNBIT \?ELS14
	SET	'C-ELAPSED,18
	FCLEAR	PRSO,WORNBIT
	PRINTI	"Okay, you're no longer wearing"
	CALL	TRPRINT,PRSO
	RSTACK	
?ELS14:	FSET?	PRSO,VEHBIT \?ELS16
	CALL	PERFORM,V?DISEMBARK,PRSO
	RTRUE	
?ELS16:	PRINTI	"You aren't wearing"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-TAKE-WITH
	PRINTI	"Sorry,"
	CALL	TPRINT-PRSI
	PRINTI	" is no help in getting"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-TASTE
	GETP	PRSO,P?FOOD-DESC
	ZERO?	STACK /?ELS5
	PRINTR	"It tastes edible."
?ELS5:	CALL	SENSE-OBJECT,STR?48
	RSTACK	


	.FUNCT	V-TELL
	FSET?	PRSO,ACTORBIT \?ELS5
	ZERO?	P-CONT /?ELS10
	SET	'WINNER,PRSO
	SET	'ELIMINATE-CR,TRUE-VALUE
	RTRUE	
?ELS10:	PRINTI	"Hmmm..."
	CALL	TPRINT-PRSO
	PRINTR	" looks at you expectantly, as if you seemed to be about to talk."
?ELS5:	PRINTI	"Talking to"
	CALL	APRINT,PRSO
	PRINTI	"? Dr. Blanchard, the Duffy's psychiatrist, would be fascinated to hear that."
	CRLF	
	CALL	STOP
	RSTACK	


	.FUNCT	V-TELL-ABOUT
	EQUAL?	PRSO,ME \?ELS5
	CALL	PERFORM,V?WHAT,PRSI
	RTRUE	
?ELS5:	CALL	PERFORM,V?SHOW,PRSI,PRSO
	RTRUE	


	.FUNCT	V-THANK,OWINNER
	ZERO?	PRSO \?ELS5
	PRINTR	"[Just doing my job.]"
?ELS5:	FSET?	PRSO,ACTORBIT \?ELS7
	SET	'OWINNER,WINNER
	SET	'WINNER,PRSO
	CALL	PERFORM,V?THANK
	SET	'WINNER,OWINNER
	RTRUE	
?ELS7:	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-THROW
	EQUAL?	HERE,VACUUM-STORAGE \?ELS5
	PRINTI	"You lose sight of"
	CALL	TPRINT-PRSO
	PRINTI	" as it sails away."
	CALL	REMOVE-CAREFULLY,PRSO
	CRLF	
	RTRUE	
?ELS5:	ZERO?	PRSI /?ELS7
	MOVE	PRSO,HERE
	PRINTR	"You missed."
?ELS7:	MOVE	PRSO,HERE
	PRINTR	"Thrown."


	.FUNCT	V-THROW-TO
	FSET?	PRSI,ACTORBIT \?ELS5
	CALL	PERFORM,V?GIVE,PRSO,PRSI
	RTRUE	
?ELS5:	CALL	PERFORM,V?THROW,PRSO,PRSI
	RTRUE	


	.FUNCT	V-TICKLE
	PRINTR	"Kitchy kitchy koo?"


	.FUNCT	V-TIE
	PRINT	YOU-CANT
	PRINTI	"tie"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-TIME,NO-CR=0
	PRINTI	"Current Galactic Standard Time "
	FSET?	CHRONOMETER,WORNBIT \?ELS3
	LESS?	DAY,3 \?ELS3
	PRINTI	"(adjusted to your local day-cycle) is "
	PRINTN	INTERNAL-MOVES
	JUMP	?CND1
?ELS3:	PRINTI	"is impossible to determine, since you"
	FSET?	CHRONOMETER,WORNBIT /?ELS10
	PRINTI	"'ve removed your chronometer"
	JUMP	?CND1
?ELS10:	PRINTI	"r chronometer has stopped"
?CND1:	ZERO?	NO-CR /?ELS17
	PRINTC	46
	RTRUE	
?ELS17:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	PRE-TOUCH,VB=1
	GRTR?	PLATO-ATTACK-COUNTER,0 \?ELS5
	IN?	PLATO,HERE \?ELS5
	ZERO?	VB /TRUE
	CALL	STUNNED,STR?47
	RTRUE	
?ELS5:	CALL	UNTOUCHABLE?,PRSO
	ZERO?	STACK /FALSE
	ZERO?	VB /TRUE
	CALL	CANT-REACH,PRSO
	RTRUE	


	.FUNCT	V-TOUCH
	CALL	LOC-CLOSED
	ZERO?	STACK \TRUE
	CALL	HACK-HACK,STR?49
	RSTACK	


	.FUNCT	V-TYPE
	ZERO?	PRSI /?ELS5
	EQUAL?	PRSI,KEYPAD /?ELS5
	PRINT	YOU-CANT
	PRINTI	"type on"
	CALL	APRINT,PRSI
	PRINTR	"!"
?ELS5:	CALL	GLOBAL-IN?,KEYPAD,HERE
	ZERO?	STACK \?ELS9
	ZERO?	PRSO /?ELS14
	PRINT	HUH
	RTRUE	
?ELS14:	PRINTI	"There's no keypad here!"
	CRLF	
	CALL	STOP
	RSTACK	
?ELS9:	ZERO?	PRSO /?ELS19
	EQUAL?	PRSO,INTNUM \?ELS19
	EQUAL?	HERE,ROBOT-POOL \?ELS26
	CALL	ROBOT-TYPE
	RSTACK	
?ELS26:	EQUAL?	HERE,SPACETRUCK \?ELS28
	CALL	SPACETRUCK-TYPE
	RSTACK	
?ELS28:	EQUAL?	HERE,SHADY-DANS \?ELS30
	CALL	ID-CHANGER-TYPE
	RSTACK	
?ELS30:	EQUAL?	HERE,PX \?ELS32
	CALL	DISPENSER-TYPE
	RSTACK	
?ELS32:	CALL	ELEVATOR-TYPE
	RSTACK	
?ELS19:	ZERO?	PRSO \?ELS36
	ZERO?	P-CONT /?ELS36
	CALL	NUMBER?,P-CONT
	EQUAL?	STACK,W?NUMBER \?ELS36
	CALL	PERFORM,V?TYPE,INTNUM
	CALL	STOP
	RSTACK	
?ELS36:	GET	P-NAMW,0
	EQUAL?	STACK,W?ONE,W?TWO,W?THREE \?ELS40
	PRINT	TYPE-NUMERALS
	RTRUE	
?ELS40:	PRINTI	"You can only type numbers on this keypad."
	CRLF	
	CALL	STOP
	RSTACK	


	.FUNCT	ROBOT-TYPE
	FSET?	ROBOT-USE-AUTHORIZATION-FORM,NDESCBIT /?ELS5
	CALL	RECORDING,STR?50
	RSTACK	
?ELS5:	ZERO?	ROBOT-PICKED /?ELS7
	CALL	RECORDING,STR?51
	RSTACK	
?ELS7:	GRTR?	P-NUMBER,10 \?ELS10
	PRINTR	"There are only ten keys on the keypad."
?ELS10:	GRTR?	P-NUMBER,3 \?ELS12
	CALL	RECORDING,STR?52
	RSTACK	
?ELS12:	LESS?	P-NUMBER,1 \?ELS14
	CALL	RECORDING,STR?53
	RSTACK	
?ELS14:	EQUAL?	P-NUMBER,3 \?ELS16
	FSET	FLOYD,TOUCHBIT
	SET	'ROBOT-PICKED,FLOYD
	SET	'FLOYD-SPOKE,TRUE-VALUE
	PRINTR	"""Yippee!"" yells Floyd, bounding joyfully over and giving you a big hug."
?ELS16:	EQUAL?	P-NUMBER,1 \?ELS21
	SET	'ROBOT-PICKED,REX
	JUMP	?CND19
?ELS21:	SET	'ROBOT-PICKED,HELEN
?CND19:	CALL	DEQUEUE,I-FLOYD
	CALL	QUEUE,I-OTHER-ROBOT,-1
	FSET	ROBOT-PICKED,TOUCHBIT
	PRINTD	ROBOT-PICKED
	PRINTR	" rolls up to you, ready to follow. Floyd's lower jaw begins quivering, as though he were about to cry."


	.FUNCT	SPACETRUCK-TYPE,X
	FSET?	CLASS-THREE-SPACECRAFT-ACTIVATION-FORM,NDESCBIT /?ELS5
	CALL	RECORDING,STR?50
	RSTACK	
?ELS5:	EQUAL?	SPACETRUCK-COUNTER,5 \?ELS7
	CALL	RECORDING,STR?54
	RSTACK	
?ELS7:	ZERO?	COURSE-PICKED /?ELS9
	CALL	RECORDING,STR?51
	RSTACK	
?ELS9:	IN?	PROTAGONIST,PILOT-SEAT /?THN14
	IN?	FLOYD,PILOT-SEAT \?ELS11
?THN14:	IN?	PROTAGONIST,COPILOT-SEAT /?THN16
	IN?	FLOYD,COPILOT-SEAT \?ELS11
?THN16:	SET	'COURSE-PICKED,P-NUMBER
	DIV	INTERNAL-MOVES,10 >X
	DIV	X,5 >X
	MUL	X,5 >X
	SUB	X,660 >X
	MUL	X,X >X
	DIV	X,100 >X
	ADD	X,103 >RIGHT-COURSE
	CALL	QUEUE,I-SPACETRUCK,33
	CALL	RECORDING,STR?55
	RSTACK	
?ELS11:	CALL	RECORDING,STR?56
	RSTACK	


	.FUNCT	ELEVATOR-TYPE,DISTANCE
	EQUAL?	ELEVATOR-LEVEL,P-NUMBER \?ELS5
	CALL	RECORDING,STR?57
	RSTACK	
?ELS5:	GRTR?	P-NUMBER,9 /?THN8
	LESS?	P-NUMBER,1 \?ELS7
?THN8:	CALL	RECORDING,STR?58
	RSTACK	
?ELS7:	EQUAL?	P-NUMBER,8,9 \?ELS11
	PRINTR	"The elevator whines momentarily, but doesn't move."
?ELS11:	GRTR?	DAY,2 \?ELS13
	CALL	JIGS-UP,STR?59
	RSTACK	
?ELS13:	PRINTI	"The elevator "
	EQUAL?	DAY,1 \?ELS18
	PRINTI	"glides weightlessly "
	JUMP	?CND16
?ELS18:	PRINTI	"starts with a jerk, moving "
?CND16:	GRTR?	P-NUMBER,ELEVATOR-LEVEL \?ELS23
	PRINTI	"down"
	SUB	P-NUMBER,ELEVATOR-LEVEL >DISTANCE
	JUMP	?CND21
?ELS23:	PRINTI	"up"
	SUB	ELEVATOR-LEVEL,P-NUMBER >DISTANCE
?CND21:	MUL	5,DISTANCE >C-ELAPSED
	SET	'ELEVATOR-LEVEL,P-NUMBER
	PRINTI	" the shaft, stopping "
	EQUAL?	DAY,2 \?CND26
	PRINTI	"suddenly "
?CND26:	EQUAL?	DAY,2 \?ELS31
	GRTR?	INTERNAL-MOVES,6300 \?ELS31
	PRINTI	"and not quite at level with your new floor"
	JUMP	?CND29
?ELS31:	PRINTI	"at another opening to the west"
?CND29:	IN?	BALLOON,ELEVATOR \?CND36
	PRINTI	". The "
	PRINTD	BALLOON
	PRINTI	" looks somewhat disoriented by the experience"
?CND36:	IN?	OSTRICH,ELEVATOR \?ELS43
	PRINTI	". "
	CALL	PERFORM,V?SCARE,OSTRICH
	RTRUE	
?ELS43:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	DISPENSER-TYPE
	FSET?	DISPENSER,TOUCHBIT /?ELS5
	CALL	RECORDING,STR?60
	RSTACK	
?ELS5:	GRTR?	P-NUMBER,9 \?ELS7
	CALL	RECORDING,STR?61
	RSTACK	
?ELS7:	EQUAL?	P-NUMBER,6,9 \?ELS9
	FCLEAR	DISPENSER,TOUCHBIT
	EQUAL?	P-NUMBER,6 \?ELS12
	MOVE	TIMER,DISPENSER
	JUMP	?CND10
?ELS12:	MOVE	LARGE-BIT,DISPENSER
?CND10:	PRINTR	"You hear a loud ""klunk"" inside the dispenser, but nothing appears in the dispenser hole."
?ELS9:	LESS?	P-NUMBER,1 \?ELS16
	CALL	RECORDING,STR?53
	RSTACK	
?ELS16:	CALL	RECORDING,STR?62
	RSTACK	


	.FUNCT	RECORDING,STRING
	RANDOM	100
	LESS?	33,STACK /?ELS3
	PRINTI	"A recording says,"
	JUMP	?CND1
?ELS3:	RANDOM	100
	LESS?	50,STACK /?ELS5
	PRINTI	"You hear a recorded voice."
	JUMP	?CND1
?ELS5:	PRINTI	"A taped voice whispers in your ear."
?CND1:	PRINTI	" """
	PRINT	STRING
	PRINTR	"."""


	.FUNCT	V-UNDRESS
	ZERO?	PRSO /?ELS5
	CALL	IMPOSSIBLES
	RSTACK	
?ELS5:	SET	'PRSO,ROOMS
	CALL	V-GET-UNDRESSED
	RSTACK	


	.FUNCT	V-UNLOCK
	FSET?	PRSO,LOCKEDBIT /?ELS5
	PRINTI	"But"
	CALL	TPRINT-PRSO
	PRINTR	" isn't locked."
?ELS5:	ZERO?	PRSI \?ELS7
	CALL	ULTIMATELY-IN?,KEY
	ZERO?	STACK /?ELS12
	PRINTI	"[with the key]"
	CRLF	
	CALL	PERFORM,V?UNLOCK,PRSO,KEY
	RTRUE	
?ELS12:	SET	'AWAITING-REPLY,1
	ADD	C-ELAPSED,2
	CALL	QUEUE,I-REPLY,STACK
	PRINTR	"Your nose is key-shaped, I suppose?"
?ELS7:	ZERO?	PRSI /FALSE
	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-UNTIE
	CALL	IMPOSSIBLES
	RSTACK	


	.FUNCT	V-USE
	PRINT	YOULL-HAVE-TO
	PRINTI	"be more specific about how you want to use"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	PRE-VALIDATE
	ZERO?	PRSI \?ELS5
	CALL	VISIBLE?,VALIDATION-STAMP
	ZERO?	STACK \?ELS5
	PRINTR	"You don't have a validation stamp!"
?ELS5:	ZERO?	PRSI \?ELS9
	CALL	ULTIMATELY-IN?,VALIDATION-STAMP
	ZERO?	STACK \?ELS9
	PRINT	YNH
	CALL	TRPRINT,VALIDATION-STAMP
	RSTACK	
?ELS9:	ZERO?	PRSI /FALSE
	EQUAL?	PRSI,VALIDATION-STAMP /FALSE
	PRINT	HUH
	RTRUE	


	.FUNCT	V-VALIDATE
	PRINTI	"There's no validation box on"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-WALK,AV,VEHICLE,PT,PTS,STR,OBJ,RM
	LOC	PROTAGONIST >AV
	ZERO?	P-WALK-DIR \?ELS5
	CALL	PERFORM,V?WALK-TO,PRSO
	RTRUE	
?ELS5:	GRTR?	PLATO-ATTACK-COUNTER,0 \?ELS7
	IN?	PLATO,HERE \?ELS7
	CALL	STUNNED,STR?63
	RSTACK	
?ELS7:	EQUAL?	PRSO,P?OUT \?ELS11
	EQUAL?	AV,SIMULATION-BOOTH,HOLDING-TANK \?ELS11
	CALL	PERFORM,V?DISEMBARK,AV
	RTRUE	
?ELS11:	ZERO?	HANGING-IN-AIR /?ELS15
	EQUAL?	PRSO,P?DOWN \?ELS21
	CALL	PERFORM,V?DROP,LEASH
	RTRUE	
?ELS21:	PRINTR	"It's hard to walk when your feet are a couple of meters from the floor."
?ELS15:	EQUAL?	PRSO,P?IN \?ELS25
	GETPT	HERE,P?IN
	ZERO?	STACK \?ELS25
	CALL	FIND-IN,HERE,VEHBIT >VEHICLE
	ZERO?	VEHICLE /?ELS25
	CALL	ULTIMATELY-IN?,VEHICLE
	ZERO?	STACK \?ELS25
	CALL	PERFORM,V?ENTER,VEHICLE
	RTRUE	
?ELS25:	FSET?	AV,VEHBIT \?ELS29
	PRINTI	"You're not walking anywhere until you get "
	CALL	OFF-VEHICLE?,AV
	ZERO?	STACK /?ELS32
	PRINTI	"off"
	JUMP	?CND30
?ELS32:	PRINTI	"out of"
?CND30:	CALL	TRPRINT,AV
	RETURN	8
?ELS29:	ZERO?	TIMER-CONNECTED /?ELS38
	CALL	ULTIMATELY-IN?,TIMER
	ZERO?	STACK /?ELS38
	CALL	ULTIMATELY-IN?,DETONATOR
	ZERO?	STACK \?ELS38
	CALL	DO-FIRST,STR?16
	RSTACK	
?ELS38:	ZERO?	TIMER-CONNECTED /?ELS42
	CALL	ULTIMATELY-IN?,DETONATOR
	ZERO?	STACK /?ELS42
	CALL	ULTIMATELY-IN?,TIMER
	ZERO?	STACK \?ELS42
	CALL	DO-FIRST,STR?16
	RSTACK	
?ELS42:	ZERO?	EXPLOSIVE-CONNECTED /?ELS46
	CALL	ULTIMATELY-IN?,DETONATOR
	ZERO?	STACK /?ELS46
	CALL	ULTIMATELY-IN?,EXPLOSIVE
	ZERO?	STACK \?ELS46
	CALL	DO-FIRST,STR?17
	RSTACK	
?ELS46:	ZERO?	EXPLOSIVE-CONNECTED /?ELS50
	CALL	ULTIMATELY-IN?,EXPLOSIVE
	ZERO?	STACK /?ELS50
	CALL	ULTIMATELY-IN?,DETONATOR
	ZERO?	STACK \?ELS50
	CALL	DO-FIRST,STR?17
	RSTACK	
?ELS50:	GETPT	HERE,PRSO >PT
	ZERO?	PT /?ELS54
	PTSIZE	PT >PTS
	EQUAL?	PTS,UEXIT \?ELS59
	SET	'C-ELAPSED,22
	GETB	PT,REXIT
	CALL	GOTO,STACK
	RSTACK	
?ELS59:	EQUAL?	PTS,CEXIT \?ELS61
	EQUAL?	HERE,CASINO \?ELS66
	GETB	PT,CEXITFLAG
	VALUE	STACK
	ZERO?	STACK /?ELS71
	SET	'C-ELAPSED,22
	GETB	PT,REXIT
	CALL	GOTO,STACK
	RSTACK	
?ELS71:	PRINT	CANT-GO
	RETURN	8
?ELS66:	SET	'C-ELAPSED,22
	ZERO?	VERBOSITY /?CND78
	CALL	DESCRIBE-AUTO-DOOR
?CND78:	GETB	PT,REXIT
	CALL	GOTO,STACK
	RSTACK	
?ELS61:	EQUAL?	PTS,NEXIT \?ELS82
	GET	PT,NEXITSTR
	PRINT	STACK
	CRLF	
	RETURN	8
?ELS82:	EQUAL?	PTS,FEXIT \?ELS86
	SET	'C-ELAPSED,22
	GET	PT,FEXITFCN
	CALL	STACK >RM
	ZERO?	RM /?ELS91
	CALL	GOTO,RM
	RSTACK	
?ELS91:	EQUAL?	HERE,AIR-SHAFT /TRUE
	SET	'C-ELAPSED,7
	RETURN	8
?ELS86:	EQUAL?	PTS,DEXIT \FALSE
	GETB	PT,DEXITOBJ >OBJ
	FSET?	OBJ,OPENBIT \?ELS109
	SET	'C-ELAPSED,22
	GETB	PT,REXIT
	CALL	GOTO,STACK
	RSTACK	
?ELS109:	GET	PT,DEXITSTR >STR
	ZERO?	STR /?ELS111
	CALL	THIS-IS-IT,OBJ
	PRINT	STR
	CRLF	
	RETURN	8
?ELS111:	CALL	THIS-IS-IT,OBJ
	CALL	DO-FIRST,STR?19,OBJ
	RETURN	8
?ELS54:	EQUAL?	PRSO,P?IN,P?OUT \?ELS119
	CALL	V-WALK-AROUND
	RETURN	8
?ELS119:	PRINT	CANT-GO
	RETURN	8


	.FUNCT	DESCRIBE-AUTO-DOOR
	EQUAL?	HERE,BRIG,ARMORY \?ELS3
	PRINTI	"The security door "
	JUMP	?CND1
?ELS3:	PRINTI	"The auto-door "
?CND1:	EQUAL?	DAY,1 \?ELS8
	PRINTI	"opens as you approach, and whisks shut behind you..."
	JUMP	?CND6
?ELS8:	GRTR?	DAY,2 \?ELS10
	PRINTI	"opens barely wide enough for you to squeeze through. As you do so, the door tries to shut, jamming against you!"
	FSET?	AUTO-DOOR,TOUCHBIT /?CND6
	FSET	AUTO-DOOR,TOUCHBIT
	PRINTI	" Fortunately, auto-doors don't have a lot of power."
	JUMP	?CND6
?ELS10:	PRINTI	"opens sluggishly. As soon as you have passed through, it zooms shut, "
	GRTR?	INTERNAL-MOVES,5000 \?ELS18
	PRINTI	"almost nipping your heels!"
	JUMP	?CND16
?ELS18:	PRINTI	"seemingly a little sooner than normal."
?CND16:	FSET?	AUTO-DOOR,TOUCHBIT /?CND6
	FSET	AUTO-DOOR,TOUCHBIT
	PRINTI	" Very puzzling; auto-doors have been around for millenia, and are generally the epitome of reliability."
?CND6:	CRLF	
	CRLF	
	RTRUE	


	.FUNCT	V-WALK-AROUND
	SET	'AWAITING-REPLY,1
	CALL	QUEUE,I-REPLY,1
	SET	'P-WON,FALSE-VALUE
	PRINTR	"Did you have any particular direction in mind?"


	.FUNCT	V-WALK-TO
	EQUAL?	PRSO,INTDIR \?ELS5
	CALL	DO-WALK,P-DIRECTION
	RSTACK	
?ELS5:	CALL	VISIBLE?,PRSO
	ZERO?	STACK /?ELS7
	FSET?	PRSO,VEHBIT \?ELS12
	CALL	PERFORM,V?ENTER,PRSO
	RTRUE	
?ELS12:	CALL	V-FOLLOW
	RSTACK	
?ELS7:	CALL	V-WALK-AROUND
	RSTACK	


	.FUNCT	V-WAIT,NUM=3
	SET	'C-ELAPSED,40
	PRINTR	"Time passes..."


	.FUNCT	V-WAIT-FOR
	CALL	VISIBLE?,PRSO
	ZERO?	STACK /?ELS5
	CALL	V-FOLLOW
	RSTACK	
?ELS5:	PRINTR	"You may be waiting quite a while."


	.FUNCT	V-WEAR
	FSET?	PRSO,WEARBIT /?ELS5
	CALL	CANT-VERB-A-PRSO,STR?64
	RSTACK	
?ELS5:	PRINTI	"You're "
	FSET?	PRSO,WORNBIT \?ELS10
	PRINTI	"already"
	JUMP	?CND8
?ELS10:	MOVE	PRSO,PROTAGONIST
	FSET	PRSO,WORNBIT
	SET	'C-ELAPSED,18
	PRINTI	"now"
?CND8:	PRINTI	" wearing"
	CALL	TRPRINT,PRSO
	RSTACK	


	.FUNCT	V-WHAT
	PRINTR	"Good question."


	.FUNCT	V-WHERE
	CALL	V-FIND,TRUE-VALUE
	RSTACK	


	.FUNCT	V-WRAP
	CALL	PERFORM,V?PUT-ON,PRSI,PRSO
	RTRUE	


	.FUNCT	V-YELL
	PRINTI	"Aaaarrgghh!"
	CRLF	
	IN?	OSTRICH,HERE \?CND1
	PRINTI	"   "
	CALL	PERFORM,V?SCARE,OSTRICH
	RTRUE	
?CND1:	CALL	STOP
	RSTACK	


	.FUNCT	I-REPLY
	SET	'AWAITING-REPLY,FALSE-VALUE
	RFALSE	


	.FUNCT	V-YES
	EQUAL?	AWAITING-REPLY,1 \?ELS5
	PRINTR	"That was just a rhetorical question."
?ELS5:	EQUAL?	AWAITING-REPLY,2 \?ELS7
	PRINTR	"""Floyd changed his mind. These controls are too scary-looking."""
?ELS7:	EQUAL?	AWAITING-REPLY,3 \?ELS9
	PRINTR	"Floyd shrugs. ""Floyd not feel like learning new rules now. Let's play tag. Floyd knows rules for tag really well!"""
?ELS9:	EQUAL?	AWAITING-REPLY,4 \?ELS11
	CALL	PERFORM,V?PLAY-WITH,FLOYD
	RTRUE	
?ELS11:	CALL	YOU-SOUND,STR?65
	RSTACK	


	.FUNCT	YOU-SOUND,STRING
	PRINTI	"You sound rather "
	PRINT	STRING
	PRINTR	"ive."


	.FUNCT	YES-WORD,WRD
	EQUAL?	WRD,W?YES,W?Y,W?YUP /TRUE
	EQUAL?	WRD,W?OK,W?OKAY,W?SURE \FALSE
	RTRUE	


	.FUNCT	V-ZORK
	PRINTR	"Gesundheit!"


	.FUNCT	ITAKE,VB=1,OBJ,?TMP1
	FSET?	PRSO,TAKEBIT /?ELS3
	ZERO?	VB /?CND4
	CALL	YUKS
?CND4:	RETURN	8
?ELS3:	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK \?ELS11
	CALL	WEIGHT,PRSO >?TMP1
	CALL	WEIGHT,PROTAGONIST
	ADD	?TMP1,STACK
	GRTR?	STACK,100 \?ELS11
	ZERO?	VB /?CND14
	PRINTI	"You're already carrying as much weight as you can manage."
	CRLF	
?CND14:	RETURN	8
?ELS11:	CALL	CCOUNT,PROTAGONIST
	MUL	STACK,20
	SUB	STACK,150 >?TMP1
	RANDOM	100
	LESS?	?TMP1,STACK /?CND1
	FIRST?	PROTAGONIST >OBJ /?KLU40
?KLU40:	
?PRG22:	FSET?	OBJ,WORNBIT \?REP23
	NEXT?	OBJ >OBJ /?PRG22
	JUMP	?PRG22
?REP23:	MOVE	PRSO,HERE
	MOVE	OBJ,HERE
	FSET	PRSO,TOUCHBIT
	ZERO?	VB /?CND29
	PRINTI	"As you try to grab"
	CALL	TPRINT-PRSO
	PRINTC	44
	CALL	TPRINT,OBJ
	PRINTI	" slips from your hands and both tumble "
	FSET?	HERE,WEIGHTLESSBIT \?ELS35
	PRINTI	"away"
	JUMP	?CND33
?ELS35:	PRINTI	"to the floor"
?CND33:	PRINT	PERIOD-CR
?CND29:	RETURN	8
?CND1:	CALL	SCORE-OBJ
	MOVE	PRSO,PROTAGONIST
	RTRUE	


	.FUNCT	SCORE-OBJ,POINTS
	FSET	PRSO,TOUCHBIT
	FCLEAR	PRSO,NDESCBIT
	GETP	PRSO,P?VALUE >POINTS
	ZERO?	POINTS /FALSE
	GRTR?	POINTS,0 \?CND6
	INC	'ROBOT-EVILNESS
?CND6:	PUTP	PRSO,P?VALUE,0
	ADD	SCORE,POINTS >SCORE
	RETURN	SCORE


	.FUNCT	IDROP
	EQUAL?	PRSO,HANDS \?ELS5
	EQUAL?	PRSA,V?GIVE,V?THROW,V?DROP \FALSE
	CALL	IMPOSSIBLES
	RSTACK	
?ELS5:	EQUAL?	PRSA,V?GIVE,V?DROP \?ELS14
	EQUAL?	PRSO,LEASH \?ELS14
	ZERO?	HANGING-IN-AIR \FALSE
?ELS14:	CALL	ULTIMATELY-IN?,PRSO
	ZERO?	STACK \?ELS18
	EQUAL?	PRSA,V?THROW \?ELS21
	EQUAL?	PRSO,SWITCH /FALSE
?ELS21:	EQUAL?	PRSO,ME /?THN26
	FSET?	PRSO,PARTBIT \?ELS25
?THN26:	CALL	IMPOSSIBLES
	RETURN	8
?ELS25:	PRINTI	"That's easy for you to say since you don't even have"
	CALL	TRPRINT,PRSO
	RETURN	8
?ELS18:	IN?	PRSO,PROTAGONIST /?ELS33
	LOC	PRSO
	FSET?	STACK,CONTBIT \?ELS33
	LOC	PRSO
	FSET?	STACK,OPENBIT /?ELS33
	LOC	PRSO
	CALL	DO-FIRST,STR?19,STACK
	RSTACK	
?ELS33:	FSET?	PRSO,WORNBIT \FALSE
	CALL	DO-FIRST,STR?66,PRSO
	RSTACK	


	.FUNCT	CCOUNT,OBJ,CNT=0,X
	FIRST?	OBJ >X \?CND1
?PRG4:	FSET?	X,WORNBIT /?CND6
	INC	'CNT
?CND6:	NEXT?	X >X /?PRG4
?CND1:	RETURN	CNT


	.FUNCT	WEIGHT,OBJ,CONT,WT=0
	FIRST?	OBJ >CONT \?CND1
?PRG4:	EQUAL?	OBJ,PROTAGONIST \?ELS8
	FSET?	CONT,WORNBIT /?CND6
?ELS8:	CALL	WEIGHT,CONT
	ADD	WT,STACK >WT
?CND6:	NEXT?	CONT >CONT /?KLU23
?KLU23:	ZERO?	CONT \?PRG4
?CND1:	EQUAL?	OBJ,PROTAGONIST \?ELS20
	RETURN	WT
?ELS20:	GETP	OBJ,P?SIZE
	ADD	WT,STACK
	RSTACK	


	.FUNCT	DESCRIBE-ROOM,VERB-IS-LOOK=0,FIRST-VISIT=0,POINTS
	ZERO?	LIT \?ELS3
	PRINTI	"It is pitch black. You "
	EQUAL?	HERE,VACUUM-STORAGE \?ELS6
	PRINTI	"try desperately to remember: 1. whether grues can survive in a vacuum and 2. whether they can tear through a space suit."
	CRLF	
	RFALSE	
?ELS6:	PRINTI	"hope there are no grues aboard the station."
	CRLF	
	RFALSE	
?ELS3:	FSET?	HERE,TOUCHBIT /?CND1
	GETP	HERE,P?VALUE >POINTS
	ZERO?	POINTS /?CND11
	GRTR?	POINTS,0 \?CND14
	INC	'ROBOT-EVILNESS
?CND14:	ADD	SCORE,POINTS >SCORE
?CND11:	EQUAL?	HERE,AIR-SHAFT /?CND17
	FSET	HERE,TOUCHBIT
?CND17:	SET	'FIRST-VISIT,TRUE-VALUE
?CND1:	PRINTD	HERE
	ZERO?	HANGING-IN-AIR /?ELS22
	PRINTI	", hanging in air"
	JUMP	?CND20
?ELS22:	LOC	PROTAGONIST
	FSET?	STACK,VEHBIT \?CND20
	PRINTI	", "
	LOC	PROTAGONIST
	FSET?	STACK,INBIT \?ELS28
	PRINTC	105
	JUMP	?CND26
?ELS28:	PRINTC	111
?CND26:	PRINTC	110
	LOC	PROTAGONIST
	CALL	TPRINT,STACK
?CND20:	CRLF	
	ZERO?	VERB-IS-LOOK \?THN34
	EQUAL?	VERBOSITY,2 /?THN34
	ZERO?	FIRST-VISIT /TRUE
	EQUAL?	VERBOSITY,1 \TRUE
?THN34:	PRINTI	"   "
	GETP	HERE,P?ACTION
	CALL	STACK,M-LOOK
	ZERO?	STACK \?CND38
	GETP	HERE,P?LDESC
	PRINT	STACK
?CND38:	CRLF	
	RTRUE	


	.FUNCT	DESCRIBE-OBJECTS,O,STR,1ST?=1,AV
	LOC	WINNER >AV
	FIRST?	HERE >O /?KLU48
?KLU48:	ZERO?	O /FALSE
?PRG4:	ZERO?	O /?REP5
	CALL	DESCRIBABLE?,O
	ZERO?	STACK /?CND6
	FSET?	O,TOUCHBIT /?CND6
	GETP	O,P?FDESC >STR
	ZERO?	STR /?CND6
	PRINTI	"   "
	PRINT	STR
	FSET?	O,CONTBIT \?CND13
	ADD	D-ALL?,D-PARA?
	CALL	DESCRIBE-CONTENTS,O,TRUE-VALUE,STACK
?CND13:	CRLF	
?CND6:	NEXT?	O >O /?PRG4
	JUMP	?PRG4
?REP5:	FIRST?	HERE >O /?KLU50
?KLU50:	SET	'1ST?,TRUE-VALUE
?PRG16:	ZERO?	O /?REP17
	CALL	DESCRIBABLE?,O
	ZERO?	STACK /?CND18
	GETP	O,P?FDESC
	ZERO?	STACK /?ELS22
	FSET?	O,TOUCHBIT \?CND18
?ELS22:	GETP	O,P?DESCFCN >STR
	ZERO?	STR /?ELS28
	CALL	STR,M-OBJDESC >STR
	ZERO?	STR /?ELS28
	FSET?	O,CONTBIT \?CND31
	EQUAL?	STR,M-FATAL /?CND31
	ADD	D-ALL?,D-PARA?
	CALL	DESCRIBE-CONTENTS,O,TRUE-VALUE,STACK
?CND31:	CRLF	
	JUMP	?CND18
?ELS28:	GETP	O,P?LDESC >STR
	ZERO?	STR /?CND18
	PRINTI	"   "
	PRINT	STR
	FSET?	O,CONTBIT \?CND38
	ADD	D-ALL?,D-PARA?
	CALL	DESCRIBE-CONTENTS,O,TRUE-VALUE,STACK
?CND38:	CRLF	
?CND18:	NEXT?	O >O /?PRG16
	JUMP	?PRG16
?REP17:	CALL	DESCRIBE-CONTENTS,HERE,FALSE-VALUE,0
	ZERO?	AV /FALSE
	EQUAL?	HERE,AV /FALSE
	CALL	DESCRIBE-CONTENTS,AV,FALSE-VALUE,0
	RSTACK	


	.FUNCT	DESCRIBE-CONTENTS,OBJ,LEVEL=-1,ALL?=D-ALL?,F=0,N,1ST?=1,IT?=0,TWO?=0,START?=0,PARA?=0,DB
	EQUAL?	LEVEL,2 \?ELS3
	SET	'LEVEL,TRUE-VALUE
	SET	'PARA?,TRUE-VALUE
	SET	'START?,TRUE-VALUE
	JUMP	?CND1
?ELS3:	BTST	ALL?,D-PARA? \?CND1
	SET	'PARA?,TRUE-VALUE
?CND1:	FIRST?	OBJ >N /?KLU149
?KLU149:	ZERO?	START? \?THN17
	IN?	OBJ,ROOMS /?THN17
	FSET?	OBJ,ACTORBIT /?THN17
	ZERO?	N /FALSE
	FSET?	OBJ,CONTBIT \FALSE
	FSET?	OBJ,OPENBIT /?THN15
	FSET?	OBJ,TRANSBIT \FALSE
?THN15:	EQUAL?	LEVEL,-1 /?THN17
	FSET?	OBJ,SEARCHBIT \FALSE
?THN17:	
?PRG19:	ZERO?	N /?THN28
	CALL	DESCRIBABLE?,N
	ZERO?	STACK /?CND21
	BTST	ALL?,D-ALL? /?THN28
	CALL	SIMPLE-DESC?,N
	ZERO?	STACK /?CND21
?THN28:	ZERO?	F /?CND30
	ZERO?	1ST? /?ELS36
	SET	'1ST?,FALSE-VALUE
	EQUAL?	LEVEL,FALSE-VALUE,TRUE-VALUE \?ELS40
	ZERO?	START? \?CND34
	ZERO?	PARA? \?ELS46
	EQUAL?	OBJ,PROTAGONIST /?CND47
	PRINTI	"   "
?CND47:	SET	'PARA?,TRUE-VALUE
	JUMP	?CND44
?ELS46:	EQUAL?	LEVEL,TRUE-VALUE \?CND44
	PRINTC	32
?CND44:	CALL	DESCRIBE-START,OBJ
	JUMP	?CND34
?ELS40:	EQUAL?	LEVEL,-1 /?CND34
	PRINT	LEVEL
	JUMP	?CND34
?ELS36:	ZERO?	N /?ELS55
	PRINTC	44
	JUMP	?CND34
?ELS55:	PRINTI	" and"
?CND34:	CALL	APRINT,F
	FSET?	F,ONBIT \?CND59
	PRINTI	" (providing light)"
?CND59:	EQUAL?	F,DETONATOR \?CND62
	ZERO?	TIMER-CONNECTED \?THN67
	ZERO?	EXPLOSIVE-CONNECTED /?CND62
?THN67:	PRINTI	" (connected to the "
	ZERO?	TIMER-CONNECTED /?ELS71
	PRINTI	"timer"
	ZERO?	EXPLOSIVE-CONNECTED /?CND69
	PRINTI	" and the explosive"
	JUMP	?CND69
?ELS71:	PRINTI	"explosive"
?CND69:	PRINTC	41
?CND62:	ZERO?	IT? \?ELS81
	ZERO?	TWO? \?ELS81
	SET	'IT?,F
	JUMP	?CND30
?ELS81:	SET	'TWO?,TRUE-VALUE
	SET	'IT?,FALSE-VALUE
?CND30:	SET	'F,N
?CND21:	ZERO?	N /?CND86
	NEXT?	N >N /?CND86
?CND86:	ZERO?	F \?PRG19
	ZERO?	N \?PRG19
	ZERO?	IT? /?CND95
	ZERO?	TWO? \?CND95
	CALL	THIS-IS-IT,IT?
?CND95:	ZERO?	1ST? /?ELS102
	ZERO?	START? /?ELS102
	PRINTI	" nothing"
	RFALSE	
?ELS102:	ZERO?	1ST? \?REP20
	EQUAL?	LEVEL,FALSE-VALUE,TRUE-VALUE \?REP20
	EQUAL?	OBJ,HERE \?CND109
	FSET?	HERE,WEIGHTLESSBIT \?CND112
	EQUAL?	HERE,PET-STORE /?CND112
	PRINTI	" floating"
?CND112:	PRINTI	" here"
?CND109:	PRINTC	46
?REP20:	EQUAL?	LEVEL,FALSE-VALUE,TRUE-VALUE \?CND117
	FIRST?	OBJ >F /?KLU151
?KLU151:	
?PRG120:	ZERO?	F /?CND117
	FSET?	F,CONTBIT \?CND122
	CALL	DESCRIBABLE?,F,TRUE-VALUE
	ZERO?	STACK /?CND122
	BTST	ALL?,D-ALL? /?THN129
	CALL	SIMPLE-DESC?,F
	ZERO?	STACK /?CND122
?THN129:	SET	'DB,D-BIT
	SET	'D-BIT,FALSE-VALUE
	ZERO?	PARA? /?ELS138
	PUSH	3
	JUMP	?CND134
?ELS138:	PUSH	D-ALL?
?CND134:	CALL	DESCRIBE-CONTENTS,F,TRUE-VALUE,STACK
	ZERO?	STACK /?CND131
	SET	'1ST?,FALSE-VALUE
	SET	'PARA?,TRUE-VALUE
?CND131:	SET	'D-BIT,DB
?CND122:	NEXT?	F >F /?PRG120
	JUMP	?PRG120
?CND117:	ZERO?	1ST? \?CND142
	EQUAL?	LEVEL,FALSE-VALUE,TRUE-VALUE \?CND142
	LOC	WINNER
	EQUAL?	OBJ,HERE,STACK \?CND142
	CRLF	
?CND142:	ZERO?	1ST? \FALSE
	RTRUE	


	.FUNCT	DESCRIBE-START,OBJ
	EQUAL?	OBJ,HERE \?ELS5
	PRINT	YOU-SEE
	RTRUE	
?ELS5:	EQUAL?	OBJ,PROTAGONIST \?ELS7
	EQUAL?	D-BIT,WORNBIT \?ELS12
	PRINTI	" You are wearing"
	RTRUE	
?ELS12:	PRINTI	"You are carrying"
	RTRUE	
?ELS7:	FSET?	OBJ,SURFACEBIT /?THN17
	EQUAL?	OBJ,PILOT-SEAT,COPILOT-SEAT \?ELS16
?THN17:	PRINTI	"Sitting on"
	CALL	TPRINT,OBJ
	PRINTI	" is"
	RTRUE	
?ELS16:	PRINT	IT-SEEMS-THAT
	CALL	TPRINT,OBJ
	FSET?	OBJ,ACTORBIT \?ELS25
	PRINTI	" has"
	RTRUE	
?ELS25:	PRINTI	" contains"
	RTRUE	


	.FUNCT	DESCRIBABLE?,OBJ,CONT?=0
	FSET?	OBJ,INVISIBLE /FALSE
	EQUAL?	OBJ,WINNER /FALSE
	LOC	WINNER
	EQUAL?	OBJ,STACK \?ELS9
	LOC	WINNER
	EQUAL?	HERE,STACK \FALSE
?ELS9:	ZERO?	CONT? \?ELS13
	FSET?	OBJ,NDESCBIT /FALSE
?ELS13:	ZERO?	D-BIT /TRUE
	GRTR?	D-BIT,0 \?ELS23
	FSET?	OBJ,D-BIT \FALSE
	RTRUE	
?ELS23:	SUB	0,D-BIT
	FSET?	OBJ,STACK /FALSE
	RTRUE	


	.FUNCT	SIMPLE-DESC?,OBJ,STR
	GETP	OBJ,P?FDESC
	ZERO?	STACK /?ELS5
	FSET?	OBJ,TOUCHBIT \FALSE
?ELS5:	GETP	OBJ,P?DESCFCN >STR
	ZERO?	STR /?ELS9
	CALL	STR,M-OBJDESC?
	ZERO?	STACK \FALSE
?ELS9:	GETP	OBJ,P?LDESC
	ZERO?	STACK /TRUE
	RFALSE	


	.FUNCT	DESCRIBE-VEHICLE
	PRINTI	"Other than yourself, you can see"
	CALL	DESCRIBE-NOTHING
	ZERO?	STACK \TRUE
	FSET?	PRSO,INBIT \?ELS6
	PRINTI	" in"
	JUMP	?CND4
?ELS6:	PRINTI	" on"
?CND4:	CALL	TRPRINT,PRSO
	RTRUE	


	.FUNCT	DESCRIBE-NOTHING
	CALL	DESCRIBE-CONTENTS,PRSO,2
	ZERO?	STACK /FALSE
	IN?	PROTAGONIST,PRSO /TRUE
	CRLF	
	RTRUE	


	.FUNCT	GOTO,NEW-LOC,OLD-HERE
	GETP	HERE,P?ACTION
	CALL	STACK,M-EXIT
	IN?	FLOYD,HERE \?CND1
	FSET?	FLOYD,ACTIVEBIT \?CND1
	SET	'FLOYD-FOLLOW,TRUE-VALUE
?CND1:	SET	'OLD-HERE,HERE
	MOVE	PROTAGONIST,NEW-LOC
	SET	'HERE,NEW-LOC
	CALL	LIT?,HERE >LIT
	SET	'BALLOON-ODOR,FALSE-VALUE
	GETP	HERE,P?ACTION
	CALL	STACK,M-ENTER
	CALL	DESCRIBE-ROOM
	ZERO?	STACK /?CND6
	ZERO?	VERBOSITY /?CND6
	CALL	DESCRIBE-OBJECTS
?CND6:	IN?	OSTRICH,OLD-HERE \TRUE
	CALL	ULTIMATELY-IN?,OSTRICH-NIP
	ZERO?	STACK /TRUE
	CALL	VISIBLE?,OSTRICH-NIP
	ZERO?	STACK /TRUE
	PRINTI	"   The ostrich, sniffing excitedly, "
	CALL	GLOBAL-IN?,BED,HERE
	ZERO?	STACK /?ELS18
	PRINTR	"follows you to the door, but hesitates as she notices the bed. The ostrich, who refuses to enter any room with a bed due to a bad experience in her youth, withdraws."
?ELS18:	LOC	OSTRICH
	FSET?	STACK,WEIGHTLESSBIT \?ELS20
	PRINTI	"follows you in an awkward fashion somewhere between swimming and flying."
	JUMP	?CND16
?ELS20:	PRINTI	"trots eagerly after you."
?CND16:	EQUAL?	HERE,SOUTH-CONNECTION \?ELS29
	IN?	OSTRICH,GRIMY-PASSAGE /?THN26
?ELS29:	EQUAL?	HERE,EAST-CONNECTION \?ELS31
	IN?	OSTRICH,MAKESHIFT-CONNECTOR /?THN26
?ELS31:	IN?	OSTRICH,ELEVATOR \?ELS25
?THN26:	PRINTI	" As the ostrich crosses into gravity, it emits a surprised squawk and does a graceless bellyflop. As it struggles to its feet, it appears that only its dignity was injured."
	JUMP	?CND23
?ELS25:	EQUAL?	HERE,GRIMY-PASSAGE \?ELS37
	IN?	OSTRICH,SOUTH-CONNECTION /?THN34
?ELS37:	EQUAL?	HERE,MAKESHIFT-CONNECTOR \?ELS39
	IN?	OSTRICH,EAST-CONNECTION /?THN34
?ELS39:	EQUAL?	HERE,ELEVATOR \?CND23
?THN34:	PRINTI	" As the ostrich unexpectly enters the weightless environment of the "
	EQUAL?	HERE,ELEVATOR \?ELS42
	PRINTI	"elevator"
	JUMP	?CND40
?ELS42:	PRINTI	"village"
?CND40:	PRINTI	", it shoots into the air, sqawking loudly. It spins head over claw for a moment, thrashing its wings ineffectually, before finally acheiving a modicum of stability."
?CND23:	MOVE	OSTRICH,HERE
	CRLF	
	RTRUE	


	.FUNCT	JIGS-UP,DESC
	PRINT	DESC
	CRLF	
	CRLF	
	PRINTI	"      ****  You have died  ****"
	CRLF	
	CALL	FINISH
	RSTACK	


	.FUNCT	ACCESSIBLE?,OBJ,L
	ZERO?	OBJ /FALSE
	LOC	OBJ >L
	FSET?	OBJ,INVISIBLE /FALSE
	EQUAL?	OBJ,PSEUDO-OBJECT \?ELS10
	EQUAL?	LAST-PSEUDO-LOC,HERE \FALSE
	RTRUE	
?ELS10:	ZERO?	L /FALSE
	EQUAL?	L,GLOBAL-OBJECTS /TRUE
	EQUAL?	L,LOCAL-GLOBALS \?ELS23
	CALL	GLOBAL-IN?,OBJ,HERE
	ZERO?	STACK \TRUE
?ELS23:	CALL	META-LOC,OBJ
	EQUAL?	STACK,HERE \FALSE
	EQUAL?	L,WINNER,HERE /TRUE
	FSET?	L,OPENBIT \FALSE
	CALL	ACCESSIBLE?,L
	ZERO?	STACK /FALSE
	RTRUE	


	.FUNCT	VISIBLE?,OBJ,L
	ZERO?	OBJ /FALSE
	LOC	OBJ >L
	CALL	ACCESSIBLE?,OBJ
	ZERO?	STACK \TRUE
	CALL	SEE-INSIDE?,L
	ZERO?	STACK /FALSE
	CALL	VISIBLE?,L
	ZERO?	STACK /FALSE
	RTRUE	


	.FUNCT	UNTOUCHABLE?,OBJ
	ZERO?	OBJ /FALSE
	ZERO?	HANGING-IN-AIR /?ELS7
	IN?	OBJ,HERE \?ELS7
	EQUAL?	OBJ,STAR,ETERNAL-FLAME \TRUE
?ELS7:	IN?	PROTAGONIST,HERE /FALSE
	LOC	PROTAGONIST
	CALL	ULTIMATELY-IN?,OBJ,STACK
	ZERO?	STACK \?THN14
	LOC	PROTAGONIST
	EQUAL?	OBJ,STACK /?THN14
	LOC	OBJ
	EQUAL?	STACK,GLOBAL-OBJECTS,LOCAL-GLOBALS \?ELS13
?THN14:	FSET?	OBJ,DOORBIT \FALSE
	RTRUE	
?ELS13:	LOC	PROTAGONIST
	EQUAL?	STACK,PILOT-SEAT,COPILOT-SEAT \TRUE
	EQUAL?	OBJ,RADIO,KEYPAD,PSEUDO-OBJECT \TRUE
	RFALSE	


	.FUNCT	META-LOC,OBJ
?PRG1:	ZERO?	OBJ /FALSE
	EQUAL?	OBJ,BED \?ELS7
	RETURN	HERE
?ELS7:	IN?	OBJ,GLOBAL-OBJECTS \?CND3
	RETURN	GLOBAL-OBJECTS
?CND3:	IN?	OBJ,ROOMS \?ELS12
	RETURN	OBJ
?ELS12:	LOC	OBJ >OBJ
	JUMP	?PRG1


	.FUNCT	OTHER-SIDE,DOBJ,P=0,TEE
?PRG1:	NEXTP	HERE,P >P
	LESS?	P,LOW-DIRECTION /FALSE
	GETPT	HERE,P >TEE
	PTSIZE	TEE
	EQUAL?	STACK,DEXIT \?PRG1
	GETB	TEE,DEXITOBJ
	EQUAL?	STACK,DOBJ \?PRG1
	RETURN	P


	.FUNCT	ULTIMATELY-IN?,OBJ,CONT=0
	ZERO?	CONT \?CND1
	SET	'CONT,WINNER
?CND1:	ZERO?	OBJ /FALSE
	IN?	OBJ,CONT /TRUE
	IN?	OBJ,ROOMS /FALSE
	LOC	OBJ
	CALL	ULTIMATELY-IN?,STACK,CONT
	RSTACK	


	.FUNCT	SEE-INSIDE?,OBJ
	ZERO?	OBJ /FALSE
	FSET?	OBJ,INVISIBLE /FALSE
	FSET?	OBJ,TRANSBIT /TRUE
	FSET?	OBJ,OPENBIT /TRUE
	RFALSE	


	.FUNCT	GLOBAL-IN?,OBJ1,OBJ2,TEE
	GETPT	OBJ2,P?GLOBAL >TEE
	ZERO?	TEE /FALSE
	PTSIZE	TEE
	SUB	STACK,1
	CALL	ZMEMQB,OBJ1,TEE,STACK
	RSTACK	


	.FUNCT	FIND-IN,WHERE,FLAG-IN-QUESTION,STRING=0,OBJ,RECURSIVE-OBJ
	FIRST?	WHERE >OBJ /?KLU19
?KLU19:	ZERO?	OBJ /FALSE
?PRG4:	FSET?	OBJ,FLAG-IN-QUESTION \?ELS8
	FSET?	OBJ,INVISIBLE /?ELS8
	ZERO?	STRING /?CND11
	PRINTC	91
	PRINT	STRING
	CALL	TPRINT,OBJ
	PRINTC	93
	CRLF	
?CND11:	RETURN	OBJ
?ELS8:	CALL	FIND-IN,OBJ,FLAG-IN-QUESTION >RECURSIVE-OBJ
	ZERO?	RECURSIVE-OBJ /?ELS16
	RETURN	RECURSIVE-OBJ
?ELS16:	NEXT?	OBJ >OBJ /?PRG4
	RFALSE	


	.FUNCT	NOW-DARK?
	ZERO?	LIT /FALSE
	CALL	LIT?,HERE
	ZERO?	STACK \FALSE
	SET	'LIT,FALSE-VALUE
	PRINTR	"   It is now too dark to see."


	.FUNCT	NOW-LIT?
	ZERO?	LIT \FALSE
	CALL	LIT?,HERE
	ZERO?	STACK /FALSE
	SET	'LIT,TRUE-VALUE
	CRLF	
	CALL	V-LOOK
	RSTACK	


	.FUNCT	LOC-CLOSED,L
	LOC	PRSO >L
	FSET?	L,CONTBIT \FALSE
	FSET?	L,OPENBIT /FALSE
	FSET?	PRSO,TAKEBIT \FALSE
	CALL	DO-FIRST,STR?19,L
	RSTACK	


	.FUNCT	DO-WALK,DIR
	SET	'P-WALK-DIR,DIR
	CALL	PERFORM,V?WALK,DIR
	RSTACK	


	.FUNCT	STOP
	SET	'P-CONT,FALSE-VALUE
	SET	'QUOTE-FLAG,FALSE-VALUE
	RETURN	8


	.FUNCT	ROB,WHO,WHERE=0,N,X
	FIRST?	WHO >X /?KLU15
?KLU15:	
?PRG1:	ZERO?	X /TRUE
	NEXT?	X >N /?KLU16
?KLU16:	FSET?	X,WORNBIT /?CND6
	ZERO?	WHERE /?ELS11
	MOVE	X,WHERE
	JUMP	?CND6
?ELS11:	REMOVE	X
?CND6:	SET	'X,N
	JUMP	?PRG1


	.FUNCT	HACK-HACK,STR
	PRINT	STR
	CALL	TPRINT-PRSO
	CALL	HO-HUM
	RSTACK	


	.FUNCT	HO-HUM
	CALL	PICK-ONE,HO-HUM-LIST
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	YUKS
	CALL	PICK-ONE,YUK-LIST
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	IMPOSSIBLES
	CALL	PICK-ONE,IMPOSSIBLE-LIST
	PRINT	STACK
	CRLF	
	RTRUE	


	.FUNCT	WASTES
	CALL	PICK-ONE,WASTE-LIST
	PRINT	STACK
	CRLF	
	RTRUE	

	.ENDI
